### ISSUE TITLE
Exception running in Android error "Unknown"

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-reanimated#1028]
## Description

Works fine on iOS, however can't run my app on Android after installing this. Similar reported occurrences suggest that this was down to easing functions on 2.0.0-alpha.3 however I've yet to import the module.

### Screenshots
![image](https://user-images.githubusercontent.com/8608314/88480659-192d8100-cf4f-11ea-9758-df91fe5fe71e.png)

## Steps To Reproduce

1. install 2.0.0-alpha.4 with instruction provided

### Expected behavior
I should be able to run the app
### Actual behavior
ADB Logcat returns 

```
26 14:46:31.678 17261 17472 E unknown:ReactNative: CatalystInstanceImpl caught native exception
07-26 14:46:31.678 17261 17472 E unknown:ReactNative: com.facebook.jni.UnknownCppException: Unknown
07-26 14:46:31.678 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.678 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.678 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.678 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.678 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.678 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.678 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: Exception in native call
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: com.facebook.jni.UnknownCppException: Unknown
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.679 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.679 17261 17472 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: HMRClient.setup()
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: CatalystInstanceImpl caught native exception
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: Exception in native call
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.681 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.681 17261 17472 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: CatalystInstanceImpl caught native exception
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: Exception in native call
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.683 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.683 17261 17472 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: CatalystInstanceImpl caught native exception
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: Exception in native call
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.685 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.685 17261 17472 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: CatalystInstanceImpl caught native exception
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: Exception in native call
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.688 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.688 17261 17472 E ReactNativeJNI: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: CatalystInstanceImpl caught native exception
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: Exception in native call
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:214)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-26 14:46:31.690 17261 17472 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
```

## Package versions

- React: 16.13.1
- React Native: 0.63.1
- React Native Reanimated: 2.0.0-alpha.4

**Comment by kyle-ssg** [comment]
Going to close this, the more reading I'm doing the more it looks to be to do with hermes.

**Comment by terrysahaidak** [comment]
Yeah, it's definitely the Hermes issue. It doesn't support all the features. Check out for rest/spread operators in the code.
