### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by kangfenmao** [software-mansion/react-native-reanimated#1158]
## Description

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View com.swmansion.gesturehandler.GestureHandler.getView()' on a null object reference at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandler(GestureHandlerOrchestrator.java:279)

### Screenshots

Device:

![image](https://user-images.githubusercontent.com/8253512/91268398-da862300-e7a7-11ea-950e-e175c0ba85d1.png)

Crash line chart:

![image](https://user-images.githubusercontent.com/8253512/91268972-d9a1c100-e7a8-11ea-93cb-ff88782a0110.png)

## Steps To Reproduce

Error tracking system report this exception

## Stack

```log
java.lang.NullPointerException: Attempt to invoke virtual method &#39;android.view.View com.swmansion.gesturehandler.GestureHandler.getView()&#39; on a null object reference
	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandler(GestureHandlerOrchestrator.java:279)
	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandlers(GestureHandlerOrchestrator.java:259)
	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.java:101)
	at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.java:126)
	at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent(RNGestureHandlerEnabledRootView.java:36)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3000)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2673)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:574)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1978)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3415)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:530)
	at android.view.View.dispatchPointerEvent(View.java:12120)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4972)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4767)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4265)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4335)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4435)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4301)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4492)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4265)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4335)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4301)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4265)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6860)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6834)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6789)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6972)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6943)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6995)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
	at android.view.Choreographer.doCallbacks(Choreographer.java:737)
	at android.view.Choreographer.doFrame(Choreographer.java:663)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:911)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:192)
	at android.app.ActivityThread.main(ActivityThread.java:6840)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```

## Package versions

- React: 16.13.1
- React Native: 0.62.3
- React Native Reanimated: 1.13.0

**Comment by jakub-gonet** [comment]
Please report it in the [Gesture Handler](https://github.com/software-mansion/react-native-gesture-handler/issues) repository, stack trace doesn't mention Reanimated at all.
