### ISSUE TITLE
V2 Android crash with modal

### ISSUE THREAD

**Issue by hoangtrucit** [software-mansion/react-native-reanimated#1444]
## Description
After install `2.0.0-alpha.9`, it makes android crash without any message

## Screen shot
![image](https://user-images.githubusercontent.com/6366655/99411844-a04f9c00-2926-11eb-9f5a-ffe8f01f9705.png)

## Snack or minimal code example
[demo](https://github.com/hoangtrucit/demo-reanimated/blob/master/App.tsx)

## Package versions

- React: 17.0.1
- React Native: 0.63.3
- React Native Reanimated: 2.0.0-alpha.9
- NodeJS: v12.13.1

**Comment by kyle-ssg** [comment]
+1 modals no longer work in alpha 9

```
11-18 11:42:31.600  4696  4696 E AndroidRuntime: com.facebook.jni.CppException: Value is null, expected an Object
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 
11-18 11:42:31.600  4696  4696 E AndroidRuntime: Error: Value is null, expected an Object
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(Native Method)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:60)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.facebook.react.views.modal.ShowEvent.dispatch(ShowEvent.java:29)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:471)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:448)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:114)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.facebook.react.views.modal.ReactModalHostManager$2.onShow(ReactModalHostManager.java:121)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1358)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6138)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
11-18 11:42:31.600  4696  4696 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

```

**Comment by kyle-ssg** [comment]
I believe this is linked with https://github.com/software-mansion/react-native-reanimated/issues/1447

**Comment by hoangtrucit** [comment]
thanks @karol-bisztyga, this issue was resolve.

**Comment by kyle-ssg** [comment]
Shouldn't this be open until a version is released? Currently in Alpha 9.1 this still happens.

**Comment by dhirajanand014** [comment]
> thanks @karol-bisztyga, this issue was resolve.

In which version is this resolved. I still get the same issue for 9.1.

**Comment by karol-bisztyga** [comment]
> > thanks @karol-bisztyga, this issue was resolve.
> 
> In which version is this resolved. I still get the same issue for 9.1.

try this https://github.com/software-mansion/react-native-reanimated/releases/tag/2.0.0-alpha.9.2
