### ISSUE TITLE
App Crashes on Pull to Refresh

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#1447]
## Description

App crashes when swiping to refresh a ScrollView

**Note**: It works with `2.0.0-alpha.8` so the bug was likely introduced by `2.0.0-alpha.9`

### Screenshots

```
com.facebook.jni.CppException Value is null, expected an Object

Error: Value is null, expected an Object 
    NativeProxy.java:-2 com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent
    NativeProxy.java:60 com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent
    RefreshEvent.java:26 com.facebook.react.views.swiperefresh.RefreshEvent.dispatch
    NodesManager.java:471 com.swmansion.reanimated.NodesManager.handleEvent
    NodesManager.java:448 com.swmansion.reanimated.NodesManager.onEventDispatch
    EventDispatcher.java:114 com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent
    SwipeRefreshLayoutManager.java:147 com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager$1.onRefresh
    SwipeRefreshLayout.java:195 androidx.swiperefreshlayout.widget.SwipeRefreshLayout$1.onAnimationEnd
    CircleImageView.java:107 androidx.swiperefreshlayout.widget.CircleImageView.onAnimationEnd
    ViewGroup.java:6912 android.view.ViewGroup.finishAnimatingView
    View.java:20272 android.view.View.draw
    ViewGroup.java:4337 android.view.ViewGroup.drawChild
    ViewGroup.java:4116 android.view.ViewGroup.dispatchDraw
    View.java:20369 android.view.View.draw
    View.java:19241 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ViewGroup.java:4321 android.view.ViewGroup.recreateChildDisplayList
    ViewGroup.java:4294 android.view.ViewGroup.dispatchGetDisplayList
    View.java:19201 android.view.View.updateDisplayListIfDirty
    ThreadedRenderer.java:690 android.view.ThreadedRenderer.updateViewTreeDisplayList
    ThreadedRenderer.java:696 android.view.ThreadedRenderer.updateRootDisplayList
    ThreadedRenderer.java:805 android.view.ThreadedRenderer.draw
    ViewRootImpl.java:3517 android.view.ViewRootImpl.draw
    ViewRootImpl.java:3314 android.view.ViewRootImpl.performDraw
    ViewRootImpl.java:2683 android.view.ViewRootImpl.performTraversals
    ViewRootImpl.java:1635 android.view.ViewRootImpl.doTraversal
    ViewRootImpl.java:7788 android.view.ViewRootImpl$TraversalRunnable.run
    Choreographer.java:1004 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:816 android.view.Choreographer.doCallbacks
    Choreographer.java:751 android.view.Choreographer.doFrame
    Choreographer.java:990 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:873 android.os.Handler.handleCallback
    Handler.java:99 android.os.Handler.dispatchMessage
    Looper.java:193 android.os.Looper.loop
    ActivityThread.java:6898 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:537 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:858 com.android.internal.os.ZygoteInit.main
```

## Steps To Reproduce

Swipe down to trigger the refresh

### Expected behavior

No crash

### Actual behavior

Crash

## Snack or minimal code example

```
import React from 'react'
import {  RefreshControl, ScrollView } from 'react-native'

const Screen = function () {
  const [refresh, setRefresh] = React.useState(false)
  return (
        <ScrollView
        refreshControl={
            <RefreshControl
                refreshing={refreshing}
                onRefresh={() => console.log('refresh')}
                colors={['red']}
            />
        }>
      </ScrollView>
  )
}
```
## Package versions

- React: 16.13.1
- React Native: 0.63.2
- React Native Reanimated: ^2.0.0-alpha.9

**Comment by kyle-ssg** [comment]
Can also confirm this is happening on alpha.9 and not .8.

**Comment by gonalc** [comment]
Yes this is happening to me as well on alpha.9 when I am trying open any modal: Modal native component and tipsi-stripe generated modal.

**Comment by dhirajanand014** [comment]
I too get this issue for alpha.9. How can i get alpha.8 meanwhile when this issue is fixed?

**Comment by ajpaulingalls** [comment]
> I too get this issue for alpha.9. How can i get alpha.8 meanwhile when this issue is fixed?

Need to update both package.json and yarn.lock.  Here is the yarn.lock snippet:
```
react-native-reanimated@^2.0.0-alpha.8:
  version "2.0.0-alpha.8"
  resolved "https://registry.yarnpkg.com/react-native-reanimated/-/react-native-reanimated-2.0.0-alpha.8.tgz#9b8ce77cea315bfc356f190eecec7763d19d4c26"
  integrity sha512-WCeMwZW1ZOCkY1ANFDP2Iwei2bxO/LftxTmx0XiCbQl8+csctpB5I1GERuzCZNJZ1NLR9/LBqrJIr/Vl8/TnjQ==
  dependencies:
    "@babel/plugin-transform-object-assign" "^7.10.4"
    fbjs "^3.0.0"
    string-hash-64 "^1.0.3"
```

**Comment by kyle-ssg** [comment]
Although this currently in Alpha 9.1, there's a fix waiting in https://github.com/software-mansion/react-native-reanimated/pull/1457 to be released.

**Comment by dhirajanand014** [comment]
> Although this currently in Alpha 9.1, there's a fix waiting in #1457 to be released.

Is this available now?

**Comment by dhirajanand014** [comment]
> Although this currently in Alpha 9.1, there's a fix waiting in #1457 to be released.

Is it available now?

**Comment by kyle-ssg** [comment]
Not as far as I'm aware.

**Comment by dhirajanand014** [comment]
> Not as far as I'm aware, typo in previous comment.

This is still not fixed for version 2.0.0-alpha.9.1

**Comment by mym0404** [comment]
How is it going? will this bug be fixed next release?
This bug is produced only Android

**Comment by JB-CHAUVIN** [comment]
I still have this crash in RC 2.0 :( 

`[Tue Dec 08 2020 12:34:11.266]  WARN     Erreur xxx com.facebook.jni.CppException: Value is null, expected an Object

Error: Value is null, expected an Object
	at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(Native Method)
	at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:60)
	at com.facebook.react.views.modal.ShowEvent.dispatch(ShowEvent.java:29)
	at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:471)
	at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:448)
	at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:114)
	at com.facebook.react.views.modal.ReactModalHostManager$2.onShow(ReactModalHostManager.java:121)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1509)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`
