### ISSUE TITLE
V2 Jest mock documentation

### ISSUE THREAD

**Issue by mym0404** [software-mansion/react-native-reanimated#1463]
## Description

I upgraded v1 -> v2. My test codes are broken because of not appropriate mocking. Mainly,

- `TypeError: Cannot read property 'createNode' of undefined`
- `TypeError: global.__reanimatedWorkletInit is not a function`

```
 FAIL  src/components/screen/MainDrawer/DemoExamList/DemoExamListPage1.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'createNode' of undefined

      at AnimatedParam.__nativeInitialize (node_modules/react-native-reanimated/src/core/AnimatedNode.js:150:24)
      at AnimatedParam.__attach (node_modules/react-native-reanimated/src/core/AnimatedNode.js:98:10)
      at new AnimatedParam (node_modules/react-native-reanimated/src/core/AnimatedParam.js:12:10)
      at createAnimatedParam (node_modules/react-native-reanimated/src/core/AnimatedParam.js:87:10)
      at createAnimatedFunction (node_modules/react-native-reanimated/src/core/AnimatedFunction.js:38:17)
      at Object.<anonymous> (node_modules/react-native-reanimated/src/derived/interpolate.js:17:39)

 FAIL  src/components/shared/AnalysisGraph.test.ts
  ● Test suite failed to run

    TypeError: global.__reanimatedWorkletInit is not a function

      at animationParameter (node_modules/react-native-redash/lib/module/Animations.ts:35:14)
      at Object.<anonymous> (node_modules/react-native-redash/lib/module/Animations.ts:35:14)
      at Object.<anonymous> (node_modules/react-native-redash/lib/module/index.ts:1:1)
```

The below snippet is a mock instruction of my project.

```tsx
jest
  .mock('react-native-reanimated', () => {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const Reanimated = require('react-native-reanimated/mock');

    Reanimated.default.call = () => {};

    return Reanimated;
  })
  .mock('@react-native-community/async-storage', () => mockAsyncStorage)
  .mock('react-native-safe-area-context', () => {
    const actual = jest.requireActual('react-native-safe-area-context');

    return {
      ...actual,
      useSafeAreaInsets: () => ({ bottom: 0, left: 0, right: 0, top: 0 }),
    };
  })
  .mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');
```

### Package versions

```json
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-reanimated": "2.0.0-alpha.9.1",
    "react-native-redash": "15.11.1",
```

**Comment by mym0404** [comment]
I could resolve `TypeError: global.__reanimatedWorkletInit is not a function` with #1380

**Comment by mym0404** [comment]
maybe #1230 will fix this issue.
