### ISSUE TITLE
Attempt to invoke virtual method 'void com.swmansion.reanimated.nodes.m.addChild(com.swmansion.reanimated.nodes.m)' on a null object reference

### ISSUE THREAD

**Issue by Tanskinn** [software-mansion/react-native-reanimated#1773]
## Description

Crash reported in Crashlytics:
Attempt to invoke virtual method 'void com.swmansion.reanimated.nodes.m.addChild(com.swmansion.reanimated.nodes.m)' on a null object reference

### Expected behaviour
crash should not occur

### Actual behaviour
crash occurs

## Package versions

- React: 16.13.1
- React Native: 0.62.2
- React Native Reanimated: 1.13.2

**Comment by jakub-gonet** [comment]
Could you please provide the entire stack trace?

**Comment by Tanskinn** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.swmansion.reanimated.nodes.m.addChild(com.swmansion.reanimated.nodes.m)' on a null object reference
       at com.swmansion.reanimated.b.b(NodesManager.java:9)
       at com.swmansion.reanimated.ReanimatedModule$g.a(ReanimatedModule.java:1)
       at com.swmansion.reanimated.ReanimatedModule$d.a(ReanimatedModule.java:3)
       at com.facebook.react.uimanager.v0$s.execute(UIViewOperationQueue.java:1)
       at com.facebook.react.uimanager.v0$a.run(UIViewOperationQueue.java:10)
       at com.facebook.react.uimanager.v0.i(UIViewOperationQueue.java:11)
       at com.facebook.react.uimanager.v0.j(UIViewOperationQueue.java:1)
       at com.facebook.react.uimanager.v0$i.b(UIViewOperationQueue.java:6)
       at com.facebook.react.uimanager.e.a(GuardedFrameCallback.java:1)
       at com.facebook.react.modules.core.g$d.a(ReactChoreographer.java:7)
       at com.facebook.react.modules.core.a$a$a.doFrame(ChoreographerCompat.java:1)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1104)
       at android.view.Choreographer.doCallbacks(Choreographer.java:929)
       at android.view.Choreographer.doFrame(Choreographer.java:851)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1091)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:238)
       at android.app.ActivityThread.main(ActivityThread.java:7829)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:986)

**Comment by jakub-gonet** [comment]
Do Crashlytics report interactions made before the crash happened? If that's the case, please attach them as well.

**Comment by Tanskinn** [comment]
@jakub-gonet nothing sort of that. I've just this stack trace.

**Comment by MrAngelos6** [comment]
I have the same issue with removeChild 
![image](https://user-images.githubusercontent.com/13665765/118679509-3abd6900-b7fe-11eb-8911-c00c6bf55bcd.png)

**Comment by ngioldasis** [comment]
I have the same issue with removeChild on android 9, release-build.
my packages:
"react-native": "0.66.2",
"react-native-reanimated": "^2.2.4"

The error seems to happen when a DrawerNavigator is conditionally a) mount, b) unmount, c) re-mount again.

Any idea?

**Comment by betakurnia** [comment]
Hey I have same issue

**Comment by shanmukeshwar03** [comment]
I have the same issue , 
This is just a simple fix which worked for me

update your MainActivity.java from 

`@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);
  }`

to 

`@Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
  }`

And rebuild your app

**Comment by piaskowyk** [comment]
Sorry, unfortunately, we no longer support Reanimated v1, but if you can resolve the problem I welcome to prepare a pull request.
