### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by scrapecoder** [software-mansion/react-native-reanimated#1809]
Using `react-native-reanimated v2.0.0` causing this error on android. In IOS its working fine. don't know what causing this error on to the android devices. 
Note - I'm not debugging the app. so debugger is off

`react": "16.13.1`
`react-native": "0.63.4`
`react-native-reanimated": "^2.0.0`

**Comment by aspidvip** [comment]
```
2021-03-09 17:11:32.631 11342-11392/ru.tvil.guest E/ReactNativeJS: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
2021-03-09 17:11:32.640 11342-11392/ru.tvil.guest E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_END
2021-03-09 17:11:32.701 11342-11393/ru.tvil.guest E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.common.JavascriptException: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes, stack:
    anonymous@1:99649
    anonymous@1:101933
    anonymous@1:1365901
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1365116
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1354596
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1314216
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1312880
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1309167
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1308853
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1298952
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1296807
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1296575
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:1294909
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:633810
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:633106
    v@1:71707
    d@1:71400
    o@1:71028
    anonymous@1:78191
    v@1:71707
    d@1:71357
    o@1:71028
    global@1:70760
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
2021-03-09 17:11:32.701 11342-11393/ru.tvil.guest E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.JavascriptException: Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes, stack:
    anonymous@1:99649
```

**Comment by jakub-gonet** [comment]
Do you use Proguard? Did you specify [a rule that prevents stripping](https://docs.swmansion.com/react-native-reanimated/docs/installation#proguard) Turbomodules code?

**Comment by scrapecoder** [comment]
@jakub-gonet No, I'm not using `Proguard` neither specified any rule for Turbomodules

**Comment by jakub-gonet** [comment]
All right. Just to be sure, you cleared node_modules, metro & Gradle caches?
Do you use Expo?

**Comment by ansalmishra10** [comment]
i have cleared both my node_modules, metro & Gradle caches but the issue still persist

**Comment by scrapecoder** [comment]
@jakub-gonet I cleared all the possible things. Nah, I'm not using expo. For make sure, I created a fresh project and just installed the `react-native-reanimated v2` same issue I'm facing

**Comment by joegichuru** [comment]
experiencing the same thing

**Comment by BrendonSled** [comment]
Have you tried running the gradle clean task? How about `--reset-cache` on metro?

**Comment by aspidvip** [comment]
tried it, doesn't help

**Comment by scrapecoder** [comment]
i fixed by followed this instruction - 

[https://docs.swmansion.com/react-native-reanimated/docs/installation/](url)

after this changes make sure you clean the bundle or restart the metro

**Comment by anastely** [comment]
@jakub-gonet  I'm facing this issue just when open the Debugger, I cleared node_modules, metro & Gradle caches!

**Comment by jakub-gonet** [comment]
@anastely 

This is expected, see [this](https://docs.swmansion.com/react-native-reanimated/docs#known-problems-and-limitations), [this](https://github.com/software-mansion/react-native-reanimated/issues/1663#issuecomment-770769922) and [this](https://github.com/software-mansion/react-native-reanimated/issues/1127#issuecomment-726002170).

**Comment by arled** [comment]
if this is expected then this should not be labeled as a stable release. Wasting my time! @jakub-gonet

**Comment by arled** [comment]
@scrapecoder not the fix mate this is still an issue

**Comment by YouginaCh** [comment]
im facing the same issue
