### ISSUE TITLE
App Crash on Debug

### ISSUE THREAD

**Issue by pranshuchittora** [software-mansion/react-native-reanimated#1854]
## Description
App crashing on debugging.

Commenting out this works, error gets emitted but app doesn't crash.
```java
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
  return new ReactActivityDelegate(this, getMainComponentName()) {
    @Override
    protected ReactRootView createRootView() {
     return new RNGestureHandlerEnabledRootView(MainActivity.this);
    }
  };
}
```

### Screenshots
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at UnableToResolveError.buildCodeFrameMessage (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /home/undefined/work/round2/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /home/undefined/work/round2/node_modules/metro/src/Server.js:1471:14
    at Generator.next (<anonymous>)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at UnableToResolveError.buildCodeFrameMessage (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/home/undefined/work/round2/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /home/undefined/work/round2/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /home/undefined/work/round2/node_modules/metro/src/Server.js:1471:14
    at Generator.next (<anonymous>)

```
### Expected behavior
App should work and connect to debugger
## Package versions
```json
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0"
```

**Comment by jakub-gonet** [comment]
This is expected, see below links for more information:
- https://github.com/software-mansion/react-native-reanimated/issues/1127#issuecomment-726002170
- https://github.com/software-mansion/react-native-reanimated/issues/1663#issuecomment-770769922
- https://docs.swmansion.com/react-native-reanimated/docs#known-problems-and-limitations

**Comment by defualt** [comment]
Wish the library could fallback to a wrapper around RN's built in Animated somehow when the debugger is active.  Or maybe leverage the way reanimated is implemented for web.  Debugger incompatibility is a deal breaker.

**Comment by arled** [comment]
This is a huge dealbreaker come on fix it

**Comment by arled** [comment]
I get this as soon as I connect the debugger. ` "react-native-reanimated": "^2.0.1",`
Yes, I have followed the installation instructions. The issue only happens when I connect the debugger. So anonoying!!!!

<img width="352" alt="Screenshot 2021-03-27 at 22 36 51" src="https://user-images.githubusercontent.com/6124388/112736757-08556500-8f4d-11eb-8f73-b80b57616950.png">

**Comment by anhquan291** [comment]
> I get this as soon as I connect the debugger. ` "react-native-reanimated": "^2.0.1",`
> Yes, I have followed the installation instructions. The issue only happens when I connect the debugger. So anonoying!!!!
> 
> <img alt="Screenshot 2021-03-27 at 22 36 51" width="352" src="https://user-images.githubusercontent.com/6124388/112736757-08556500-8f4d-11eb-8f73-b80b57616950.png">

Same problem here.

**Comment by siddharthJadhav** [comment]
I am also having the same issue. Did anyone found the solution?

**Comment by Misaka-0x447f** [comment]
This is expected behavior, see the doc, reanimated2 no longer support remote debugging: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#installing-the-package
