### ISSUE TITLE
Weird error occurs rarely

### ISSUE THREAD

**Issue by heroic** [software-mansion/react-native-reanimated#1955]
## Description

On very rare occasions, we're getting a crash report in reanimated.

### Expected behavior

Should not crash

### Actual behavior & steps to reproduce

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.swmansion.reanimated.AndroidErrorHandler
        at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:20)
        at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:164)
        at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:721)
        at com.facebook.react.bridge.CatalystInstanceImpl.access$1300(CatalystInstanceImpl.java:47)
        at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:739)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Caused by: java.lang.ClassNotFoundException: com.swmansion.reanimated.AndroidErrorHandler
        at com.swmansion.reanimated.Scheduler.triggerUI(Scheduler.java:-2)
        at com.swmansion.reanimated.Scheduler.access$100(Scheduler.java:9)
        at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:21)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.1.0
- NodeJS: 12.20.0
- Java & Gradle: 1.8.0_181 gradle: 6.5

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by heroic** [comment]
@piaskowyk we are still seeing this issue with "react-native-reanimated": "^2.2.0"

**Comment by piaskowyk** [comment]
@heroic thanks for the information. We will check this.

**Comment by heroic** [comment]
@piaskowyk FYI: This is continuing still on "react-native-reanimated": "^2.2.4"

Still haven't been able to find the steps to make this occur though

**Comment by piaskowyk** [comment]
Hey, without any code to reproduce your issue unfortunately I am not able to fix it :/ Its looks like a configuration issue specific to your project. Could you try to use the newest version of reanimated?
