### ISSUE TITLE
Babel plugin cannot process arrow functions without body

### ISSUE THREAD

**Issue by savelichalex** [software-mansion/react-native-reanimated#2041]
## Description

```js
const opacity = useSharedValue(0);

// The plugin cannot transform next expression
useAnimatedStyle(() => ({
  opacity,
});
```

### Expected behavior

Should compile successfully 

### Actual behavior & steps to reproduce

Compilation produce following error:
```
{ TypeError: index.tsx: Property body of FunctionExpression expected node to be of a type ["BlockStatement"] but instead got "ObjectExpression"
    at Object.validate (node_modules/@babel/types/lib/definitions/utils.js:130:11)
    at validateField (node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (node_modules/@babel/types/lib/validators/validate.js:17:3)
    at builder (node_modules/@babel/types/lib/builders/builder.js:38:27)
    at Object.functionExpression (node_modules/@babel/types/lib/builders/generated/index.js:339:31)
    at processWorkletFunction (node_modules/react-native-reanimated/plugin.js:351:27)
    at indexes.forEach (node_modules/react-native-reanimated/plugin.js:496:9)
    at Array.forEach (<anonymous>)
    at processWorklets (node_modules/react-native-reanimated/plugin.js:495:15)
    at PluginPass.exit (/Users/savelichalex/work/tonlabs/UIKit/node_modules/react-native-reanimated/plugin.js:560:11) code: 'BABEL_TRANSFORM_ERROR' }
```

My `babel.conig.js`:
```js
module.exports = {
    presets: [
        [
            '@babel/preset-env',
            {
                targets: { node: '10' },
            },
        ],
        '@babel/preset-typescript',
    ],
    plugins: ['react-native-reanimated/plugin'],
};
```

And I'm using [bob](https://github.com/callstack/react-native-builder-bob).

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.1.0
- NodeJS: 10.15.3

**Comment by Szymon20000** [comment]
I wasn't able to reproduce it. I used node 14.15 though.

**Comment by khacbac** [comment]
I got this error as well

**Comment by piaskowyk** [comment]
Should be fixed with https://github.com/software-mansion/react-native-reanimated/pull/2169 It will be available in the next release.
