### ISSUE TITLE
Unable to run on iPhone, works on simulator

### ISSUE THREAD

**Issue by archcorsair** [software-mansion/react-native-reanimated#2042]
⚠️ - Solution Found: https://github.com/software-mansion/react-native-reanimated/issues/2042#issuecomment-846342671

## Description

I've been able to work with reanimated `2.1.0` in the iOS Simulator.
I noticed this issue when I tried to run the same code on my physical iPhone:

<img src="https://i.imgur.com/Vcnfbzu.png" height="750" />

Error in console:
```console
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:625:3)
    at tryReadSync (node:fs:390:20)
    at Object.readFileSync (node:fs:427:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/nxc/w/app/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/Users/nxc/w/app/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/Users/nxc/w/app/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/Users/nxc/w/app/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /Users/nxc/w/app/node_modules/@react-native-community/cli/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /Users/nxc/w/app/node_modules/@react-native-community/cli/node_modules/metro/src/Server.js:1471:14
    at Generator.next (<anonymous>)
```

### Steps Taken:
- Clean build
- Ensure pod was successfully installed:  `- RNReanimated (2.1.0):` from `Podfile.lock`
- Ensure babel plugin installed and listed in plugins array within `babel.config.js`
- Nuked everything with: `react-native clean-project-auto` from [react-native-clean-project](https://github.com/pmadruga/react-native-clean-project)

### Podfile
```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'App' do
  pod "ComScore", "~> 6.0"

  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # react-native-maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!()
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|
    react_native_post_install(installer)
  end
end

```

### Expected behavior

Should work on simulator and physical device

### Actual behavior & steps to reproduce
- Start metro bundle: `yarn start`
- Run simulator: `react-native run-ios` (works)
- Select physical device from Xcode dropdown and build (build successful)
- App crashes with above error

## Snack or minimal code example
N/A

## Package versions

- React Native: `0.64.1`
- React Native Reanimated: `2.1.0`
- NodeJS: `15.14.0`
- Xcode: `12.5`
- iOS: `14.5`
- Java & Gradle: `1.8.0_242-release`

## Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by archcorsair** [comment]
As a last ditch effort to make sure I exhausted every single troubleshooting step:
- Uninstalled the application entirely from the phone
- Reboot device
- Reinstalled via Xcode

This solved my issue. If anyone else experiences this problem hopefully its as simple of a fix!
