### ISSUE TITLE
2.2.0 Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found

### ISSUE THREAD

**Issue by mym0404** [software-mansion/react-native-reanimated#2168]
## Description

I bumped reanimated `2.1.0` -> `2.2.0` and suffered error like the follwoing in production build(launch time crash)
![image](https://user-images.githubusercontent.com/33388801/124223688-2aa7e180-db3f-11eb-8cec-1ff8215c5d70.png)

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
       at java.lang.System.loadLibrary(System.java:1667)
       at com.swmansion.reanimated.NativeProxy.<clinit>(NativeProxy.java:22)
       at com.swmansion.reanimated.NodesManager.initWithContext(NodesManager.java:127)
       at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:18)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1265)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
       at java.lang.Thread.run(Thread.java:919)
```

I can't sure it is related to reanimated but stack trace indicates it. 

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.2.0
- NodeJS: 
- Xcode:
- Java & Gradle: 
```
System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 988.16 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/mj/.rvm/gems/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 23.0.7344513-beta4
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey @mym0404 
You right this is a stack trace from Reanimated, but the source of the problem doesn't relate to Reanimated. Reanimated require to work `libjsc.so` if you want to use JSC runtime or `libhermes.so` if you use Hermes runtime and these .so files should be provided by React Native to .apk. So if you don't have these libs it probably means you have a configuration issue.
You should check Gradle property `enableHermes`: 
https://github.com/facebook/react-native/blob/master/template/android/app/build.gradle#L81
Reanimated check this property to choose the right runtime:
https://github.com/software-mansion/react-native-reanimated/blob/master/android-npm/build.gradle#L12
the default runtime is JSC.

**Comment by piaskowyk** [comment]
You can share me `/android/app/build.gradle` and will check it.

**Comment by mym0404** [comment]
Unfortunetly in my project, I have used hermes for a year.

I could fix it with adding line the following. it is so weird... I am really using a hermes and didn't change any setting about that recently.

```groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
import com.android.build.OutputFile
/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://reactnative.dev/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
        // the root of your project, i.e. where "package.json" lives
        root: "../../",
        enableHernes: true,
        // whether to bundle JS and assets in debug mode
        bundleInDebug: false,
        // whether to bundle JS and assets in release mode
        bundleInRelease: true,
        // the entry file for bundle generation. If none specified and
        // "index.android.js" exists, it will be used. Otherwise "index.js" is
        // default. Can be overridden with ENTRY_FILE environment variable.
        entryFile: "index.js",


//        // where to put the JS bundle asset in debug mode
//        jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
//        // where to put drawable resources / React Native assets, e.g. the ones you use via
//        // require('./image.png')), in debug mode
//        resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
//
//        // where to put the JS bundle asset in release mode
//        jsBundleDirRelease: "src/main/assets",
//        // where to put drawable resources / React Native assets, e.g. the ones you use via
//        // require('./image.png')), in release mode
//        resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
]

android {
	ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }

    defaultConfig {
        applicationId "com.iammathking"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode project.env.get("ANDROID_VERSION_CODE").toInteger()
        versionName project.env.get("ANDROID_VERSION_NAME")

        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable false
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file(project.env.get("ANDROID_UPLOAD_STORE_FILE"))
            storePassword project.env.get("ANDROID_UPLOAD_STORE_PASSWORD")
            keyAlias project.env.get("ANDROID_UPLOAD_KEY_ALIAS")
            keyPassword project.env.get("ANDROID_UPLOAD_KEY_PASSWORD")
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                		defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }
    dexOptions {
        javaMaxHeapSize "3g"
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    debugImplementation files("../../node_modules/hermes-engine/android/hermes-debug.aar")
    releaseImplementation files("../../node_modules/hermes-engine/android/hermes-release.aar")

    implementation "androidx.core:core-ktx:1.5.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    //noinspection GradleDependency
    implementation 'com.google.firebase:firebase-analytics:17.3.0'

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation "com.kakao.sdk:v2-link:2.5.1" //  Message (Kakao Link)
    implementation 'org.webkit:android-jsc:+'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
repositories {
    mavenCentral()
}

// Circle CI React Native orb
//https:\/\/github.com\/react-native-community\/react-native-circleci-orb#android
task downloadDependencies() {
    description 'Download all dependencies to the Gradle cache'
    doLast {
        configurations.findAll().each { config ->
            if (config.name.contains("minReactNative") && config.canBeResolved) {
                print config.name
                print '\n'
                config.files
            }
        }
    }
}
```

**Comment by mym0404** [comment]
what? in my gradle, 
typo in 
`enableHernes` not `enableHermes` ??????????

what a dumb;;;
