### ISSUE TITLE
Android: java.lang.RuntimeException: OnRender error

### ISSUE THREAD

**Issue by jesseproudman** [software-mansion/react-native-reanimated#2215]
## Description

On an Android release builds uploaded to a local device using `adb`, we see consistent crashes to navigation calls.  `react-native-reanimated`. These calls work fine on Android debug builds and all iOS builds.

### Expected behavior

The app not to crash.

### Actual behavior & steps to reproduce

The original exception we received was: 
```
2021-07-23 14:12:28.524 6812-6812/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appname, PID: 6812
    java.lang.RuntimeException: Exception in HostFunction: java.lang.AssertionError: Illegal type provided
    
    [native code]
    _f
    [native code]
    styleUpdater
    [native code]
    _f
    [native code]
        at com.swmansion.reanimated.AndroidErrorHandler.raise(AndroidErrorHandler.java:6)
        at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
        at com.swmansion.reanimated.Scheduler.access$100(Scheduler.java:9)
        at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:21)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6314)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

I realized we were building that distribution without Hermes. Using Hermes (and disabling the JSC Intl extensions), we get this crash at the same spot:

```
2021-07-23 16:02:25.543 27882-27882/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appname, PID: 27882
    java.lang.RuntimeException: OnRender error
        at com.swmansion.reanimated.AndroidErrorHandler.raise(AndroidErrorHandler.java:6)
        at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
        at com.swmansion.reanimated.Scheduler.access$100(Scheduler.java:9)
        at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:21)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6314)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

## Snack or minimal code example

I'm working on identifying what specifically in the code is causing the crash.

## Package versions

- React Native: 0.64.0
- React Native Reanimated: 2.1.0 (same crash occurs on 2.2.0)
- NodeJS: v16.3.0
- Java & Gradle: 
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
Gradle 6.7.1
```

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by jesseproudman** [comment]
The error is originating from here:
https://github.com/software-mansion/react-native-reanimated/blob/0c2f66f9855a26efe24f52ecff927fe847f7a80e/Common/cpp/NativeModules/NativeReanimatedModule.cpp#L273

**Comment by jesseproudman** [comment]
This may be related to #2213.

**Comment by jesseproudman** [comment]
Confirmed, this is a duplicate of #2213.
