### ISSUE TITLE
Cannot use `runOnJS` in other workletized runtime (VisionCamera Frame Processor Runtime)

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-reanimated#2239]
## Description

VisionCamera supports a feature called ["Frame Processors"](https://mrousavy.github.io/react-native-vision-camera/docs/guides/frame-processors), which provide an API where you can run JS code on every frame the camera sees. So if the camera runs at 30 FPS, the "Frame Processor" function gets called 30 times a second, with the current `Frame` passed in (a `jsi::HostObject`). To achieve maximum performance, I run this code in a workletized Runtime on a parallel Thread, which is powered by Reanimated. I have made numerous fixes in the Reanimated codebase to support this feature and enable other third party libraries to benefit from the native Reanimated workletization code such as VisionCamera.

Now I tried to add `console.log`ging support which should log to the React-JS Thread's console to display logs in metro - I want to achieve this by polyfilling `console.log` with a `runOnJS` call to the actual  `console.log` func on the React-JS Thread, so here's my code for that:

```ts
const capturableConsole = console;

export function useFrameProcessor(frameProcessor: FrameProcessor, dependencies: DependencyList) {
  return useCallback((frame: Frame) => {
    'worklet';

    if (global.didSetConsole == null || global.didSetConsole === false) {
      const console = {
        debug: runOnJS(capturableConsole.debug),
        log: runOnJS(capturableConsole.log),
        warn: runOnJS(capturableConsole.warn),
        error: runOnJS(capturableConsole.error),
        info: runOnJS(capturableConsole.info),
      };
      _setGlobalConsole(console);
      global.didSetConsole = true;
    }

    frameProcessor(frame);
  }, dependencies);
}
```

This works fine on iOS with the latest alpha.2, but somehow breaks on Android with the following errors:

```
2021-07-30 09:52:48.208 26359-26575/com.mrousavy.camera.example E/ReactNativeJS: 'Error: Requiring module "../node_modules/react-native-reanimated/src/Animated.js", which threw an exception: Invariant Violation: Tried to register two views with the same name REALayoutView, js engine: hermes', '\n    at CameraPage (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.mrousavy.camera.example&modulesOnly=false&runModule=true:117139:27)\n    at GestureHandlerRootView\n    at GestureHandlerRootView (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.mrousavy.camera.example&modulesOnly=false&runModule=true:151808:24)\n    at gestureHandlerRootHOC(CameraPage)\n    at WrappedComponent (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.mrousavy.camera.example&modulesOnly=false&runModule=true:106385:84)\n    at RCTView\n    at View\n    at RCTView\n    at View\n    at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.mrousavy.camera.example&modulesOnly=false&runModule=true:74525:36)'
2021-07-30 09:52:48.230 26359-26575/com.mrousavy.camera.example E/ReactNativeJS: TypeError: Cannot read property 'runOnJS' of undefined
    
    This error is located at:
        in CameraPage (at gestureHandlerRootHOC.tsx:13)
        in GestureHandlerRootView (at GestureHandlerRootView.android.tsx:26)
        in GestureHandlerRootView (at gestureHandlerRootHOC.tsx:12)
        in gestureHandlerRootHOC(CameraPage) (at ComponentWrapper.js:42)
        in WrappedComponent (at renderApplication.js:47)
        in RCTView (at View.js:34)
        in View (at AppContainer.js:107)
        in RCTView (at View.js:34)
        in View (at AppContainer.js:134)
        in AppContainer (at renderApplication.js:40), js engine: hermes
2021-07-30 09:52:48.233 26359-26575/com.mrousavy.camera.example E/ReactNativeJS: TypeError: Cannot read property 'runOnJS' of undefined
    
    This error is located at:
        in CameraPage (at gestureHandlerRootHOC.tsx:13)
        in GestureHandlerRootView (at GestureHandlerRootView.android.tsx:26)
        in GestureHandlerRootView (at gestureHandlerRootHOC.tsx:12)
        in gestureHandlerRootHOC(CameraPage) (at ComponentWrapper.js:42)
        in WrappedComponent (at renderApplication.js:47)
        in RCTView (at View.js:34)
        in View (at AppContainer.js:107)
        in RCTView (at View.js:34)
        in View (at AppContainer.js:134)
        in AppContainer (at renderApplication.js:40), js engine: hermes
2021-07-30 09:52:48.282 26359-26359/com.mrousavy.camera.example E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.JSApplicationIllegalArgumentException: Animated node with ID 2 already exists
        at com.swmansion.reanimated.NodesManager.createNode(NodesManager.java:317)
        at com.swmansion.reanimated.ReanimatedModule$2.execute(ReanimatedModule.java:117)
        at com.swmansion.reanimated.ReanimatedModule$1.execute(ReanimatedModule.java:87)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:573)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1079)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

Unfortunately I really don't know how to debug this / tackle the problem and find a solution, as Reanimated is distributed as a `.aar` file and for this reason I cannot make quick local changes in my `node_modules` to test them.

You can reproduce this by cloning react-native-vision-camera from [the `feat/console-logging-js` branch](https://github.com/mrousavy/react-native-vision-camera/tree/feat/console-logging-js) and simply running `yarn bootstrap` to set everything up. Then just run the `example/android` app using Android Studio.

Relevant code spots:

* [`FrameProcessorRuntimeManager.cpp` where the "adaption" from a jsi::Value -> Worklet occurs](https://github.com/mrousavy/react-native-vision-camera/blob/b5c8f4952aca06272d88c220fdf57a01f294d394/android/src/main/cpp/FrameProcessorRuntimeManager.cpp#L146-L171)
* [`useFrameProcessor.ts` where the console capture & `runOnJS` call happens](https://github.com/mrousavy/react-native-vision-camera/blob/b5c8f4952aca06272d88c220fdf57a01f294d394/src/hooks/useFrameProcessor.ts#L9-L45)

### Expected behavior

I expect it to behave like on iOS where no error is thrown

### Actual behavior & steps to reproduce

Android app crashes with error above. Reproduce with VisionCamera example code

## Snack or minimal code example

* [VisionCamera from the `feat/console-logging-js` branch](https://github.com/mrousavy/react-native-vision-camera/tree/feat/console-logging-js)

## Package versions

- React Native: 0.64.2
- React Native Reanimated: 2.3.0-alpha.2
- NodeJS: 14
- Xcode: /
- Java & Gradle:

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by mrousavy** [comment]
Maybe also worth mentioning that it does work when I replace:

```diff
-      info: runOnJS(capturableConsole.info),
+      info: capturableConsole.info.__callAsync,
```

Seems like there still is some sort of incorrect Runtime check (maybe a `isWorkletRuntime(...)` where a strict runtime equality comparison is required?) which causes those errors, because if I try to extract that code into a separate function like this:

```ts
function assertConsoleIsSet() {
  'worklet';
  // @ts-expect-error
  if (global.didSetConsole == null || global.didSetConsole === false) {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
    if (capturableConsole?.debug?.__callAsync == null) return;
    const console = {
      // @ts-expect-error __callAsync is injected by native REA
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      debug: capturableConsole.debug.__callAsync,
      // @ts-expect-error __callAsync is injected by native REA
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      log: capturableConsole.log.__callAsync,
      // @ts-expect-error __callAsync is injected by native REA
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      warn: capturableConsole.warn.__callAsync,
      // @ts-expect-error __callAsync is injected by native REA
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      error: capturableConsole.error.__callAsync,
      // @ts-expect-error __callAsync is injected by native REA
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
      info: capturableConsole.info.__callAsync,
    };
    // @ts-expect-error _setGlobalConsole is set by RuntimeDecorator::decorateRuntime
    _setGlobalConsole(console);
    // @ts-expect-error
    global.didSetConsole = true;
  }
}
```

I am still getting the following error immediatelly on app startup (before `useFrameProcessor` is even called):

```
2021-07-30 10:24:44.757 30688-30757/com.mrousavy.camera.example E/ReactNativeJS: TypeError: undefined is not a function, js engine: hermes
```

🤔🤔🤔🤔

**Comment by nomi9995** [comment]
I am getting issues on the sentry for some devices like Samsung j6+. I am using `react-native-reanimated@2.3.1`
```
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: Cannot read property '__callAsync' of undefined
    
    TypeError: Cannot read property '__callAsync' of undefined
```

**Comment by jakub-gonet** [comment]
Unfortunately, we won't likely support this use-case in Reanimated since it's related to another runtime. Sorry!
