### ISSUE TITLE
Null pointer exception on Android when restarting the app

### ISSUE THREAD

**Issue by bobsmits** [software-mansion/react-native-reanimated#2288]
We use https://www.npmjs.com/package/react-native-restart to restart our app, this in combination with a component that keeps track of the app state, leads to a null pointer exception coming from reanimated 2.

I haven't seen the error when re-starting the app manually. But it's not in production yet.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.uimanager.UIManagerModule.prependUIBlock(com.facebook.react.uimanager.UIBlock)' on a null object reference
       at com.swmansion.reanimated.layoutReanimation.ReactBatchObserver.willMount(ReactBatchObserver.java:94)
       at com.swmansion.reanimated.layoutReanimation.ReactBatchObserver$FakeLastRootShadowNode.calculateLayout(ReactBatchObserver.java:175)
       at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:878)
       at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:633)
       at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:594)
       at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:799)
       at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:119)
       at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:171)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:246)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:923)
```

### Steps to reproduce
```
import RNRestart from 'react-native-restart';
import React from 'react';
import {View, Button, AppState} from 'react-native';

class AppStateCro extends React.Component {
  state = {
    appState: AppState.currentState,
  };

  componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this.handleAppStateChange);
  }

  handleAppStateChange = (nextAppState) => {
    const {appState} = this.state;

    if (appState.match(/inactive|background/) && nextAppState === 'active') {
      // logEvent('app_active_foreground');
    }

    if (appState.match(/active/) && nextAppState === 'inactive') {
      // logEvent('app_active_background');
    }

    this.setState({appState: nextAppState});
  };

  render() {
    return null;
  }
}


class Restart extends React.PureComponent {
  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center'}}>
        <AppStateCro />
        <Button
          style={{
            marginTop: 100,
            width: 100,
            height: 50,
          }}
          onPress={() => {
            RNRestart.Restart();
          }}
          color="green"
          title="Restart"
        />
      </View>
    );
  }
}

export default Restart;
```
The above code will crash the app pretty consistently. I noticed we where using the state to keep track of the last app state, this will cause a re-render. When changing the component so it doesn't re-rerender using shouldComponentUpdate or a class variable the null pointer exception disappears. 

For now I have a workaround but there is probably something underlying wrong in ReactBatchObserver.java:94. My Android skill are non existing so I can't fix this for you guys.

## Package versions

- React Native: 0.63.3
- React Native Reanimated: Alpha 2
```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 19.48 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/redacted/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Hey @bobsmits 
This issue should be fixed by: https://github.com/software-mansion/react-native-reanimated/tree/%40szymon/remove_animated_layout
This branch is almost ready.

**Comment by piaskowyk** [comment]
I tested it on 2.3.0-alpha-3 and the issue no longer occurs. 🚀
