### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

### ISSUE THREAD

**Issue by 90minutes** [software-mansion/react-native-reanimated#2369]
## Description

2.3.0-alpha.2 worked just fine but 2.3.0-alpha.3 crashes with this error:

## Stack trace:

```
E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.swmansion.reanimated.layoutReanimation.AnimationsManager.onViewCreate(AnimationsManager.java:121)
        at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.applyLayoutUpdate(ReanimatedNativeHierarchyManager.java:76)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:253)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:223)
        at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.updateLayout(ReanimatedNativeHierarchyManager.java:153)
        at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:169)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:914)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Unknown Source:12)
        at android.view.Choreographer.doCallbacks(Unknown Source:79)
        at android.view.Choreographer.doFrame(Unknown Source:180)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:9)
        at android.os.Handler.handleCallback(Unknown Source:2)
        at android.os.Handler.dispatchMessage(Unknown Source:4)
        at android.os.Looper.loop(Unknown Source:249)
        at android.app.ActivityThread.main(Unknown Source:131)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
        at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
 ```

## Package versions

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-alpha.3
- NodeJS: 16
- Gradle: 4.2.2

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by mohamadnavabi** [comment]
try this:

`npm i react-native-reanimated@^1.13.2`

**Comment by Pix-00** [comment]
Same issue, I also tested with a brand new project.
I created a new project, I added the dependencies, I compiled, and it crushed with the same error.

Environments:
Gradle Wrapper: 7.0.2
Gradle Plugin: 7.0.1
react: 17.0.2
react-native: 0.65.1 (no expo)
react-native-reanimated: 2.3.0-alpha.3

**Comment by piaskowyk** [comment]
Hey @90minutes, @Pix-00 👋
Could you provide an example code when this error is occurring? I can't reproduce it in my app.

**Comment by Pix-00** [comment]
> Hey @90minutes, @Pix-00 👋
> Could you provide an example code when this error is occurring? I can't reproduce it in my app.

uhmmmmmm.... 
I am afraid that it is not possible to provide "example code", as it crashed on a brand new and empty project that I have not put any of my codes in yet.

Setps:
1 create a new project by `npx react-native init Test --template react-native-template-typescript`
2 install only react-native-reanimated by `yarn add react-native-reanimated@alpha`
3 modify the version of Gradle Wrapper and Gradle Plugin under the project's android folder
4 compile and run by `yarn android`
5 crash

Environments:
OS: Windows 11 / Android 10
OpenJDK: 16.0.2.7-hotspot
Gradle Wrapper: 7.0.2
Gradle Plugin: 7.0.1
react: 17.0.2
react-native: 0.65.1 (no expo)
react-native-reanimated: 2.3.0-alpha.3

**Comment by geekiam23** [comment]
Same here. 

react: 17.0.2
react-native: 0.65.1 (no expo)
react-native-reanimated: 2.3.0-alpha.3

Spun up a new app and trying to get it up and running. Seems like it has to do with react-native: 0.65 bc I did not have this issue with .64. 

Hope this helps. If I can provide any more clarification please let me know.

**Comment by fgagneten** [comment]
+1 Same issue here with RN 0.65

**Comment by anjob1** [comment]
+1 I have the same issue since upgrading from RN 0.64 to 0.65.1

react: 17.0.2
react-native: 0.65.1 (no expo)
react-native-reanimated: 2.3.0-alpha.3

**Comment by mohamedhelmi70** [comment]
+1 Same issue here with RN 0.65.1

**Comment by piaskowyk** [comment]
It looks like you missed the configuration step for android. Did you do these instructions from the manual https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#android?

**Comment by piaskowyk** [comment]
I can confirm that this issue occurs if someone missed configuration steps for Android.

**Comment by 90minutes** [comment]
Got the app to work after following the steps from docs! Closing this for now...

**Comment by Pix-00** [comment]
Thanks very much, it works!

I do missed the configuration step, and also forget to check the documents again.
Sorry for that (ノへ￣、).

**Comment by piaskowyk** [comment]
No problem, I am happy that it helped 😃

**Comment by Pix-00** [comment]
> We have a plan to replace manual installation with automatic installation.

That will be GREAT!

**Comment by hamzaouhssain1993** [comment]
2.2.2 fixed the issue for me
