### ISSUE TITLE
[2.3.0-alpha.3] ViewManager for tag 245 could not be found.

### ISSUE THREAD

**Issue by 0nlyDev** [software-mansion/react-native-reanimated#2394]
## Description

Getting the error when using the package in conjunction with react-native-google-places-autocomplete. Might be related to https://github.com/software-mansion/react-native-reanimated/issues/2393
![Capture](https://user-images.githubusercontent.com/89726447/132599386-50908d5f-2f6f-4f05-a03b-733a3889094b.PNG)

### Expected behavior
To be able to click on the results without throwing an error
### Actual behavior & steps to reproduce
Install "react-native": "0.65.1", "react-native-google-places-autocomplete": "^2.4.1", "react-native-reanimated": "^2.3.0-alpha.3",
Then run the example code from bellow, add a letter to the current text to see some results, and click on some (they might not be clickable so keep trying results near the end)

## Snack or minimal code example
```
import React from 'react';
import { GooglePlacesAutocomplete } from 'react-native-google-places-autocomplete';

const GooglePlacesInput = () => {
  return (
    <GooglePlacesAutocomplete
      placeholder='Search'
      onPress={(data, details = null) => {
        // 'details' is provided when fetchDetails = true
        console.log(data, details);
      }}
      query={{
        key: 'YOUR API KEY',
        language: 'en',
      }}
      requestUrl={{
        useOnPlatform: 'web', // or "all"
        url:
          'https://cors-anywhere.herokuapp.com/https://maps.googleapis.com/maps/api', // or any proxy server that hits https://maps.googleapis.com/maps/api
        headers: {
          Authorization: `an auth token`, // if required for your proxy
        },
      }}
    />
  );
};

export default GooglePlacesInput;

```

## Package versions
`"scripts": { "android": "react-native run-android", "ios": "react-native run-ios", "start": "react-native start", "test": "jest", "lint": "eslint ." }, "dependencies": { "@react-native-masked-view/masked-view": "^0.2.6", "@react-navigation/drawer": "^6.1.4", "@react-navigation/native": "^6.0.2", "@react-navigation/native-stack": "^6.1.0", "react": "17.0.2", "react-native": "0.65.1", "react-native-geolocation-service": "^5.3.0-beta.2", "react-native-gesture-handler": "^1.10.3", "react-native-google-places-autocomplete": "^2.4.1", "react-native-maps": "0.28.0", "react-native-maps-directions": "^1.8.0", "react-native-reanimated": "^2.3.0-alpha.3", "react-native-safe-area-context": "^3.3.2", "react-native-screens": "^3.6.0", "react-native-vector-icons": "^8.1.0" }, "devDependencies": { "@babel/core": "^7.12.9", "@babel/runtime": "^7.12.5", "@react-native-community/eslint-config": "^2.0.0", "babel-jest": "^26.6.3", "eslint": "7.14.0", "jest": "^26.6.3", "metro-react-native-babel-preset": "^0.66.0", "react-native-codegen": "^0.0.7", "react-test-renderer": "17.0.2" }, "jest": { "preset": "react-native"`

## Affected platforms

- Android

**Comment by Szymon20000** [comment]
Did anyone encounter a similar issue but without using react-native-google-places-autocomplete?

**Comment by TatuUlmanen** [comment]
I am receiving `ViewManager for tag -1 could not be found.` and no react-native-google-places-autocomplete installed. Unable to pinpoint the culprit, but -1 seems like a special case that could / should be handled without raising errors?

Downgrading to 2.3.0-alpha.2 got rid of the error, but Layout animations stopped working.

```
com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag -1 could not be found.
  at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:112)
  at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.dfs(ReanimatedNativeHierarchyManager.java:109)
  at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.deleteView(ReanimatedNativeHierarchyManager.java:103)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:489)
  at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:205)
  at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:211)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:908)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1019)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1079)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
  at android.view.Choreographer.doCallbacks(Choreographer.java:790)
  at android.view.Choreographer.doFrame(Choreographer.java:721)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
  at android.os.Handler.handleCallback(Handler.java:883)
  at android.os.Handler.dispatchMessage(Handler.java:100)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7356)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by morri1eu** [comment]
> Did anyone encounter a similar issue but without using react-native-google-places-autocomplete?

I am having a similar issue without using  react-native-google-places-autocomplete. Have you found a workaround?

**Comment by Szymon20000** [comment]
@morri1eu  Can you share your code?
