### ISSUE TITLE
Build on android fails for version 2.2.1

### ISSUE THREAD

**Issue by aprilmintacpineda** [software-mansion/react-native-reanimated#2412]
## Description

when running `cd android && ./gradlew clean && cd .. && react-native run-android --variant=devDebug --appIdSuffix=dev` I get the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'my-app/node_modules/react-native-reanimated/android/build.gradle' line: 85

* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.
```

[see in diff](https://github.com/software-mansion/react-native-reanimated/compare/2.2.0...2.2.1#diff-d260c332176b5c72008900aef1116a89a873451c7388a808c8d2d58be0865d38R85)

### Expected behavior

Should not crash 

### Actual behavior & steps to reproduce

Update from 2.2.0 to 2.2.1

## Package versions

- React Native:  `"react-native": "0.64.2",`
- React Native Reanimated: `"react-native-reanimated": "^2.2.1",`
- NodeJS: `v16.8.0`
- Xcode: N/A
- Java & Gradle: N/A

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by samaneh-kamalian** [comment]
> ## Description
> when running `cd android && ./gradlew clean && cd .. && react-native run-android --variant=devDebug --appIdSuffix=dev` I get the following error:
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'my-app/node_modules/react-native-reanimated/android/build.gradle' line: 85
> 
> * What went wrong:
> A problem occurred evaluating project ':react-native-reanimated'.
> > Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.
> ```
> 
> [see in diff](https://github.com/software-mansion/react-native-reanimated/compare/2.2.0...2.2.1#diff-d260c332176b5c72008900aef1116a89a873451c7388a808c8d2d58be0865d38R85)
> 
> ### Expected behavior
> Should not crash
> 
> ### Actual behavior & steps to reproduce
> Update from 2.2.0 to 2.2.1
> 
> ## Snack or minimal code example
> ## Package versions
> * React Native:  `"react-native": "0.64.2",`
> * React Native Reanimated: `"react-native-reanimated": "^2.2.1",`
> * NodeJS: `v16.8.0`
> * Xcode: N/A
> * Java & Gradle: N/A
> 
> ## Affected platforms
> * [x]  Android
> * [ ]  iOS
> * [ ]  Web

Same problem. is there any solution?

**Comment by aprilmintacpineda** [comment]
Haven't found anything for me.

**Comment by samaneh-kamalian** [comment]
Can any of the authors solve this problem? My code used to work and now that we are close to the pilot we have this problem!
Thank you in advance.

**Comment by edxds** [comment]
@aprilmintacpineda Have you initialized your project with `react-native init`? I'm having the same problem, but my project is an already existing Android application. 

I observed that projects bootstrapped with `react-native init` have the `mergeNativeLibs` task, but mine - and presumably yours too - don't. 

Maybe the library authors can shed some light on where that task comes from?

**Comment by aprilmintacpineda** [comment]
> Have you initialized your project with react-native init

Yes.

> I observed that projects bootstrapped with react-native init have the mergeNativeLibs task,

All versions or just the latest version?

**Comment by aprilmintacpineda** [comment]
Sorry, I did not mean to close this.

**Comment by edxds** [comment]
> All versions or just the latest version?

I tested the latest version of the `react-native` CLI with RN versions 0.64.2 and 0.65, and they both generated Android projects with the `mergeNativeLibs` task.

**Comment by aprilmintacpineda** [comment]
> > All versions or just the latest version?
> 
> I tested the latest version of the `react-native` CLI with RN versions 0.64.2 and 0.65, and they both generated Android projects with the `mergeNativeLibs` task.

Hmmm... I'm currently on 0.64 but my app was not originally 0.64, I started at lower version and just updated. Doing a global search for `mergeNativeLibs ` doesn't show any results. I use https://react-native-community.github.io/upgrade-helper/ when upgrading.

**Comment by edxds** [comment]
> Doing a global search for `mergeNativeLibs ` doesn't show any results.

Yeah, I have barely a clue on where it comes from. Doing a quoted Google search shows [this](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/MergeNativeLibsTask.kt), which is not very useful. To my understanding, it's related to Android's NDK, but specifying it in my Gradle files yielded no results.

**Comment by jplandry908** [comment]
I'm on 64.2 and having the same issue. I rolled back to 2.2.0, which is working fine.

**Comment by samaneh-kamalian** [comment]
> I'm on 64.2 and having the same issue. I rolled back to 2.2.0, which is working fine.

I use react-native 63.4 and react-native-reanimated 2.2.0 , but it does not build and gives such an error:

```
A problem occurred evaluating project ':react-native-reanimated'.
Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.
```

**Comment by aprilmintacpineda** [comment]
Wait, what? 

> > I'm on 64.2 and having the same issue. I rolled back to 2.2.0, which is working fine.
> 
> I use react-native 63.4 and react-native-reanimated 2.2.0 , but it does not build and gives such an error:
> 
> ```
> A problem occurred evaluating project ':react-native-reanimated'.
> Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.
> ```

Wait, what? can you do a global search for `app:mergeDebugNativeLibs `? Do `grep -r "app:mergeDebugNativeLibs"` or something similar....

**Comment by samaneh-kamalian** [comment]
yes. I searched a lot. I found a solution that said to add this lines to app/build.gradle but have same error: 

```
android{
    packagingOptions {
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/arm64-v8a/libc++_shared.so'
    }
}
```

**Comment by samaneh-kamalian** [comment]
Does anyone have a solution? I really stopped

**Comment by samaneh-kamalian** [comment]
> > I'm on 64.2 and having the same issue. I rolled back to 2.2.0, which is working fine.
> 
> I use react-native 63.4 and react-native-reanimated 2.2.0 , but it does not build and gives such an error:
> 
> ```
> A problem occurred evaluating project ':react-native-reanimated'.
> Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.
> ```

Does anyone have a solution? I really stopped

**Comment by piaskowyk** [comment]
The temporary solution is to replace reanimated/build.gradle with this https://raw.githubusercontent.com/software-mansion/react-native-reanimated/2.2.0/android-npm/build.gradle

**Comment by aprilmintacpineda** [comment]
I can confirm that version 2.2.1 works with react-native 0.65.1

**Comment by Yonom** [comment]
I was getting the following slightly-different error, the fix from @piaskowyk worked for me!

```
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:mergeDebugNativeLibs'.
[RUN_GRADLEW] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[RUN_GRADLEW]    > More than one file was found with OS independent path 'lib/x86/libfbjni.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
```

<details>
  <summary>Here's a <a href="https://www.npmjs.com/package/patch-package">patch-package</a> patch to fix the issue</summary>

`react-native-reanimated+2.2.1.patch`

```patch
diff --git a/node_modules/react-native-reanimated/android/build.gradle b/node_modules/react-native-reanimated/android/build.gradle
index ddeabe1..29a49ab 100644
--- a/node_modules/react-native-reanimated/android/build.gradle
+++ b/node_modules/react-native-reanimated/android/build.gradle
@@ -1,6 +1,4 @@
-import groovy.json.JsonSlurper
-import java.util.regex.Matcher
-import java.util.regex.Pattern
+import groovy.json.JsonSlurper;
 configurations.maybeCreate("default")
 
 def inputFile = new File(projectDir, '../../react-native/package.json')
@@ -9,92 +7,8 @@ def reactNativeVersion = json.version as String
 def (major, minor, patch) = reactNativeVersion.tokenize('.')
 
 def engine = "jsc"
-
-abstract class replaceSoTask extends DefaultTask {
-    public static String appName = ":app"
-    public static String buildDir = "../../../android/app/build"
-    public static String engine = "jsc"
-    public static String reactVersion = "64"
-
-    @TaskAction
-    def run() {
-        ant.unzip(
-            src: "./react-native-reanimated-${reactVersion}-${engine}.aar",
-            dest: "./tmp"
-        )
-        for(def abiVersion in ["x86", "x86_64", "armeabi-v7a", "arm64-v8a"]) {
-            ant.sequential {
-                copy(
-                    tofile: "${buildDir}/intermediates/merged_native_libs/debug/out/lib/${abiVersion}/libfbjni.so",
-                    file: "./tmp/jni/${abiVersion}/libfbjni.so",
-                    overwrite: true
-                )
-            }
-        }
-    }
-}
-
-def getCurrentFlavor() {
-    Gradle gradle = getGradle()
-    String taskRequestName = gradle.getStartParameter().getTaskRequests().toString()
-    Pattern pattern
-
-    if(taskRequestName.contains("assemble")) {
-        pattern = Pattern.compile("assemble(\\w+)(Release|Debug)")
-    }
-    else {
-        pattern = Pattern.compile("generate(\\w+)(Release|Debug)")
-    }
-    Matcher matcher = pattern.matcher(taskRequestName)
-
-    if(matcher.find()) {
-        return matcher.group(1).toLowerCase()
-    }
-    return ""
+if (project(':app').ext.react.enableHermes) {
+    engine = "hermes"
 }
 
-def replaceSoTaskDebug
-def replaceSoTaskRelease
-if(Integer.parseInt(minor) < 65) {
-    tasks.register("replaceSoTaskDebug", replaceSoTask)
-    tasks.register("replaceSoTaskRelease", replaceSoTask)
-    replaceSoTaskDebug = project.getTasks().getByPath(":react-native-reanimated:replaceSoTaskDebug")
-    replaceSoTaskRelease = project.getTasks().getByPath(":react-native-reanimated:replaceSoTaskRelease")
-}
-
-rootProject.getSubprojects().forEach({project ->
-    if (project.plugins.hasPlugin("com.android.application")) {
-        if(project.ext.react.enableHermes) {
-            engine = "hermes"
-        }
-
-        if(project.getProperties().get("android") && Integer.parseInt(minor) < 65) {
-            def projectProperties = project.getProperties()
-            if(!projectProperties.get("reanimated")
-                || (projectProperties.get("reanimated") && projectProperties.get("reanimated").get("enablePackagingOptions"))
-            ) {
-                def flavorString = getCurrentFlavor()
-                replaceSoTask.appName = project.getProperties().path
-                replaceSoTask.buildDir = project.getProperties().buildDir
-                replaceSoTask.engine = engine
-                replaceSoTask.reactVersion = minor
-                def appName = project.getProperties().path
-                project.getProperties().android.packagingOptions.pickFirst("lib/**/libfbjni.so")
-
-                replaceSoTaskDebug.dependsOn(
-                    project.getTasks().getByPath("${appName}:merge${flavorString}DebugNativeLibs"),
-                    project.getTasks().getByPath("${appName}:strip${flavorString}DebugDebugSymbols")
-                )
-                project.getTasks().getByPath("${appName}:package${flavorString}Debug").dependsOn(replaceSoTaskDebug)
-
-                replaceSoTaskRelease.dependsOn(
-                    project.getTasks().getByPath("${appName}:merge${flavorString}ReleaseNativeLibs"),
-                    project.getTasks().getByPath("${appName}:strip${flavorString}ReleaseDebugSymbols")
-                )
-                project.getTasks().getByPath("${appName}:package${flavorString}Release").dependsOn(replaceSoTaskRelease)
-            }
-        }
-    }
-})
-
 artifacts.add("default", file("react-native-reanimated-${minor}-${engine}.aar"))
\ No newline at end of file

```

</details>

**Comment by edxds** [comment]
> I was getting the following slightly-different error, the fix from @piaskowyk worked for me!
> 
> ```
> [RUN_GRADLEW] FAILURE: Build failed with an exception.
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] Execution failed for task ':app:mergeDebugNativeLibs'.
> [RUN_GRADLEW] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> [RUN_GRADLEW]    > More than one file was found with OS independent path 'lib/x86/libfbjni.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
> ```
> 
> Here's a [patch-package](https://www.npmjs.com/package/patch-package) patch to fix the issue

In your case, you shouldn't need to modify the library's Gradle files. [This StackOverflow answer](https://stackoverflow.com/a/64116311) should fix your problem.

**Comment by robertherber** [comment]
> I was getting the following slightly-different error, the fix from @piaskowyk worked for me!
> 
> ```
> [RUN_GRADLEW] FAILURE: Build failed with an exception.
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] Execution failed for task ':app:mergeDebugNativeLibs'.
> [RUN_GRADLEW] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> [RUN_GRADLEW]    > More than one file was found with OS independent path 'lib/x86/libfbjni.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
> ```
> 
> Here's a [patch-package](https://www.npmjs.com/package/patch-package) patch to fix the issue

I'm getting the same error. Using Expo 42 (which uses RN 0.63) with Hermes enabled. Smashed my head against the wall for a while since the error wasn't really pointing on reanimated in any way. My current workaround is downgrading to 2.2.0.

**Comment by MEsteves22** [comment]
I am currently using react-native version 0.64.2 and I am currently having the same problem. I downgraded to version 2.2.0 of react-native-reanimated to be able to build my App.

**Comment by choubeyaakash77** [comment]
I'm getting the same error on 0.62.0
My app is hybrid and the packageOptions solution will definitely increase the apk size, so I would not like to go with that.
I am getting an error on iOS as well when trying to use reanimated.

Rolling back to 2.2.0 fixes everything.

**Comment by Gabogg07** [comment]
I am currently working on "0.63.2" and using 2.2.0 or even keeping the previous used version till friday (2.0.0-alpha.5) is still giving us problems. Either the same debug problem or this new one
`
A problem occurred evaluating project ':react-native-reanimated'.
>......./node_modules/react-native-reanimated/android/../../react-native/package.json (No such file or directory)

`

**Comment by akenger** [comment]
We are having the same problem and also rolled back to 2.2.0.  We're in a 0.63.4 react-native app that is due for upgrade but hasn't yet been upgraded.

**Comment by KingAmo** [comment]
android build failed :
```
More than one file was found with OS independent path 'lib/x86/libfbjni.so'
```

**Comment by tijs** [comment]
Same basic issue, none of the above suggestions resolve it except downgrading to 2.2.0

```
Build file 'node_modules/react-native-reanimated/android/build.gradle' line: 76

A problem occurred evaluating project ':react-native-reanimated'.
> Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':react-native-reanimated'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
....etc
```

we already had the packagingOptions in our app/build.gradle. this is RN 0.63.4 manually upgraded with upgrade helper throughout the years (so if we missed some new gradle task I would love to know 😁)

**Comment by Yonom** [comment]
`v2.2.2` fixed the issue for us

**Comment by tijs** [comment]
still have it with 2.2.2 I'm afraid. I tried both 😞 we don't use expo which that fix seemed to be targeted at?

**Comment by samaneh-kamalian** [comment]
> > I'm on 64.2 and having the same issue. I rolled back to 2.2.0, which is working fine.
> 
> I use react-native 63.4 and react-native-reanimated 2.2.0 , but it does not build and gives such an error:
> 
> ```
> A problem occurred evaluating project ':react-native-reanimated'.
> Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.
> ```

I already sent the problem I had.
I do not have this problem on my system but I have this problem on gitlab runner. And I do not know why. This is while previously this project was built correctly with the same version of react-native-reanimated and had no problems. We made this error without changing the versions !!!
Does anyone come up with a solution?

**Comment by sperardt** [comment]
I am getting the same error. I am on react-native-reanimated: 1.13.3 and react-native: 0.63.4.

What are the chances that this error is not being generated by react-native-reanimated? Looking at the above comments, I have the oldest version of it and getting the same error than recent versions... What else has changed lately for android that could be causing this issue for all of us?

**Comment by tijs** [comment]
> What else has changed lately for android that could be causing this issue for all of us?

Were on gradle 7+ a quite recent release. Maybe that could make a difference.

**Comment by bitcrumb** [comment]
@tijs I am having the same failure as the author of this issue (even on 2.2.2).

I'm seeing this in the logs on our CI/CD: `Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.`

Does this point to an issue in react-native-reanimated or could this have to do with out own project (which does noet yet use Gradle 7).

**Comment by samaneh-kamalian** [comment]
> > > I'm on 64.2 and having the same issue. I rolled back to 2.2.0, which is working fine.
> > 
> > 
> > I use react-native 63.4 and react-native-reanimated 2.2.0 , but it does not build and gives such an error:
> > ```
> > A problem occurred evaluating project ':react-native-reanimated'.
> > Task with path ':app:mergeDebugNativeLibs' not found in project ':app'.
> > ```
> 
> I already sent the problem I had.
> I do not have this problem on my system but I have this problem on gitlab runner. And I do not know why. This is while previously this project was built correctly with the same version of react-native-reanimated and had no problems. We made this error without changing the versions !!!
> Does anyone come up with a solution?

I downgrade react-native-reanimated to 1.13.0 and the problem on pipeline is solved!!! but I dont know why!

**Comment by anjit6** [comment]
Downgrading to react-native-reanimated version to 2.1.0 (from 2.2.0) worked for me. I'm using react-native 0.64.2 (without expo). Some people mentioned downgrading to 2.2.0 worked for them, but it didn't for me.

**Comment by saadnaveed94** [comment]
Having the same issue with "react-native-reanimated": "^2.3.0-beta.2" and   "react-native": "0.62.2". any uopdates

**Comment by bekazandukeli** [comment]
> The temporary solution is to replace reanimated/build.gradle with this https://raw.githubusercontent.com/software-mansion/react-native-reanimated/2.2.0/android-npm/build.gradle

It worked for me with "react-native-reanimated": "^2.3.0-beta.2".

**Comment by wbercx** [comment]
I ran into this when wanting to create a new production release.

I produce Android App Bundles for the Play Store, not APKs. The task for that `bundleProductionRelease` for me, but `bundle` isn't matched against by the new `build.gradle` file of `react-native-reanimated`.

To fix that:
```diff
diff --git a/node_modules/react-native-reanimated/android/build.gradle b/node_modules/react-native-reanimated/android/build.gradle
index 18ee54a..a3f6fb7 100644
--- a/node_modules/react-native-reanimated/android/build.gradle
+++ b/node_modules/react-native-reanimated/android/build.gradle
@@ -31,7 +31,7 @@ abstract class replaceSoTask extends DefaultTask {
 def getCurrentFlavor() {
     Gradle gradle = getGradle()
     String taskRequestName = gradle.getStartParameter().getTaskRequests().toString()
-    Pattern pattern = Pattern.compile("(assemble|install|generate)(\\w+)(Release|Debug)")
+    Pattern pattern = Pattern.compile("(assemble|install|bundle|generate)(\\w+)(Release|Debug)")
     Matcher matcher = pattern.matcher(taskRequestName)
 
     if(matcher.find()) {
```

I can now produce the bundle I need, which is good. 

**However, every other Gradle command is broken, e.g. `gradlew clean`.**

Every time I need to do a `clean` I have to first delete `react-native-reanimated` from my node_modules so the above script does not run.

**Comment by jtoce** [comment]
Thanks for all of the hints. I've submitted a detailed pull request with a fix for this issue:
https://github.com/software-mansion/react-native-reanimated/pull/2564

**Comment by sperardt** [comment]
@thomazcapra the only thing that worked for me (after a couple of months) was: I created a brand new react-native project , ran it to see if it had any build issue. When it was working perfectly, I replaced the android folder in my old project. Before you do that, make sure you have committed your old project files to a git repository, based on the diff check what you actually need on the android folder, and try to run the project again. 

Hope that works!

**Comment by aprilmintacpineda** [comment]
This is already working for me, I'm using react-native-reanimated v2.4.1 and react-native 0.67.4 in my bare react-native app.

**Comment by joaorr3** [comment]
Let's hope this gets fixed soon. In the meantime, if you're desperate you could apply this patch and wait for an update. Make sure you don't have any gradle flavors. (you probably don't) 

I'm on v0.64.2, btw.

<details><summary>react-native-reanimated+2.3.3.patch</summary>

<p>

```patch
diff --git a/node_modules/react-native-reanimated/android/build.gradle b/node_modules/react-native-reanimated/android/build.gradle
index 794d95b..fcb8cc6 100644
--- a/node_modules/react-native-reanimated/android/build.gradle
+++ b/node_modules/react-native-reanimated/android/build.gradle
@@ -28,28 +28,6 @@ abstract class replaceSoTask extends DefaultTask {
     }
 }
 
-def getCurrentFlavor() {
-    Gradle gradle = getGradle()
-    String taskRequestName = gradle.getStartParameter().getTaskRequests().toString()
-    Pattern pattern = Pattern.compile("(assemble|bundle|install|generate)(\\w*)(Release|Debug)")
-    Matcher matcher = pattern.matcher(taskRequestName)
-
-    if(matcher.find()) {
-        return matcher.group(2)
-    }
-
-    return "NOT-FOUND"
-}
-
-def replaceSoTaskDebug
-def replaceSoTaskRelease
-if(Integer.parseInt(minor) < 65) {
-    tasks.register("replaceSoTaskDebug", replaceSoTask)
-    tasks.register("replaceSoTaskRelease", replaceSoTask)
-    replaceSoTaskDebug = project.getTasks().getByPath(":react-native-reanimated:replaceSoTaskDebug")
-    replaceSoTaskRelease = project.getTasks().getByPath(":react-native-reanimated:replaceSoTaskRelease")
-}
-
 rootProject.getSubprojects().forEach({project ->
     if (project.plugins.hasPlugin("com.android.application")) {
         if(project.ext.react.enableHermes) {
@@ -58,26 +36,11 @@ rootProject.getSubprojects().forEach({project ->
 
         if(project.getProperties().get("android") && Integer.parseInt(minor) < 65) {
             def projectProperties = project.getProperties()
-            final NOTFOUND = "NOT-FOUND"
-            if(!NOTFOUND.equals(getCurrentFlavor()) && (!projectProperties.get("reanimated")
-                    || (projectProperties.get("reanimated") && projectProperties.get("reanimated").get("enablePackagingOptions")))
-            ) {
-                def flavorString = getCurrentFlavor()
+            if(projectProperties.get("reanimated") && projectProperties.get("reanimated").get("enablePackagingOptions")) {
                 replaceSoTask.appName = project.getProperties().path
                 replaceSoTask.buildDir = project.getProperties().buildDir
                 def appName = project.getProperties().path
-
-                replaceSoTaskDebug.dependsOn(
-                        project.getTasks().getByPath("${appName}:merge${flavorString}DebugNativeLibs"),
-                        project.getTasks().getByPath("${appName}:strip${flavorString}DebugDebugSymbols")
-                )
-                project.getTasks().getByPath("${appName}:package${flavorString}Debug").dependsOn(replaceSoTaskDebug)
-
-                replaceSoTaskRelease.dependsOn(
-                        project.getTasks().getByPath("${appName}:merge${flavorString}ReleaseNativeLibs"),
-                        project.getTasks().getByPath("${appName}:strip${flavorString}ReleaseDebugSymbols")
-                )
-                project.getTasks().getByPath("${appName}:package${flavorString}Release").dependsOn(replaceSoTaskRelease)
+                project.getTasks().getByPath("${appName}:packageRelease")
             }
         }
     }

```

</p>
</details>

**Comment by TomasSestak** [comment]
Still happening in > 2.3.2 and react native 0.64.3
