### ISSUE TITLE
App Crash (v2.3.0-beta.1) FATAL EXCEPTION: main 

### ISSUE THREAD

**Issue by SohaibKtb** [software-mansion/react-native-reanimated#2518]
I tested the app on debug mode and everything is working well, but when I build the app with --variant=release mode, it crashed on opening the app, I debugged it on android studio and I got this exception:

```
2021-10-10 21:42:56.089 13715-13715/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 13715
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
        at com.swmansion.reanimated.layoutReanimation.g.r(Unknown Source:219)
        at com.facebook.react.uimanager.y0$m.b(Unknown Source:14)
        at com.facebook.react.uimanager.y0$a.run(Unknown Source:135)
        at com.facebook.react.uimanager.y0.U(Unknown Source:53)
        at com.facebook.react.uimanager.y0.s(Unknown Source:0)
        at com.facebook.react.uimanager.y0$j.c(Unknown Source:31)
        at com.facebook.react.uimanager.f.a(Unknown Source:0)
        at com.facebook.react.modules.core.g$d.a(Unknown Source:46)
        at com.facebook.react.modules.core.a$a$a.doFrame(Unknown Source:2)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

- React Native: 0.65.1
- React Native Reanimated: 2.3.0-beta.1 ---&--- 2.3.0-beta.2
- NodeJS: 15.14.0
- Xcode: 13
- Java & Gradle: open-jdk 1.8.0_275 ---&--- gradle-6.9-all

- [✅ ] Android

Thanks!

**Comment by robertying** [comment]
If you are using any minify tool like R8, try add an entry to `proguard-rules.pro`

```
-keep class com.swmansion.reanimated.** { *; }
```

**Comment by piaskowyk** [comment]
You should use @robertying 's solution and add the pro guard rule. Related PR: https://github.com/software-mansion/react-native-reanimated/pull/2803
