### ISSUE TITLE
java.lang.RuntimeException: Exception in HostFunction: Javascript worklet error

### ISSUE THREAD

**Issue by matteodisabatino** [software-mansion/react-native-reanimated#2527]
## Description

After opening a modal and turning back to the main Screen, the app freezes; at the this point the only thing you can do is to close the app. Then, if you try to open the app again, it never starts and after the splash screen it closes automatically.

This problem affects only Android and only on physical device (on simulator it works well).

After launch the command `adb logcat "AndroidRuntime:E *:S"`, I've found this error:

```
10-12 10:33:32.795  8256  8256 E AndroidRuntime: FATAL EXCEPTION: main
10-12 10:33:32.795  8256  8256 E AndroidRuntime: Process: com.my.app, PID: 8256
10-12 10:33:32.795  8256  8256 E AndroidRuntime: java.lang.RuntimeException: Exception in HostFunction: Javascript worklet error
10-12 10:33:32.795  8256  8256 E AndroidRuntime:
10-12 10:33:32.795  8256  8256 E AndroidRuntime: Error: Javascript worklet error
10-12 10:33:32.795  8256  8256 E AndroidRuntime:     at _f (native)
10-12 10:33:32.795  8256  8256 E AndroidRuntime:     at frame (/Users/matteodisabatino/my-app/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (183:0):1:1164)
10-12 10:33:32.795  8256  8256 E AndroidRuntime:
10-12 10:33:32.795  8256  8256 E AndroidRuntime: Error: Exception in HostFunction: Javascript worklet error
10-12 10:33:32.795  8256  8256 E AndroidRuntime:
10-12 10:33:32.795  8256  8256 E AndroidRuntime: Error: Javascript worklet error
10-12 10:33:32.795  8256  8256 E AndroidRuntime:     at _f (native)
10-12 10:33:32.795  8256  8256 E AndroidRuntime:     at frame (/Users/matteodisabatino/my-app/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (183:0):1:1164)
10-12 10:33:32.795  8256  8256 E AndroidRuntime:     at _f (native)
10-12 10:33:32.795  8256  8256 E AndroidRuntime:     at frame (/Users/matteodisabatino/my-app/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedStyle.ts (183:0):1:1164)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at com.swmansion.reanimated.AndroidErrorHandler.raise(AndroidErrorHandler.java:6)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:23)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:41)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
10-12 10:33:32.795  8256  8256 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

### Expected behavior

The app doesn't close.

### Actual behavior & steps to reproduce

As explained in "Description"

## Package versions

- React Native: 0.66.0
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: 14.18.0
- Java & Gradle: 11.0.12 & 6.9

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by wjaykim** [comment]
I have same issues with following code:
```js
const AnimatedGradient = Animated.createAnimatedComponent(LinearGradient);

const WelcomeScreen = () => {
  const navigation = useNavigation<RootNavigationProp<'Welcome'>>();
  const color = useSharedValue(0);
  const gradientProps = useAnimatedProps(() => ({
    colors: [
      interpolateColor(color.value, [0, 1], [colorLocaStart, colorLocaEnd]),
      interpolateColor(color.value, [0, 1], [colorLocaEnd, colorLocaStart]),
    ],
  }));

  useEffect(() => {
    color.value = withRepeat(withTiming(1, { duration: 5000 }), -1, true);
  }, [color]);

  return (
    <AnimatedGradient
      colors={[]}
      animatedProps={gradientProps}
      style={styles.container}>
      <Animated.View style={styles.centerContainer} entering={FadeIn}>
        <Logo style={styles.logo} />
      </Animated.View>
      <Animated.View style={styles.buttonContainer} entering={FadeIn}>
        <TouchableOpacity
          onPress={() => navigation.navigate('SignUp')}
          style={styles.registerButton}>
          <Text style={styles.registerButtonText}>사용자 등록</Text>
        </TouchableOpacity>
        <TouchableOpacity
          onPress={() => navigation.navigate('SignIn')}
          style={styles.signInButton}>
          <Text style={styles.signInButtonText}>로그인</Text>
        </TouchableOpacity>
      </Animated.View>
    </AnimatedGradient>
  );
};
```

**Comment by wjaykim** [comment]
I guess this issue is all about animating color. When I removed animations related to color, the error does not come out.

**Comment by piaskowyk** [comment]
Hey, 
I resolved this problem. It is because you missed adding custom props `color` to permitted UI props.
You should do something like this:
```js
import React, {useEffect} from 'react';
import Animated, {
  useSharedValue,
  withTiming,
  interpolateColor,
  useAnimatedProps,
  withRepeat,
} from 'react-native-reanimated';
import LinearGradient from 'react-native-linear-gradient';

Animated.addWhitelistedUIProps({colors: true}); // <-- important line

const AnimatedGradient = Animated.createAnimatedComponent(LinearGradient);
const styles = {
  container: {
    width: 400,
    height: 740,
  }
};

const WelcomeScreen = () => {
  const color = useSharedValue(0);
  const gradientProps = useAnimatedProps(() => {
    return {
      colors: [
        interpolateColor(color.value, [0, 1], ['#4c669f', '#ffffff']),
        interpolateColor(color.value, [0, 1], ['#ffffff', '#4c669f']),
      ]
    }
  });

  useEffect(() => {
    color.value = withRepeat(withTiming(1), 2, true);
  });

  return (
    <AnimatedGradient
      colors={[]}
      animatedProps={gradientProps}
      style={[styles.container]}
    />
  );
};

export default WelcomeScreen;
```

but unfortunately, LinearGradient isn't animable, because is wrapped by View and this view doesn't pass animated style to his child (NativeLinearGradient).
current:

https://user-images.githubusercontent.com/36106620/146605504-d4e534af-191a-4d49-b2c3-46686ba7e7e2.mov

after mu changes:

https://user-images.githubusercontent.com/36106620/146605531-3bd65c1f-d525-473f-be01-0700cdf66294.mov

**Comment by Noitidart** [comment]
How about for the code from the first user which doesn't use gradient? I'm also having this crash but I don't use gradient, not sure where it's coming from.

**Comment by hossam1231** [comment]
me too
