### ISSUE TITLE
[Android/2.3.0-beta.2]: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()'

### ISSUE THREAD

**Issue by danieldaleva** [software-mansion/react-native-reanimated#2541]
## Description

After launching in  Android emulator  (Android 11,  API 30). 
When loading the home screen (react-native-screens 3.4.0 or 3.8.0)

```
2021-10-14 17:54:46.205 15918-15918/com.xxx.yyy E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.swmansion.reanimated.layoutReanimation.AnimationsManager.onViewCreate(AnimationsManager.java:122)
        at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.applyLayoutUpdate(ReanimatedNativeHierarchyManager.java:78)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:252)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:225)
        at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.updateLayout(ReanimatedNativeHierarchyManager.java:170)
        at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:169)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.do
![Screen Shot 2021-10-14 at 18 48 00](https://user-images.githubusercontent.com/12353963/137400260-06d61e68-1f37-41d3-b760-92abd3163338.png)
Frame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Expected behavior

To Load the view after splash screen. But returns the error: **Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference**.

### Actual behavior & steps to reproduce

```sh  
npx react-native init App --template react-native-template-typescript

yarn add typescript@4.0.8 react-native-screens@3.4.0  react-native-reanimated@2.3.0-beta.2
```

## Package versions

    ....
    "react": "17.0.2",
    "react-native": "0.66.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.3.0-beta.2",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.4.0",
    "react-native-svg": "12.1.1",
    "react-native-unimodules": "^0.14.8",
    "react-native-web": "^0.17.5",
    ...

- React Native: 0.66
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: v14.17.4
- Xcode: Version 13.0 (13A233)
- Java & Gradle: openjdk version "1.8.0_292" & 4.4.2

## Affected platforms

- [X] Android
- [ ] iOS <--- Works fine
- [ ] Web <--- didn't try

**Comment by JeyongOh-MAASASIA** [comment]
Follow the installation instruction.
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation
