### ISSUE TITLE
[react-native 0.66.1] Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by nguyenthanhsonbs** [software-mansion/react-native-reanimated#2560]
Hi everyone, i got this bug
## description
`
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
        at com.swmansion.reanimated.layoutReanimation.AnimationsManager.onViewRemoval(AnimationsManager.java:101)
        at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.deleteView(ReanimatedNativeHierarchyManager.java:100)
`
## actual behavior
crash

## Package versions

- React Native: 0.66.1
- React Native Reanimated: 2.3.0-beta.2
- NodeJS: v16.6.1
- Xcode:
- Java & Gradle:

## Affected platforms

-  Android

**Comment by piaskowyk** [comment]
Probably fixed with this - https://github.com/software-mansion/react-native-reanimated/pull/2588

**Comment by piaskowyk** [comment]
Could you provide an example repo to reproduce your issue?

**Comment by piaskowyk** [comment]
Unfortunately, I am closing this issue because I can't reproduce it. If someone prepares a repo with reproduction of this issue post it here and we will reopen the issue.
It should be fixed by #2588
