### ISSUE TITLE
Failing to import Transitions in Android

### ISSUE THREAD

**Issue by MorganTrudeau** [software-mansion/react-native-reanimated#2577]
## Description

I have installed react-native-reanimated v2 and I am experiencing a crash now. This crash is related to react-navigation-animated-switch. They are using Transition component to animate navigation transitions. Looks like these transition files cannot be located on Android.

If I disable the animated switch navigator and use the basic `createSwitchNavigator` from react-navigation it works.

This is the crash from adb logcat.
```
10-25 21:58:46.705 21420 21420 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/transition/TransitionSet;
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.swmansion.reanimated.transitions.TransitionUtils.inflateGroup(TransitionUtils.java:40)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.swmansion.reanimated.transitions.TransitionUtils.inflate(TransitionUtils.java:28)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.swmansion.reanimated.transitions.TransitionModule$1.execute(TransitionModule.java:33)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:571)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1088)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1254)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:995)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at android.view.Choreographer.lambda$new$0$Choreographer(Choreographer.java:233)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at android.view.-$$Lambda$Choreographer$zXV0PrqwmpdPajenUBozqc6c8Hs.run(Unknown Source:2)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8393)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
10-25 21:58:46.705 21420 21420 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.transition.TransitionSet" on path: DexPathList[[zip file "/data/app/com.morgantrudeau.employeelink_dev-XYGfIDj-m_hYPxQimf224g==/base.apk"],nativeLibraryDirectories=[/data/app/com.morgantrudeau.employeelink_dev-XYGfIDj-m_hYPxQimf224g==/lib/arm64, /data/app/com.morgantrudeau.employeelink_dev-XYGfIDj-m_hYPxQimf224g==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
```

### Expected behavior
Files should be imported and no crash should occur

### Actual behavior & steps to reproduce
Crashes attempting to import Transition

## Snack or minimal code example

Checkout this repo where I made a simple reproduction with all latest libraries. https://github.com/MorganTrudeau/reanimated_test

This is how I am using the Transition component

```
import createAnimatedSwitchNavigator from 'react-navigation-animated-switch';
import { Transition } from 'react-native-reanimated';

...

 const switchNavigator = createAnimatedSwitchNavigator(
      {
        SplashScreen,
        AuthScreens,
        NewUserScreens,
        EmployerScreens,
        EmployeeScreens,
        SubscriptionScreens,
        EmailVerificationScreens,
      },
      {
        initialRouteName,
        headerMode: 'screen',
        transition: (
          <Transition.Together>
            <Transition.Out
              type={'fade'}
              durationMs={260}
              interpolation='easeOut'
            />
            <Transition.In
              type={'fade'}
              durationMs={260}
              interpolation='easeOut'
            />
          </Transition.Together>
        ),
      },
    );
```

## Package versions

"react-native-reanimated": "^2.2.3", // I have tried with 2.0.0, 2.2.0, and 2.3.x alpha
"react-native": "0.63.4",
"react": "16.13.1",
"react-navigation-animated-switch": "^0.6.4",

*Android versions*
buildToolsVersion = "29.0.3"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29
supportLibVersion = "28.0.0"

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by SanderRonde** [comment]
We just encountered this bug and managed to fix it by adding `implementation "androidx.transition:transition:1.4.1"` to the `dependencies` section of our `build.gradle`. Maybe this works for you as well.

**Comment by piaskowyk** [comment]
Unfortunately, we no longer support reanimated v1. Please try the above @SanderRonde 's solution.
