### ISSUE TITLE
[Web] Captured null values in useAnimatedStyle causes extractMutables crash

### ISSUE THREAD

**Issue by brianreavis** [software-mansion/react-native-reanimated#2628]
## Description

Referencing `null` variables in `useAnimatedStyle` worklets causes a crash in [`extractMutables`](https://github.com/software-mansion/react-native-reanimated/blob/0fc7a32037b26aff61455678a515721f71f6a243/src/reanimated2/js-reanimated/Mapper.ts#L50) when the mapper is created ([see snack](https://snack.expo.dev/@brianreavis/null-extractmutables-crash)).

### Expected behavior

No crash

### Actual behavior & steps to reproduce

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at e (react-native-reanimated.js:12:149367)
    at eval (react-native-reanimated.js:12:149332)
    at Array.forEach (<anonymous>)
    at e (react-native-reanimated.js:12:149304)
    at e.value (react-native-reanimated.js:12:149407)
    at new e (react-native-reanimated.js:12:148894)
    at e.value (react-native-reanimated.js:12:146322)
    at t.startMapper (react-native-reanimated.js:3:15002)
    at eval (react-native-reanimated.js:12:194835)
```

## Snack or minimal code example

```js
const someValue = null;
const style = useAnimatedStyle(() => {
    return { opacity: someValue ? 1 : 0 };
});
```

**https://snack.expo.dev/@brianreavis/null-extractmutables-crash**

## Package versions

2.2.4

## Affected platforms

- [ ] Android
- [ ] iOS
- [x] Web

**Comment by brianreavis** [comment]
Duplicate of: https://github.com/software-mansion/react-native-reanimated/issues/2589

**Comment by piaskowyk** [comment]
Like above, this is duplicated issue and we will fix it soon 🚀 Thanks for the report!
