### ISSUE TITLE
Could not load needed library 'libhermes.so' for 'libreanimated.so'

### ISSUE THREAD

**Issue by CyxouD** [software-mansion/react-native-reanimated#2638]
## Description

I've expected crash could not load needed library 'libhermes.so' for 'libreanimated.so' after installing react-native-reanimated@2.2.4 with Android API 16:

```
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    java.lang.ExceptionInInitializerError
        at com.swmansion.reanimated.NodesManager.initWithContext(NodesManager.java:127)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:18)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1256)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1891]:  1172 could not load needed library 'libhermes.so' for 'libreanimated.so' (load_library[1093]: Library 'libhermes.so' not found)
        at java.lang.Runtime.loadLibrary(Runtime.java:370)
        at java.lang.System.loadLibrary(System.java:535)
        at com.swmansion.reanimated.NativeProxy.<clinit>(NativeProxy.java:22)
        at com.swmansion.reanimated.NodesManager.initWithContext(NodesManager.java:127) 
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:18) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1256) 
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016) 
        at java.lang.Thread.run(Thread.java:856) 
```

### Expected behavior

The app runs and doesn't crash

### Actual behavior & steps to reproduce

Steps to reproduce the behaviour:

1. Create react-native project with npx react-native init AwesomeProject --template react-native-template-typescript@6.5.13
2. Follow the guide to add react-native-reanimated@2.2.4
3. Clean a build after enabling Hermes during the last step (to be sure that it isn't because of this)
4. Build an app with Nexus S Android device API 16
5. See a crash in your Android Studio console

## Snack or minimal code example

No special code is needed, just steps to reproduce

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.2.4
- Java & Gradle: Java – 1.8.0_292, Gradle - 6.2

## Affected platforms

- Android API 16

## Note
When I do the same steps with device Pixel 2 API 29 everything is OK, no crash. Also, API 16 device doesn't crash if just enable Hermes without adding react-native-ui-lib

**Comment by kmagiera** [comment]
Hi @CyxouD – thanks for reporting this. Since the repro steps aren't using the most recent version can you confirm it does happen as well on the most recent version? Given reanimated works for a lot of people and that we also test each release on a number of repos it is hard for me to believe that creating a fresh project and installing reanimated does not work and suspect this has to do with your build environment maybe?

Can you please confirm if these steps also cause the app to crash on 2.3.1 version of reanimated?

**Comment by gelodgreat** [comment]
Up with this issue, When hermes is enabled I also got this issue. This is 2.3.1 @kmagiera
