### ISSUE TITLE
Runtime crash: JSON object value was a NaN when serializing value at "focalX"

### ISSUE THREAD

**Issue by vtoupet** [software-mansion/react-native-reanimated#2662]
## Description
 The following crash occurs sporadically in production build.

```
java.lang.RuntimeException: folly::toJson: JSON object value was a NaN when serializing value at "focalX"
    at com.facebook.react.bridge.NativeMap.toString(NativeMap.java)
    at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java)
    at com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(NativeProxy.java:55)
    at com.swmansion.gesturehandler.react.RNGestureHandlerStateChangeEvent.dispatch(RNGestureHandlerStateChangeEvent.java:80)
    at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:485)
    at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:462)
    at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
    at com.swmansion.gesturehandler.react.RNGestureHandlerModule.onStateChange(RNGestureHandlerModule.java:691)
    at com.swmansion.gesturehandler.react.RNGestureHandlerModule.access$300(RNGestureHandlerModule.java:42)
    at com.swmansion.gesturehandler.react.RNGestureHandlerModule$1.onStateChange(RNGestureHandlerModule.java:436)
    at com.swmansion.gesturehandler.GestureHandler.dispatchStateChange(GestureHandler.java:81)
    at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onHandlerStateChange(GestureHandlerOrchestrator.java:200)
    at com.swmansion.gesturehandler.GestureHandler.moveToState(GestureHandler.java:350)
    at com.swmansion.gesturehandler.GestureHandler.cancel(GestureHandler.java:444)
    at com.swmansion.gesturehandler.GestureHandlerOrchestrator.makeActive(GestureHandlerOrchestrator.java:223)
    at com.swmansion.gesturehandler.GestureHandlerOrchestrator.tryActivate(GestureHandlerOrchestrator.java:159)
    at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onHandlerStateChange(GestureHandlerOrchestrator.java:194)
    at com.swmansion.gesturehandler.GestureHandler.moveToState(GestureHandler.java:350)
    at com.swmansion.gesturehandler.GestureHandler.activate(GestureHandler.java:456)
    at com.swmansion.gesturehandler.NativeViewGestureHandler.onHandle(NativeViewGestureHandler.java:87)
    at com.swmansion.gesturehandler.GestureHandler.handle(GestureHandler.java:329)
    at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandler(GestureHandlerOrchestrator.java:301)
    at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandlers(GestureHandlerOrchestrator.java:259)
    at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.java:101)
    at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.java:126)
    at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent(RNGestureHandlerEnabledRootView.java:36)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
    at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
    at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
    at android.view.View.dispatchPointerEvent(View.java:15458)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
    at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
    at android.os.MessageQueue.next(MessageQueue.java:335)
    at android.os.Looper.loop(Looper.java:206)
    at android.app.ActivityThread.main(ActivityThread.java:8633)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Expected behavior

It should not crash.

### Actual behavior & steps to reproduce

- upgrade react-native-reanimated: from 1.13.2 to 2.2.4 in project
- update

Modify references in the code from (reanimated v1)
```
  const translateX = Animated.interpolate(progress, {
    inputRange: [0, 0.5, 0.7, 0.8, 1],
    outputRange: [-100, -85, -70, -45, 0],
  });
```
to (reanimated v2)

```
  const translateX = Animated.interpolateNode(
    progress as Animated.Adaptable<number>,
    {
      inputRange: [0, 0.5, 0.7, 0.8, 1],
      outputRange: [-100, -85, -70, -45, 0],
    },
  );
```

and from

```tsx
React.useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 1000,
      easing: Easing.inOut(Easing.ease),
    }).start();
  }, [fadeAnim]);
```
to

```tsx
React.useEffect(() => {
    Animated.timing(fadeAnim, {
      toValue: 1,
      duration: 1000,
      easing: EasingNode.inOut(EasingNode.ease),
    }).start();
  }, [fadeAnim]);
```

Those are the only 2 references of react-native-reanimated in my app

## Package versions

- React Native: 0.66.3
- React Native Reanimated: 2.2.4
- NodeJS: v16.11.1
- Xcode: 13.1
- Java & Gradle: java 15.0.2 2021-01-19 and gradle 6.9

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by vtoupet** [comment]
until now it occurred only on Android 11 devices

**Comment by kamui545** [comment]
I also have this issue with a similar stack trace, but I was only able to reproduce it once on my device.
It seems to be really random...

Sentry reported this issue on Android 9, 10 and 11.

**Comment by vtoupet** [comment]
@piaskowyk Why have you changed tag to reanimated v1? The problem showed up when upgrading the project to reanimated v2.

**Comment by piaskowyk** [comment]
Hey, you shouldn't use `Animated.timing`, in reanimated v2 we have `withTiming`, Look at this example - https://github.com/software-mansion/react-native-reanimated/blob/main/Example/src/AnimatedStyleUpdateExample.tsx#L20 Could you check if it resolves your problem?

**Comment by kamui545** [comment]
Hi @piaskowyk, thank you for your reply.

Sadly, on my app, [the only library using Reanimated](https://github.com/Flair-Dev/react-native-awesome-gallery/blob/main/src/index.tsx) does use `withTiming` and I am encountering this error, it might not be related (at least for me).

I'm still investigating but not being able to reproduce it is very troublesome.

**Comment by michaelknoch** [comment]
`folly::toJson: JSON object value was a NaN when serializing value at "velocity"->"y"` keeps happening for our users. It seems that it directly happens after an orientation switch has happened and the viewport gets recreated with new dimensions. I'm wondering if this is more a problem with [react-native-gesture-handler ](https://github.com/software-mansion/react-native-gesture-handler). 

Would it make sense to ignore events with which contain `NaN` values? I'd prefer that over crashing the entire app, but this might be specific to us. @piaskowyk

**Comment by tomekzaw** [comment]
Looks similar to #1776.

**Comment by michaelknoch** [comment]
I came up with a fix for the gesture handler library to prevent NaN values in first place. Let's see what they say about it.
https://github.com/software-mansion/react-native-gesture-handler/pull/1853

**Comment by michaelknoch** [comment]
I also have a working version which "ignores" NaN values in the `receiveEvent` function. As I said before this would be more fighting symptoms rather than really fixing the underlying problem. But maybe still interesting for you guys @tomekzaw 

https://github.com/michaelknoch/react-native-reanimated/commit/995e2e71cebe0d3045122efe743595a3ef0e3c1c

**Comment by tomekzaw** [comment]
@michaelknoch There are many libraries out there that also use `NaN` in event values, e.g. react-native-video. That's why we decided to wrap JSON serialization within `try/catch` block to ensure compatibility with other libraries (see #2896).

**Comment by michaelknoch** [comment]
fair point about other libraries. The solution in the pr looks good, way better than what I did by replacing the NaNs with nulls in the java code. Happy to see it merged! thanks for your work @tomekzaw

**Comment by tomekzaw** [comment]
Fixed with #2901

**Comment by vtoupet** [comment]
> Fixed with #2901

That's great news! @tomekzaw do you have an idea when v2.4.0 will be released ?

I've followed the instructions to pick builds from master, but it fails to build :-(

**Comment by piaskowyk** [comment]
@vtoupet We release a new version today night or tomorrow morning 😀  (according to middle Europe time)

**Comment by hedia-m** [comment]
We are getting the same crash on 3.19.0, and we do have react-native-video. Is it a regression in reanimated V3 ? I don't see something related to the code added in [#2901](https://github.com/software-mansion/react-native-reanimated/pull/2901) in V3 source code

Only Android 10 and 11 are affected.

**Comment by Maroka745** [comment]
react-native-image-header-scroll-view
badge

A ScrollView-like component that:

Has a fixed image header
Keep the image as a nav bar
Works on iOS and Android
Breaking changes

Version 1.0.0

/!\ Warning /!\ The lib has been upgraded to match with new React and React Native standards (hooks, deprecated methods, etc...). The version 1.0.0 may contain some bugs or regressions. Ping me in issues if you notice a bad behaviour of the upgraded lib on your project. I advice you to update the lib in a separate commit to roll back if necessary. However the lib should work for most of cases, so don't be scared to update the lib. It is a first step to improve the lib in the future, so please be understanding 😇

Installation

$ npm install react-native-image-header-scroll-view --save
Demo

react-native-image-header-scroll-view demo android|react-native-image-header-scroll-view demo ios

You can find this example code here : https://github.com/bamlab/react-native-image-header-scroll-view-example/blob/master/src/Pages/TvShow.js

Basic Usage

import { ImageHeaderScrollView, TriggeringView } from 'react-native-image-header-scroll-view';

// Inside of a component's render() method:
render() {
  return (
    <ImageHeaderScrollView
      maxHeight={200}
      minHeight={MIN_HEIGHT}
      headerImage={require("../../assets/NZ.jpg")}
      renderForeground={() => (
        <View style={{ height: 150, justifyContent: "center", alignItems: "center" }} >
          <TouchableOpacity onPress={() => console.log("tap!!")}>
            <Text style={{ backgroundColor: "transparent" }}>Tap Me!</Text>
          </TouchableOpacity>
        </View>
      )}
    >
      <View style={{ height: 1000 }}>
        <TriggeringView onHide={() => console.log("text hidden")}>
          <Text>Scroll Me!</Text>
        </TriggeringView>
      </View>
    </ImageHeaderScrollView>
  );
}
Result :

Basic Usage

You can find examples in a dedicated repository.

Usage (API)

All of the properties of ScrollView are supported. Please refer to the ScrollView documentation for more detail.

The ImageHeaderScrollView handle also the following props. None is required :

Header

Property	Type	Default	 Description	Example
renderHeader	function	 Empty view	Function which return the component to use as header. It can return background image for example.	example
headerImage	Image source Props (object or number)	 undefined	Shortcut for renderHeader={() => <Image source={this.props.headerImage} style={{ height: this.props.maxHeight, width: Dimensions.get('window').width }} />}	example
maxHeight	number	125	Max height for the header	example
minHeight	number	80	Min height for the header (in navbar mode)	example
minOverlayOpacity	number	0	Opacity of a black overlay on the header before any scroll	example
maxOverlayOpacity	number	0.3	Opacity of a black overlay on the header when in navbar mode	example
overlayColor	string	black	Color of the overlay on the header	example
useNativeDriver	boolean	false	Use native driver for the animation for performance improvement. A few props are unsupported at the moment if useNativeDriver=true (onScroll, ScrollComponent, renderTouchableFixedForeground)	-
headerContainerStyle	Object	undefined	Optional styles to be passed to the container of the header component	
disableHeaderGrow	boolean	undefined	Disable to grow effect on the header	
Foreground

Property	Type	Default	 Description	Example
renderForeground	function	Empty view	Function which return the component to use at foreground. The component is render in front of the header and scroll with the ScrollView. It can return a title for example.	example
renderFixedForeground	function	Empty view	Function which return the component to use as fixed foreground. The component is displayed with the header but not affected by the overlay.	example
foregroundExtrapolate	string	clamp	Optional prop that allows override extrapolate mode for foreground. Use null to allow extrapolation, which is usefull for using foreground as bottom title	-
foregroundParallaxRatio	number	1	Ration for parallax effect of foreground when scrolling. If 2, the header goes up two times faster than the scroll	example
fadeOutForeground	bool	false	If set, add a fade out effect on the foreground when scroll up	example
renderTouchableFixedForeground	function	Empty view	Same as renderFixedForeground but allow to use touchable in it. Can cause performances issues on Android	example
fixedForegroundContainerStyles	Object	undefined	Optional styles to be passed to the container of the fixed foreground component	
Mixed

Property	Type	Default	 Description	Example
ScrollViewComponent	Component	 ScrollView	The component to be used for scrolling. Can be any component with an onScroll props (ie. ListView, FlatList, SectionList or ScrollView)	example
scrollViewBackgroundColor	string	 white	Background color of the scrollView content	example
TriggeringView

The module also export a TriggeringView component. It is a spy View you put on the page that will can call various callback during the scroll. It accept callback called when it disappear or appear at the top of the ImageHeaderScrollView. You can see an exemple in the dedicated repository.

All of the properties of View are supported.

Property	Type	Description
onBeginHidden	function	 Called when the component start to be hidden at the top of the scroll view.
onHide	function	 Called when the component is not displayed any more after scroll up
onBeginDisplayed	function	 Called when the component begin to be displayed again after scroll down
onDisplay	function	 Called when the component finished to be displayed again.
onTouchTop	function	 Called when the Top of the component touch the Top of the ScrollView. (onDisplay + onBeginHidden)
onTouchBottom	function	 Called when the Bottom of the component touch the Top of the ScrollView. (onHide + onBeginDisplayed)
FAQ

How to remove the black image overlay

Just set the maxOverlayOpacity to 0.

<ImageHeaderScrollView
  minOverlayOpacity={0}
  maxOverlayOpacity={0}
  {/* ... */}
/>
How to remove the image zomming on scroll down

You have two solutions :

You can use the disableHeaderGrow props. It will keep the ios elastic scroll effect.
You can also use the bounces={false} props from the scroll view.
Results :

disableHeaderGrow	bounces={false}
react-native-image-header-scroll-view demo disableHeaderGrow	react-native-image-header-scroll-view demo bounces
Contributing

All contributions are welcomed, that might be either adding new features, doing some refaco of the exisiting code or fixing bugs.

How to contribute

Fork the project & clone locally. Follow the initial setup here.
Create a branch, naming it either a feature or bug: git checkout -b feature/that-new-feature or bug/fixing-that-bug
Code and commit your changes. Write a good commit message. Best would be to use git commitizen
Test your changes in the example
launch the Expo project: cd example && yarn start && cd ..
compile typescript to lib folder : `yarn tsc --noEmit``
watch your feature/fix in your simulator
Push to the branch: git push origin feature/that-new-feature
Create a pull request for your branch 🎉
Other open-source modules by the folks at BAM

generator-rn-toolbox
react-native-image-resizer
react-native-numberpicker-dialog
react-native-animated-picker
