### ISSUE TITLE
Jest error "Cannot read property 'previousStyle' of undefined"

### ISSUE THREAD

**Issue by Andarius** [software-mansion/react-native-reanimated#2672]
## Description

Running tests with jest raises the following error

```bash
/my-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/index.web.js:33
  var previousStyle = component.previousStyle ? component.previousStyle : {};
                                ^

TypeError: Cannot read property 'previousStyle' of undefined
    at setNativeProps (/my-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/index.web.js:18:37)
    at updatePropsInternal (/my-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/index.web.js:14:9)
    at updateProps (/my-app/node_modules/react-native-reanimated/lib/reanimated2/UpdateProps.js:42:5)
    at updatePropsJestWrapper (/my-app/node_modules/react-native-reanimated/lib/reanimated2/UpdateProps.js:46:5)
    at jestStyleUpdater (/my-app/node_modules/react-native-reanimated/lib/reanimated2/Hooks.js:326:9)
    at Mapper.mapper (/my-app/node_modules/react-native-reanimated/lib/reanimated2/Hooks.js:364:17)
    at Mapper.execute (/my-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/Mapper.js:21:14)
    at MapperRegistry.execute (/my-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/MapperRegistry.js:27:24)
    at JSReanimated._onRender (/my-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js:38:30)
    at Timeout._onTimeout (/my-app/node_modules/react-native-reanimated/lib/reanimated2/js-reanimated/JSReanimated.js:33:22)
error Command failed with exit code 1.
```

### Expected behavior

Not to raise an error

### Actual behavior & steps to reproduce

Upgrade from 2.2.3 to 2.2.4

## Snack or minimal code example

Run test on a component with an animation.

## Package versions

- React Native: 0.66
- React Native Reanimated: 2.2.4

## Affected platforms

- [ ] Android
- [ ] iOS
- [ ] Web

**Comment by giovanijfc** [comment]
The same here, with `@testing-library/jest-native: 4.0.4` and `@testing-library/react-native: 8.0.0`

**Comment by Only-IceSoul** [comment]
same here with expo and react native web. Simple animation

**Comment by kkafar** [comment]
Since I can not reproduce it locally, can anyone with this bug provide minimal code sample (component + test)? 

However it seems to me that this problem is related to:

* https://github.com/software-mansion/react-native-reanimated/issues/2635

In that case problem should be resolved with release of 2.2.5. Give me a hint, if fixing this typo works for you.

**Comment by tiste** [comment]
Hello @kkafar! Do you know when the 2.2.5 could be released? I tried the fix with higher version and it works well, but I'm stuck with ~2.2.x with expo.
