### ISSUE TITLE
[Android] Crash on app launch, after upgrade to 2.3.0

### ISSUE THREAD

**Issue by alimek** [software-mansion/react-native-reanimated#2727]
## Description
My app once bootsplash is destroyed I am shoiwing some animation as 1st thing.
App is crashing just after opening only in release build on Android. iOS with version 2.3.0 is working fine.

Stack strace: 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.reanimated.layoutReanimation.f.j()' on a null object reference
        at com.swmansion.reanimated.layoutReanimation.g.r(ReanimatedNativeHierarchyManager.java:1)
        at com.facebook.react.uimanager.x0$m.c(UIViewOperationQueue.java:1)
        at com.facebook.react.uimanager.x0$a.run(UIViewOperationQueue.java:19)
        at com.facebook.react.uimanager.x0.U(UIViewOperationQueue.java:10)
        at com.facebook.react.uimanager.x0.s(UIViewOperationQueue.java:1)
        at com.facebook.react.uimanager.x0$j.c(UIViewOperationQueue.java:6)
        at com.facebook.react.uimanager.f.a(GuardedFrameCallback.java:1)
        at com.facebook.react.modules.core.g$d.a(ReactChoreographer.java:7)
        at com.facebook.react.modules.core.a$a$a.doFrame(ChoreographerCompat.java:1)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
        at android.view.Choreographer.doCallbacks(Choreographer.java:880)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7879)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Downgrading renimated to 2.2.4 works fine.

### Expected behavior

App should launch without crash.

## Package versions

- React Native: 0.66.3
- React Native Reanimated: 2.3.0
- NodeJS: 14.17.2
- React Native Gesture Handler: 1.10.3

## Affected platforms

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by ahmetbicer** [comment]
I was getting the same issue. I solved it by adding reanimated to proguard rules.

-keep class com.swmansion.reanimated.** { *; }

Link to the PR: https://github.com/software-mansion/react-native-reanimated/pull/2725/files

**Comment by kakajann** [comment]
@ahmetbicer that saved my day!

**Comment by alexco2** [comment]
@alimek did you have a look at https://github.com/software-mansion/react-native-reanimated/issues/2246?

**Comment by alimek** [comment]
> I was getting the same issue. I solved it by adding reanimated to proguard rules.
> 
> `-keep class com.swmansion.reanimated.** { *; }`
> 
> Link to the PR: #2725

this fixed issue for me, I can close issue i think, as there is PR already.

**Comment by priyankaEdufund** [comment]
> I was getting the same issue. I solved it by adding reanimated to proguard rules.
> 
> `-keep class com.swmansion.reanimated.** { *; }`
> 
> Link to the PR: #2725

Thanks buddy, saved my time :)

**Comment by mercpls** [comment]
> > I was getting the same issue. I solved it by adding reanimated to proguard rules.
> > `-keep class com.swmansion.reanimated.** { *; }`
> > Link to the PR: #2725
> 
> Thanks buddy, saved my time :)

Any response for someone not using proguard, but using crashlytics?
