### ISSUE TITLE
[2.3] Cannot find module `@babel/preset-typescript`

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-reanimated#2746]
## Description

I upgraded to `2.3`, and I am getting this super bizarre error. Downgrading to 2.2 fixes it. I've tried clearing my cache, rebuilding, etc. No luck.

It says `Cannot find module '@babel/preset-typescript'`. I'm in a TypeScript Expo project (in a monorepo). I'm using a custom dev client (meaning I can use native code,) and I'm trying to use 2.3.x.

### Expected behavior

The app should run normally after upgrading.

### Actual behavior & steps to reproduce

If you have no clue what it could be, I can try to repro tomorrow. Maybe it's an issue with Expo + TypeScript + Expo's babel config?

This is the error message I get:

<details>
<summary>
View iOS error
</summary>

```sh
../../packages/navigation/native-stack/use-options.tsx: /Users/user/Developer/madison-hacks/app/packages/navigation/native-stack/use-options.tsx: Cannot find module '@babel/preset-typescript'
Require stack:
- /Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/index.js
- /Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/index.js
- /Users/user/Developer/madison-hacks/app/node_modules/metro-transform-worker/src/index.js
- /Users/user/Developer/madison-hacks/app/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/user/Developer/madison-hacks/app/node_modules/jest-worker/build/workers/processChild.js
Error: /Users/user/Developer/madison-hacks/app/packages/navigation/native-stack/use-options.tsx: Cannot find module '@babel/preset-typescript'
Require stack:
- /Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/index.js
- /Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/index.js
- /Users/user/Developer/madison-hacks/app/node_modules/metro-transform-worker/src/index.js
- /Users/user/Developer/madison-hacks/app/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/user/Developer/madison-hacks/app/node_modules/jest-worker/build/workers/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolve (node:internal/modules/cjs/helpers:108:19)
    at resolveStandardizedName (/Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/plugins.js:102:7)
    at resolvePreset (/Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/plugins.js:50:10)
    at loadPreset (/Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/plugins.js:69:20)
    at loadPreset.next (<anonymous>)
    at createDescriptor (/Users/user/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/config-descriptors.js:179:16)
    at createDescriptor.next (<anonymous>)
    at evaluateSync (/Users/user/Developer/madison-hacks/app/node_modules/gensync/index.js:251:28)
```
</details>

<details>
<summary>
View Web (Next.js) error
</summary>

```sh
../../node_modules/react-native-reanimated/lib/createAnimatedComponent.js
Error: Cannot find module '@babel/preset-typescript'
Require stack:
- /Users/app/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/app/Developer/madison-hacks/app/node_modules/@babel/core/lib/config/files/index.js
- /Users/app/Developer/madison-hacks/app/node_modules/@babel/core/lib/index.js
- /Users/app/Developer/madison-hacks/app/node_modules/@babel/helper-create-class-features-plugin/lib/index.js
- /Users/app/Developer/madison-hacks/app/node_modules/@babel/plugin-proposal-private-methods/lib/index.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/config/files/index.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/node_modules/@babel/core/lib/index.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/webpack/loaders/createBabelLoader.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/webpack/loaders/createAllLoaders.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/webpack/loaders/index.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/webpack/addons/withUnimodules.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/webpack/addons/index.js
- /Users/app/Developer/madison-hacks/app/node_modules/@expo/webpack-config/addons/index.js
- /Users/app/Developer/madison-hacks/app/apps/next/node_modules/@expo/next-adapter/build/withExpo.js
- /Users/app/Developer/madison-hacks/app/apps/next/node_modules/@expo/next-adapter/build/index.js
- /Users/app/Developer/madison-hacks/app/apps/next/next.config.js
    at loadPreset.next (<anonymous>)
    at createDescriptor.next (<anonymous>)
```
</details>

## Snack or minimal code example

I don't have one for now, but can provide tomorrow if needed. Please let me know.

## Package versions

- React Native: 0.63.4
- React Native Reanimated: 2.3.0, 2.3.1 have the same issue
- NodeJS:
- Xcode:
- Java & Gradle:

## Affected platforms

- [ ] Android
- [x] iOS
- [x] Web

**Comment by alexco2** [comment]
Hello, I think I had the same issue and fixed it by `yarn add @babel/preset-typescript`

**Comment by nandorojo** [comment]
Hm got it, I’ll try that again. When I ran `yarn why` it showed that I already had it, but maybe I missed something.

**Comment by nandorojo** [comment]
Okay, that did fix it after all. Unfortunately, I'm facing a number of other issues with reanimated 2.3 not firing animations now. But at least I got past that bundle issue.

**Comment by alexco2** [comment]
Happy I was able to help.
The animation issue sounds similar to this bug: https://github.com/software-mansion/react-native-reanimated/issues/2735

**Comment by chungweileong94** [comment]
I personally don't think we should close this issue. 
Installing `@babel/preset-typescript` should be just a workaround, not an actual fix.

**Comment by juandl** [comment]
yes, please re-open the issue, adding packages like that is not a correct way to solve this issue @nandorojo

**Comment by karanmartian** [comment]
Any update on this issue. Me too facing this issue

**Comment by simon-abbott** [comment]
I just updated to react-native 0.66.4, and react-native-reanimated to 2.4.1, still getting this error. I can easily install the package manually, but I shouldn't have to.

**Comment by marciofaria-git** [comment]
Hi, i try put this in my .eslintrc.json

{
  "extends": ["next/babel","next/core-web-vitals"]
}

and in my .babelrc

"presets": [
      "next/babel",
      "@babel/preset-typescript"
    ]

My .eslintrc.json
```
{
  "extends": ["next/babel","next/core-web-vitals"]
}
```

My .babelrc

```
{
    "plugins": [
      [
        "babel-plugin-styled-components",
        
        {
          "ssr": true,
          "transpileTemplateLiterals":true,
          "minify":true,
          "pure":true
          
        }
        
      ] 
    ],
    "presets": [
      "next/babel",
      "@babel/preset-typescript"
    ]
  }
```
