### ISSUE TITLE
Android 5.1 (Huawei): java.lang.NullPointerException: Attempt to invoke virtual method isLayoutAnimationEnabled

### ISSUE THREAD

**Issue by tapz** [software-mansion/react-native-reanimated#2828]
## Description

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.isLayoutAnimationEnabled()' on a null object reference
    at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:266)
    at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:824)
    at android.view.Choreographer.doCallbacks(Choreographer.java:629)
    at android.view.Choreographer.doFrame(Choreographer.java:596)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:812)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5931)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

### Expected behavior

No crash

### Actual behavior & steps to reproduce

Crash

## Snack or minimal code example

https://github.com/tapz/reanimatederror-example/tree/master/android

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         | 0.66.4  |
| react-native-reanimated              | 2.3.1   |
| NodeJS                               | 14.18.1 |
| Xcode                                |         |
| Java                                 | openjdk 14.0.2+12-46 |
| Gradle                               | 7.3.3   |
| expo                                 |         |

## Affected platforms

Android 5.1
HUAWEI CUN-L21

- [X] Android
- [ ] iOS
- [ ] Web

**Comment by hernanmateo** [comment]
#2773

**Comment by tapz** [comment]
Closed this as duplicate.
