### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by shensven** [software-mansion/react-native-reanimated#2994]
## Description
After installed the `react-native-collapsible-tab-view` and wrote a minimal example, jest does not pass
see this commit https://github.com/shensven/Readhubn/commit/9b0877f890d9acf5542ec91964dc374307270f0c

```sh
yarn run v1.22.15
$ jest
 FAIL  __tests__/App-test.tsx (6.541 s)
  ✕ renders correctly (209 ms)

  ● renders correctly

    TypeError: Cannot read properties of undefined (reading 'toString')

      at reduce (node_modules/react-native-reanimated/lib/reanimated2/hook/utils.js:46:33)
          at Array.reduce (<anonymous>)
      at buildWorkletsHash (node_modules/react-native-reanimated/lib/reanimated2/hook/utils.js:44:36)
      at buildDependencies (node_modules/react-native-reanimated/lib/reanimated2/hook/utils.js:60:27)
      at useHandler (node_modules/react-native-reanimated/lib/reanimated2/hook/utils.js:36:20)
      at useAnimatedScrollHandler (node_modules/react-native-reanimated/lib/reanimated2/hook/useAnimatedScrollHandler.js:5:47)
      at node_modules/react-native-collapsible-tab-view/lib/commonjs/Container.tsx:284:30
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
      at updateForwardRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8038:20)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10015:16)

  console.warn
    [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!

      at showRngh2NoticeIfNeeded (node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:128:5)
      at new Handler (node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:176:9)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4022:18)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8399:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9990:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)

  console.error
    The above error occurred in the <ForwardRef> component:
    
        at /Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-collapsible-tab-view/lib/commonjs/Container.tsx:63:7
        at Home (/Users/shensven/Documents/GitHub/Readhubn/src/screens/Home.tsx:9:46)
        at StaticContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/StaticContainer.tsx:7:3)
        at EnsureSingleNavigator (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/EnsureSingleNavigator.tsx:20:49)
        at SceneView (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/SceneView.tsx:33:3)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at CardSheet (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardSheet.tsx:15:3)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at AnimatedComponent (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:44:43)
        at AnimatedComponentWrapper
        at Handler (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-gesture-handler/lib/commonjs/handlers/createHandler.ts:163:51)
        at PanGestureHandler (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/GestureHandlerNative.tsx:10:22)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at AnimatedComponent (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:44:43)
        at AnimatedComponentWrapper
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at Card (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/Card.tsx:92:58)
        at CardContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardContainer.tsx:59:24)
        at RNSScreen
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockNativeComponent.js:15:18)
        at AnimatedComponent (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/Libraries/Animated/createAnimatedComponent.js:44:43)
        at AnimatedComponentWrapper
        at MaybeFreeze (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-screens/lib/commonjs/index.native.tsx:169:22)
        at Screen (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-screens/lib/commonjs/index.native.tsx:206:51)
        at MaybeScreen (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Screens.tsx:26:29)
        at RNSScreenContainer
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockNativeComponent.js:15:18)
        at ScreenContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-screens/lib/commonjs/index.native.tsx:324:11)
        at MaybeScreenContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Screens.tsx:12:38)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at Background (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/elements/lib/commonjs/Background.tsx:9:36)
        at CardStack (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:384:29)
        at RNCSafeAreaProvider
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockNativeComponent.js:15:18)
        at SafeAreaProvider (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native-safe-area-context/lib/commonjs/SafeAreaContext.tsx:24:34)
        at SafeAreaProviderCompat (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/elements/lib/commonjs/SafeAreaProviderCompat.tsx:34:48)
        at View
        at Component (/Users/shensven/Documents/GitHub/Readhubn/node_modules/react-native/jest/mockComponent.js:28:18)
        at GestureHandlerRootView
        at StackView (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:63:70)
        at StackNavigator (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/stack/lib/commonjs/navigators/createStackNavigator.tsx:33:25)
        at EnsureSingleNavigator (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/EnsureSingleNavigator.tsx:20:49)
        at BaseNavigationContainer (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/core/lib/commonjs/BaseNavigationContainer.tsx:81:5)
        at ThemeProvider (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/native/lib/commonjs/theming/ThemeProvider.tsx:11:39)
        at NavigationContainerInner (/Users/shensven/Documents/GitHub/Readhubn/node_modules/@react-navigation/native/lib/commonjs/NavigationContainer.tsx:55:5)
        at App
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        6.631 s, estimated 37 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

In this commit, the `react-native-reanimated` can be passed with the jest https://github.com/shensven/Readhubn/commit/aaf335c43475f2bf385ac7d38dd4d3f19693e850

## Snack or minimal code example
```ts
// src/screens/Home.tsx
import React, {useCallback} from 'react';
import {ListRenderItem, StyleSheet, View} from 'react-native';
import {Tabs} from 'react-native-collapsible-tab-view';

const DATA = [0, 1, 2, 3, 4];
const identity = (v: unknown): string => v + '';

const Home: React.FC = () => {
  const renderItem: ListRenderItem<number> = useCallback(({index}) => {
    return <View style={[styles.box, index % 2 === 0 ? styles.boxB : styles.boxA]} />;
  }, []);

  return (
    <Tabs.Container>
      <Tabs.Tab name="A">
        <Tabs.FlatList data={DATA} renderItem={renderItem} keyExtractor={identity} />
      </Tabs.Tab>
      <Tabs.Tab name="B">
        <Tabs.FlatList data={DATA} renderItem={renderItem} keyExtractor={identity} />
      </Tabs.Tab>
    </Tabs.Container>
  );
};

const styles = StyleSheet.create({
  box: {
    height: 250,
    width: '100%',
  },
  boxA: {
    backgroundColor: 'white',
  },
  boxB: {
    backgroundColor: '#D8D8D8',
  },
  header: {
    height: 250,
    width: '100%',
    backgroundColor: '#2196f3',
  },
});

export default Home;
```

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.67.2  |
| react-native-reanimated              |  ^2.4.1  |
| NodeJS                               |  v16.14.0  |
| Xcode                                |  13.2.1 (13C100)  |
| Java                                 |  openjdk 11.0.12 2021-07-20  |
| Gradle                               |  7.2  |
| expo                                 |         |

## Affected platforms

- [x] Android
- [x] iOS
- [ ] Web

**Comment by jahglow** [comment]
to ayone stumbling on this and loosing it over debugging, your final resort would be [this comment](https://github.com/software-mansion/react-native-reanimated/issues/3049#issuecomment-1117281665)

**Comment by RobertSasak** [comment]
If you encounter this issue on web, read on. As stated in the documentation reanimated requires _react-native-reanimated/plugin_ to be part of the build process. In the documentation it is included in _babel.config.js_.
```js
module.exports = {
    presets: ['module:metro-react-native-babel-preset'],
    plugins: ['react-native-reanimated/plugin'], // <-- Added this line
}
```
However maybe you are using webpack to to produce web version. In this case _react-native-reanimated/plugin_ need to be part of the webpack build process. As well you need to specify all the packages that use reanimated. 
```js
const path = require('path')

const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')

const appDirectory = path.resolve(__dirname)
const { presets } = require(`${appDirectory}/babel.config.js`)

const compileNodeModules = [
    // Add every react-native package that needs compiling
    '@gorhom/bottom-sheet', # <-- Add all the packages that are using reanimated
    'react-native',
].map((moduleName) => path.resolve(appDirectory, `node_modules/${moduleName}`))

const babelLoaderConfiguration = {
    test: /\.js$|tsx?$/,
    // Add every directory that needs to be compiled by Babel during the build.
    include: [
        path.resolve(__dirname, 'index.web.js'), // Entry to your application
        path.resolve(__dirname, 'App.web.tsx'), // Change this to your main App file
        path.resolve(__dirname, 'src'),
        ...compileNodeModules,
    ],
    use: {
        loader: 'babel-loader',
        options: {
            cacheDirectory: false,
            presets,
            plugins: ['react-native-web', 'react-native-reanimated/plugin'], # <-- Plugin added here
        },
    },
}

const svgLoaderConfiguration = {
    test: /\.svg$/,
    use: [
        {
            loader: '@svgr/webpack',
        },
    ],
}

const imageLoaderConfiguration = {
    test: /\.(gif|jpe?g|png|svg)$/,
    use: {
        loader: 'url-loader',
        options: {
            name: '[name].[ext]',
            esModule: false,
        },
    },
}

module.exports = {
    entry: {
        app: path.join(__dirname, 'index.web.js'),
    },
    output: {
        path: path.resolve(appDirectory, 'dist'),
        publicPath: '/',
        filename: 'main.bundle.js',
    },
    resolve: {
        extensions: ['.web.tsx', '.web.ts', '.tsx', '.ts', '.web.js', '.js'],
        alias: {
            'react-native$': 'react-native-web',
            screens: path.resolve(__dirname, 'src/screens'),
            services: path.resolve(__dirname, 'src/services'),
            components: path.resolve(__dirname, 'src/components'),
            hooks: path.resolve(__dirname, 'src/hooks'),
            locales: path.resolve(__dirname, 'src/locales'),
        },
    },
    module: {
        rules: [
            babelLoaderConfiguration,
            imageLoaderConfiguration,
            svgLoaderConfiguration,
            { test: /\.css$/, use: ['style-loader', 'css-loader'] },
            {
                test: /\.ttf$/,
                loader: 'url-loader', // or directly file-loader
                include: path.resolve(
                    __dirname,
                    'node_modules/react-native-vector-icons',
                ),
            },
        ],
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: path.join(__dirname, 'index.html'),
        }),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.DefinePlugin({
            // See: https://github.com/necolas/react-native-web/issues/349
            __DEV__: JSON.stringify(true),
        }),
        new webpack.DefinePlugin({ process: { env: {} } }),
    ],
    devServer: {
        historyApiFallback: true,
    },
}
```

**Comment by devalnor** [comment]
If you want to do the same with **expo.io**:

**Customize Webpack**

> When you run expo start --web or expo export:web the CLI will check to see if your project has a webpack.config.js in the root directory. If the project doesn't then Expo will use the default @expo/webpack-config

```npx expo customize:web```

> This will install @expo/webpack-config as a dev dependency and create a template ./webpack.config.js

**Change  ./webpack.config.js with this**
```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: [
          '@gorhom/bottom-sheet',  # <-- Add all the packages that are using reanimated
        ],
      },
    },
    argv
  );
  return config;
};
```
