### ISSUE TITLE
ANR Semaphore.acquire in NodesManager.java

### ISSUE THREAD

**Issue by marf** [software-mansion/react-native-reanimated#3062]
## Description

Hello, we are experiencing several ANR where users'device seems not to be able to acquire semaphore lock and wait indefinitely blocking the main thread.

Do you have any ideas on how we can prevent this?

Here's the stacktrace of the ANR:

```
main (waiting): tid=1 systid=16766
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1023)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1334)
       at java.util.concurrent.Semaphore.acquire(Semaphore.java:318)
       at com.swmansion.reanimated.NodesManager.performOperations(NodesManager.java:251)
       at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:280)
       at com.swmansion.reanimated.NodesManager.access$000(NodesManager.java:65)
       at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:170)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
       at android.view.Choreographer.doCallbacks(Choreographer.java:849)
       at android.view.Choreographer.doFrame(Choreographer.java:775)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8250)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)

```

### Expected behavior

App should not crash due to an ANR.

| name                                 | version |
| ------------------------------------| ------- |
| react-native                                  | 0.63.3 |
| react-native-reanimated              | 2.1.4 |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by ryanliljestrom** [comment]
We are seeing this crash as well

**Comment by areydra** [comment]
any updates for this issue @marf? Does this issue already solve?

**Comment by malikzype** [comment]
Getting a similar issue... with reanimated v3. @marf  @areydra Did you guys manage to fix this?

**Comment by charlyBerthet** [comment]
Getting same issue after upgrading from v2 to v3

**Comment by tj-mc** [comment]
I'm experiencing this on 3.6.0. We can't provide a repro as it only happens in the wild
