### ISSUE TITLE
Android app crash after upgrading to  0.68.0

### ISSUE THREAD

**Issue by suri-cs** [software-mansion/react-native-reanimated#3178]
## Description
It was working  perfectly before update, nothing changed in Codebase and navigation . Assuming error in the navigation stack Drawer  navigator as crash is just there in Home Screen under drawer navigator.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |  0.68.0       |
| react-native-reanimated              |  2.7. 0      |
| NodeJS                               |   16.8      |
| Xcode                                |     -    |
| Java                                 |    11.0.12     |
| Gradle                               |     7.3.3    |
| expo                                 |     -    |

## Affected platforms

- [ ] Android

**Comment by BlackJohnny** [comment]
I have a similar behavior but it complains about `undefined is not an object (evaluating 'animation.current')` (in 2.6.0). The application simply crashes and the following info is in the android logs:

For v2.6.0
```
    com.facebook.jni.CppException: undefined is not an object (evaluating 'animation.current')
    
    workletValueSetter@XXX/node_modules/react-native-reanimated/src/reanimated2/core.ts (190:0):1:384
    [native code]
        at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
        at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:24)
        at com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:43)
        at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2022-05-29 12:17:43.782 690-690/io.XXX A/XXX: java_vm_ext.cc:579] JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: Tried to synchronously call function {create} from a different thread.
```

For 2.8.0 (not much):

```
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x50 in tid 3753 (mqt_js), pid 3513 (XXX)
```

**Comment by hugoh59** [comment]
Did you find a solution ?

**Comment by karel-suchomel-ed** [comment]
Same issue. Happened in production to a test customer.
Samsung S22 Ultra Android 13.
"react-native": "0.71.6"
"react-native-reanimated": "2.14.4"

**Comment by Latropos** [comment]
Closing due to lack of reproduction
