### ISSUE TITLE
[Android] 2.8.0 - The specified child already has a parent

### ISSUE THREAD

**Issue by andreialecu** [software-mansion/react-native-reanimated#3234]
## Description

I found this logged on Sentry and it seems to mention a Reanimated stack trace.

Android 10, OnePlus model GM1925 (QKQ1.190716.003)

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
    at android.view.ViewGroup.addViewInner(ViewGroup.java:5131)
    at android.view.ViewGroup.addView(ViewGroup.java:4960)
    at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:466)
    at android.view.ViewGroup.addView(ViewGroup.java:4900)
    at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:38)
    at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:19)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
    at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:306)
    at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1161)
    at android.view.Choreographer.doCallbacks(Choreographer.java:986)
    at android.view.Choreographer.doFrame(Choreographer.java:894)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7682)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Expected behavior

No crash.

### Actual behavior & steps to reproduce

Native crash, not sure what the circumstances are. Just found it in Sentry.

## Snack or minimal code example

Unknown.

## Package versions

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |   0.68.1      |
| react-native-reanimated              | 2.8.0        |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by wbinarytree** [comment]
Have similar issue, only stacktrace 

```
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5247)
       at android.view.ViewGroup.addView(ViewGroup.java:5076)
       at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:465)
       at android.view.ViewGroup.addView(ViewGroup.java:5016)
       at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:37)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:306)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
       at android.view.Choreographer.doCallbacks(Choreographer.java:845)
       at android.view.Choreographer.doFrame(Choreographer.java:775)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by JoniVR** [comment]
Same stack trace here, I can say that the device in question is also OnePlus. I can't reproduce it in the emulator (I know how the user triggers it). So might be brand specific? Not sure.

**Comment by robertwt7** [comment]
I am actually experiencing this issue as well on production and emulator.

It happens only at app start though, I have to close the app the re-open it to reproduce.

Reloading / refreshing does not make the emulator crash.

Should be related to this one: https://github.com/react-navigation/react-navigation/issues/10012

**Comment by robertwt7** [comment]
I think this is also related to this:
https://github.com/facebook/react-native/issues/27552

**Comment by animaonline** [comment]
No updates on this? The library is basically unusable in the latest version of Expo sdk.

**Comment by abitling** [comment]
@robertwt7 Were you able to find any solution or a possible work around for this issue? We are also facing same issue as you, happens once per launch/install on Android.

**Comment by el-banna** [comment]
We faced the same stack trace sometimes upon reloading the app.
In our case, we are using wix's `react-native-navigation` library (v7.26.0)

Updating `react-native-navigation` to the latest version seems to fix it.

**Comment by matasmaciulaitis** [comment]
I seem to be getting same issue on Android using react-native-reanimated@3.6.3

`Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5958)
       at android.view.ViewGroup.addView(ViewGroup.java:5777)
       at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:514)
       at android.view.ViewGroup.addView(ViewGroup.java:5717)
       at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:38)
       at com.facebook.react.views.view.ReactClippingViewManager.addView(ReactClippingViewManager.java:19)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
       at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:300)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:926)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1037)
       at com.facebook.react.uimanager.UIViewOperationQueue.-$$Nest$mflushPendingBatches()
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1097)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:725)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7814)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)`

**Comment by Sumit-Budhiraja** [comment]
same issues, happening for my android application as well

**Comment by tdvuanh** [comment]
We still face this issue on version 3.13.0 and we saw this issue on Sentry.
I tried to reproduce it on emulators and also real devices but could not.
After investigation follow stack trace. this issue happens because inside function addViewInner of android.view.ViewGroup.addView: they have to check if (child.getParent() != null). I am curious why Android needs to check it and why react-native or react-native-reanimated did not check this condition on the function addView or manageChildren.

**Comment by DrZoidberg09** [comment]
Since Expo 52 and the newest rn-reanimated I get the same error on Android. With previous versions I worked nicely.

**Comment by MasonTyTran** [comment]
Same error here, should we reopen this issue?

**Comment by matt-dalton** [comment]
I also got it on the latest reanimated version and had to revert (i.e. remove the animation)

**Comment by kirasiris** [comment]
Has anyone found the solution for this?  I upgraded my app to the latest SDKv52 and it started to throw that same error.

**Comment by puke3615** [comment]
Same issue, and my version is:
```json
"expo": "^52.0.19"
"react-native-reanimated": "~3.16.1"
```

**Comment by KristianLentino99** [comment]
Same problem here

**Comment by Takeda04** [comment]
i alse faces with this problem, but i think it is not animated library, i faced it when i tried to navigate to auth page with router.replace, and i changed it to router.push and it is fixed

**Comment by ChronSyn** [comment]
> i alse faces with this problem, but i think it is not animated library, i faced it when i tried to navigate to auth page with router.replace, and i changed it to router.push and it is fixed

Oh my... I've spent the better part of a week chasing down this issue, changing library versions, thinking it was related to react-native-maps, and then expo-image.

And it turns out that this was the fix for me too.

**Comment by jahirfiquitiva** [comment]
But what if one actually wants to replace the current screen with a new one so that the current one is not kept in the screens history? (push vs replace)

**Comment by AyoParadis** [comment]
> But what if one actually wants to replace the current screen with a new one so that the current one is not kept in the screens history? (push vs replace)

exactly! did you find a fix

**Comment by ChronSyn** [comment]
> But what if one actually wants to replace the current screen with a new one so that the current one is not kept in the screens history? (push vs replace)

I know it's a workaround with a trade-off. The goal was to help people know a potential source of the crash so that the root cause can be identified and triaged, and how to work around it until a fix is developed. It's not an ideal solution, but maybe using dispatch and reset would resolve the issues with the workaround in the meantime.

**Comment by steve228uk** [comment]
Wrapping in `requestAnimationFrame` works around this:

```
requestAnimationFrame(() => {
    navigationRef.resetRoot({ index: 0, routes: [{ name: "Auth" }] });
});
```

**Comment by PepeTonin** [comment]
> Wrapping in `requestAnimationFrame` works around this:
> 
> ```
> requestAnimationFrame(() => {
>     navigationRef.resetRoot({ index: 0, routes: [{ name: "Auth" }] });
> });
> ```

Worked for me, thanks

**Comment by dan-trewin** [comment]
FWIW, this crash was happening for me after recently updating my Android app to New Architecture and I think it's some conflict between `navigation.reset`,  `@react-navigation/drawer`, and React Native New Architecture on Android specifically.

The reason I say this is because I've fixed the issue by merely removing a call to `navigation.closeDrawer()`

```ts
 <ListItem
  style={styles.logoutItem}
  title='Logout' 
  onPress={() => {
    props.navigation.closeDrawer(); // if this line is present = crash
    logout(); // this calls navigation.reset...
  }}
/>
```

In my case, closing the drawer before logout wasn't really necessary anyways as reset is immediately called anyways so you couldn't really even see the "drawer closing animation"

**Comment by steve228uk** [comment]
> FWIW, this crash was happening for me after recently updating my Android app to New Architecture and I think it's some conflict between `navigation.reset`, `@react-navigation/drawer`, and React Native New Architecture on Android specifically.
> 
> The reason I say this is because I've fixed the issue by merely removing a call to `navigation.closeDrawer()`
> 
>  <ListItem
>   style={styles.logoutItem}
>   title='Logout' 
>   onPress={() => {
>     props.navigation.closeDrawer(); // if this line is preset = crash
>     logout(); // this calls navigation.reset...
>   }}
> />
> In my case, closing the drawer before logout wasn't really necessary anyways as reset is immediately called anyways so you couldn't really even see the "drawer closing animation"

Yeah, our crash was also caused by the drawer package. I'm removing it from a future release of our app.

**Comment by zlanich** [comment]
For me, it was happening most commonly with Expo Router on router.back() after some automated task - ie. User presses button to save something, that callback awaits, then calls router.back(). I tried using requestAnimationFrame() with no luck, but adding a small setTimeout() before navigating got around it for me for now.

**Comment by nicolasizraelski-squire** [comment]
Calling `router.replace` after a `setTimeout` worked for me:
```setTimeout(() => router.replace(target), 0);```

**Comment by Mert75** [comment]
The Fabric addViewAt crash was fixed in RN 0.83 (SDK 55).      

Upgrading to SDK 55+ resolves it at the core level.
