### ISSUE TITLE
Build android failed

### ISSUE THREAD

**Issue by mayconline** [software-mansion/react-native-reanimated#3345]
## Description

build android failed when `./gradlew bundleRelease`

### Expected behavior

build successfully

### Actual behavior & steps to reproduce

```js
error node_modules/react-native-reanimated/lib/index.js: /project/node_modules/react-native-reanimated/lib/index.js: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
  4 | export * from './reanimated1';
  5 | export * from './reanimated2';
> 6 | export * as default from './Animated';
    |        ^^^^^^^^^^^^
  7 |.
SyntaxError: /project/node_modules/react-native-reanimated/lib/index.js: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
  4 | export * from './reanimated1';
  5 | export * from './reanimated2';
> 6 | export * as default from './Animated';
    |        ^^^^^^^^^^^^
  7 |
    at File.buildCodeFrameError (/project/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/lib/transformation/file/file.js:249:12)
    at NodePath.buildCodeFrameError (/project/node_modules/metro-react-native-babel-transformer/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/index.js:143:21)
    at assertExportSpecifier (/project/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:111:16)
    at /project/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:201:9
    at Array.forEach (<anonymous>)
    at /project/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:200:31
    at Array.forEach (<anonymous>)
    at getModuleMetadata (/project/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:148:27)
    at normalizeModuleAndLoadMetadata (/project/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:57:7)
```

## Snack or minimal code example

```js
cd android
./gradlew bundleRelease
```

## Package versions

com.android.tools.build:gradle:7.1.1

| name                                 | version |
| ------------------------------------ | ------- |
| react-native                         |    0.69.1     |
| react-native-reanimated              |    2.9.0     |
| NodeJS                               |    16.15.1     |
| Java                                 |    11     |
| Gradle                               |     7.3.3    |

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by piaskowyk** [comment]
Are you sure that you add Reaniamted plugin to `babel.config.js`?
```js
plugins: ['react-native-reanimated/plugin']
```
more info: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin

**Comment by GaelCO** [comment]
@piaskowyk, Indeed, that was the problem for me.
That's works now.
Thanks

**Comment by mayconline** [comment]
work successfully, thanks ^^

**Comment by mayconline** [comment]
> Are you sure that you added Reanimated plugin to `babel.config.js`?
> 
> ```js
> plugins: ['react-native-reanimated/plugin']
> ```
> 
> more info: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin

work successfully, thanks ^^

**Comment by kyle-ssg** [comment]
For me, this was down to not clearing cache 

```
npm start -- --reset-cache
```

Or 

```
yarn start --reset-cache
```

**Comment by lucas-figueiredo-m** [comment]
I'm also having this issue, but in a different shape.

The error is the same, but it's happening when I', trying to publish a jsbundle using epicenter. Regular builds for android and iOS works fine. Only building for epicenter this happens.

Any ideas?
