### ISSUE TITLE
dlopen failed: library "libfolly_json.so" not found

### ISSUE THREAD

**Issue by Anoopbk1** [software-mansion/react-native-reanimated#3358]
### My app crashes without any formal error. This error I found in logcat 

```
E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.myapp, PID: 11305
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libfolly_json.so" not found: needed by /data/app/~~4gp2E7YtL8o-49YMQ4uIrQ==/com.myapp-7jUAREIQl67FHrb4so-s0Q==/lib/arm64/libreanimated.so in namespace classloader-namespace
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at com.swmansion.reanimated.NativeProxy.<clinit>(NativeProxy.java:26)
        at com.swmansion.reanimated.NodesManager.initWithContext(NodesManager.java:140)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:24)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1389)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:136)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1108)
        at java.lang.Thread.run(Thread.java:920)
I/Process: Sending signal. PID: 11305 SIG: 9
```
  ```
buildToolsVersion = "30.0.3"
  minSdkVersion = 21
  compileSdkVersion = 31
  targetSdkVersion = 31
  ndkVersion = "21.4.7075529"
  kotlin_version = '1.6.10'
```

When I try to run my application in Visual Studio code using npm react-native run-android, it builds successfully but App stops soon after the emulator loads. Tried restarting the app, clean Gradle, rebuild, but the same issue occurs every time. Tried a few of the solutions shown here on GitHub but no change.

**Comment by tomekzaw** [comment]
Hello @Anoopbk1! Thanks for reporting the issue.

Can you please specify which version of `react-native` and `react-native-reanimated` are you using?

In React Native 0.69, shared libraries `folly_json` and `folly_futures` were merged into `folly_runtime` (see https://github.com/facebook/react-native/commit/e5874d90e20adce5c0350ce1794c6c1f759eae3b).

We addressed this change in #3206 which was released with v2.9.0 (and v3.0.0-rc.0 for Fabric).

Please upgrade to `react-native-reanimated@2.9.1` (or newer) and let us know if it works for you. 😃

**Comment by ahnafnafee** [comment]
Also have the same issue. I'm using `"react-native": "0.69.3"`, `react-native-reanimated@2.9.1` [set in resolutions]

**Comment by ahnafnafee** [comment]
Needs to be reopened as issue persists

**Comment by Anoopbk1** [comment]
I had to create a new application and copied all the stuffs from the old application to the new application and installed all the components to make it work.

**Comment by Ozaoujal** [comment]
same problem here
