### ISSUE TITLE
bug: doesn't work in yarn3 monorepo

### ISSUE THREAD

**Issue by rxliuli** [software-mansion/react-native-reanimated#3512]
### Description

just doesn't work, if there is any temporary workaround please let me know

```ts
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1012 file(s) to forward-jetify. Using 16 workers...
info JS server already running.
info Installing the app...
> Task :react-native-gradle-plugin:compileKotlin UP-TO-DATE
> Task :react-native-gradle-plugin:compileJava UP-TO-DATE
> Task :react-native-gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :react-native-gradle-plugin:processResources UP-TO-DATE
> Task :react-native-gradle-plugin:classes UP-TO-DATE
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :react-native-gradle-plugin:jar UP-TO-DATE

> Configure project :react-native-reanimated
Native libs debug enabled: false
Android gradle plugin: 7.1.1
Gradle: 7.3.3
building Reanimated2
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :react-native-reanimated:preBuild UP-TO-DATE
> Task :react-native-reanimated:preDebugBuild UP-TO-DATE
> Task :react-native-reanimated:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :react-native-reanimated:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :react-native-reanimated:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :react-native-reanimated:mergeDebugShaders UP-TO-DATE
> Task :react-native-reanimated:compileDebugShaders NO-SOURCE
> Task :react-native-reanimated:generateDebugAssets UP-TO-DATE
> Task :react-native-reanimated:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :react-native-reanimated:compileDebugRenderscript NO-SOURCE
> Task :react-native-reanimated:generateDebugResValues UP-TO-DATE
> Task :react-native-reanimated:generateDebugResources UP-TO-DATE
> Task :react-native-reanimated:packageDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-reanimated:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-reanimated:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :react-native-reanimated:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-reanimated:parseDebugLocalResources UP-TO-DATE
> Task :react-native-reanimated:generateDebugRFile UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :react-native-reanimated:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-reanimated:javaPreCompileDebug UP-TO-DATE
> Task :react-native-reanimated:packageNdkLibs NO-SOURCE
> Task :react-native-reanimated:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-reanimated:bundleLibCompileToJarDebug UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :react-native-reanimated:processDebugJavaRes NO-SOURCE
> Task :react-native-reanimated:bundleLibResDebug NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :react-native-reanimated:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:mergeLibDexDebug UP-TO-DATE
> Task :app:mergeProjectDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :react-native-reanimated:applyJavaPatches NO-SOURCE
> Task :react-native-reanimated:createNativeDepsDirectories UP-TO-DATE

> Task :react-native-reanimated:downloadBoost UP-TO-DATE
Download https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

> Task :react-native-reanimated:downloadDoubleConversion UP-TO-DATE
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :react-native-reanimated:downloadFolly UP-TO-DATE
Download https://github.com/facebook/folly/archive/v2021.06.28.00.tar.gz

> Task :react-native-reanimated:downloadGlog UP-TO-DATE
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :react-native-reanimated:prepareBoost UP-TO-DATE
> Task :react-native-reanimated:downloadNdkBuildDependencies UP-TO-DATE
> Task :react-native-reanimated:prepareDoubleConversion UP-TO-DATE
> Task :react-native-reanimated:prepareFolly UP-TO-DATE
> Task :react-native-reanimated:prepareGlog UP-TO-DATE
> Task :react-native-reanimated:unpackReactNativeAAR UP-TO-DATE
> Task :react-native-reanimated:prepareThirdPartyNdkHeaders UP-TO-DATE
> Task :react-native-reanimated:extractAARHeaders
> Task :react-native-reanimated:extractSOFiles
> Task :react-native-reanimated:configureCMakeDebug[arm64-v8a]

> Task :react-native-reanimated:buildCMakeDebug[arm64-v8a] FAILED
C/C++: ninja: error: mkdir(CMakeFiles/reanimated.dir/C_/Users/rxliuli/Code/company/react-native-reanimated-error-demo): No such file or directory

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
57 actionable tasks: 5 executed, 52 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process C:\Users\rxliuli\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C C:\Users\rxliuli\Code\company\react-native-reanimated-error-demo\apps\react-native-hello-example\node_modules\react-native-reanimated\android\.cxx\Debug\6o55662i\arm64-v8a reanimated}
  ninja: Entering directory `C:\Users\rxliuli\Code\company\react-native-reanimated-error-demo\apps\react-native-hello-example\node_modules\react-native-reanimated\android\.cxx\Debug\6o55662i\arm64-v8a'
  [0/2] Re-checking globbed directories...
  ninja: build stopped: .
  
  ninja: error: mkdir(CMakeFiles/reanimated.dir/C_/Users/rxliuli/Code/company/react-native-reanimated-error-demo): No such file or directory


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:buildCMakeDebug[arm64-v8a]'.
> Build command failed.
  Error while executing process C:\Users\rxliuli\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C C:\Users\rxliuli\Code\company\react-native-reanimated-error-demo\apps\react-native-hello-example\node_modules\react-native-reanimated\android\.cxx\Debug\6o55662i\arm64-v8a reanimated}
  ninja: Entering directory `C:\Users\rxliuli\Code\company\react-native-reanimated-error-demo\apps\react-native-hello-example\node_modules\react-native-reanimated\android\.cxx\Debug\6o55662i\arm64-v8a'
  [0/2] Re-checking globbed directories...
  ninja: build stopped: .
  
  ninja: error: mkdir(CMakeFiles/reanimated.dir/C_/Users/rxliuli/Code/company/react-native-reanimated-error-demo): No such file or directory


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at makeError (C:\Users\rxliuli\Code\company\react-native-reanimated-error-demo\apps\react-native-hello-example\node_modules\execa\index.js:174:9)
    at C:\Users\rxliuli\Code\company\react-native-reanimated-error-demo\apps\react-native-hello-example\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\rxliuli\Code\company\react-native-reanimated-error-demo\apps\react-native-hello-example\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\rxliuli\Code\company\react-native-reanimated-error-demo\apps\react-native-hello-example\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
```

### Steps to reproduce

1. `git clone https://github.com/rxliuli/react-native-reanimated-error-demo`
2. `cd apps/react-native-hello-example`
3. `yarn && yarn android`
4. getting the above error

### Snack or a link to a repository

https://github.com/rxliuli/react-native-reanimated-error-demo

### Reanimated version

2.10.0

### React Native version

0.69.4

### Platforms

Android

### Acknowledgements

Yes

**Comment by mbastian93** [comment]
I'm currently having the same issue;

Did you manage to fix it and -if so - how?

**Comment by rxliuli** [comment]
> I'm currently having the same issue;
> 
> Did you manage to fix it and -if so - how?

react-native downgrade to 0.68.2

**Comment by mbastian93** [comment]
> > I'm currently having the same issue;
> > Did you manage to fix it and -if so - how?
> 
> react-native downgrade to 0.68.2

Huh, i'm already using that version and it still doesn't work...

**Comment by mbastian93** [comment]
Update: 
Using react-native@0.68.2 and react-native-reanimated@2.9.1 works, but as soon as i upgrade react-native-reanimated to 2.10.0, i'm running in the error mentioned above.

**Comment by chungtv1doi** [comment]
> 

How to downgrade react-native-reanimated @2.9.1?
