### ISSUE TITLE
Issue when using react-native-reanimated with react-native-multithreading

### ISSUE THREAD

**Issue by Fabian-webdev** [software-mansion/react-native-reanimated#3659]
### Description

When installing react-native-reanimated, react-native-gesture-handler, react-native-mmkv, and react-native-multithreading and running the app, it builds without error but then instantly crashes when executed on either a device or emulator
Here is the logcat output:

2022-10-08 06:09:56.309  2812-3114  unknown:ReactContext    com.test                            W  initializeMessageQueueThreads() is called.
2022-10-08 06:09:56.309  2812-3114  [REANIMATED]            com.test                            W  Since 2.5.0, Reanimated autoinstalls on Android - you can remove getJSIModulePackage() override in MainApplication.java.
2022-10-08 06:09:56.354  2812-3114  AndroidRuntime          com.test                            E  FATAL EXCEPTION: create_react_context
                                                                                                    Process: com.test, PID: 2812
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN10reanimated16RuntimeDecorator15decorateRuntimeERN8facebook3jsi7RuntimeENSt6__ndk112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE" referenced by "/data/app/~~-EpfXOB9MAOEOUPAVlYnVA==/com.test-Rskv2sU1PaCyJpq3qKijBA==/base.apk!/lib/arm64-v8a/librnmultithreading.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1656)
                                                                                                    	at com.reactnativemultithreading.MultithreadingModule.<clinit>(MultithreadingModule.java:26)
                                                                                                    	at com.reactnativemultithreading.MultithreadingModule.install(MultithreadingModule.java:47)
                                                                                                    	at com.test.TestJSIPackage.getJSIModules(TestJSIPackage.java:16)
                                                                                                    	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1390)
                                                                                                    	at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
                                                                                                    	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)

### Steps to reproduce

1. npx react-native init test --template  react-native-template-typescript@6.8.4 (that is react native version: 0.68.0)
2. npm i react-native-reanimated react-native-mmkv react-native-gesture-handler react-native-multithreading
3. npx react-native link react-native-reanimated.... (for all libraries)
4. Following the installation steps for react-native-multithreading
5. build

### Snack or a link to a repository

-

### Reanimated version

Doesnt work with: 2.2.4 and up, tested with 2.10.0

### React Native version

0.68.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device model

All devices all emulators (> API 30)

### Acknowledgements

Yes

### Current Fix:
Downgrade reanimated to 2.2.4

**Comment by Fabian-webdev** [comment]
Omitting the **setup** steps for react-native-multithreading where we have to create

// Multithreading support
        @Override
        protected JSIModulePackage getJSIModulePackage() {
          return new TestJSIPackage();
        }

in **MainApplication.java** seems to resolve this issue

**Comment by Fabian-webdev** [comment]
The above step fixes the error but after that spawnThread from react-native-multithreading is undefined.
Still need help concering this issue

**Comment by piaskowyk** [comment]
Hi! Thanks for the report, but this problem comes from `react-native-multithreading` not from our library and we haven't enough capacity to fixing external libraries also :/
