### ISSUE TITLE
conflict react-native-reanimated with react-native-keychain

### ISSUE THREAD

**Issue by fkazemi5236** [software-mansion/react-native-reanimated#3766]
### Description

I have a react-native app RN 0.71.8
with react-native-reanimated 3.1.0
and when I install react-native-keychain package, my app was successfully installed on adb device. but when I opened the app I see the error message that says: 

"unable to load script. make sure you're either running Metro (run 'npx react-native start') or ....."

you know.. every thing is Ok. metro is running and its Ok, the terminal was built successfully and i dont understand what happen with install this two packages together :\

I am completely confused
so when I remove react-native-keychain or remove react-native-reanimated, my app run perfectly 🙄

### Steps to reproduce

npx react-native run android

### Snack or a link to a repository

https://github.com/fkazemi5236/react-native-keychain-reanimated.git

### Reanimated version

^3.1.0

### React Native version

0.71.8

### Platforms

Android

### Acknowledgements

Yes

**Comment by MircoSans** [comment]
> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Users/xierruisi/Documents/Working/Fixon/node_modules/react-native-reanimated/android/react-native-reanimated-70-hermes.aar

> Task :app:bundleReleaseJsAndAssets
warn Package react-native-ui-lib contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated


metro-file-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: std::__1::system_error: open: /Users/xierruisi/Documents/Working/Fixon: Operation not permitted. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: std::__1::system_error: open: /Users/xierruisi/Documents/Working/Fixon: Operation not permitted
    at BunserBuf.<anonymous> (/Users/xierruisi/Documents/Working/Fixon/node_modules/fb-watchman/index.js:95:23)
    at BunserBuf.emit (node:events:527:28)
    at BunserBuf.process (/Users/xierruisi/Documents/Working/Fixon/node_modules/bser/index.js:292:10)
    at /Users/xierruisi/Documents/Working/Fixon/node_modules/bser/index.js:247:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on WatchmanWatcher instance at:
    at Client.<anonymous> (/Users/xierruisi/Documents/Working/Fixon/node_modules/metro-file-map/src/watchers/WatchmanWatcher.js:114:10)
    at Client.emit (node:events:527:28)
    at BunserBuf.<anonymous> (/Users/xierruisi/Documents/Working/Fixon/node_modules/fb-watchman/index.js:107:12)
    at BunserBuf.emit (node:events:527:28)
    at /Users/xierruisi/Documents/Working/Fixon/node_modules/bser/index.js:249:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  watchmanResponse: {
    error: 'std::__1::system_error: open: /Users/xierruisi/Documents/Working/Fixon: Operation not permitted',
    version: '2022.08.22.00'
  }
}

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
6 actionable tasks: 1 executed, 5 up-to-date

**Comment by boonook** [comment]
same

**Comment by boonook** [comment]
https://github.com/boonook/nativeapp/tree/native7 /////github

**Comment by boonook** [comment]
System:
    OS: macOS 13.0
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 280.39 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.3 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2022.10.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by fkazemi5236** [comment]
@tomekzaw

**Comment by fkazemi5236** [comment]
@tomekzaw
