### ISSUE TITLE
AAR for react-native-reanimated has been found /Users/zhuxiuwu/space/native/nativeapp/node_modules/react-native-reanimated/android/react-native-reanimated-70-hermes.aar

### ISSUE THREAD

**Issue by boonook** [software-mansion/react-native-reanimated#3776]
### Description

AAR for react-native-reanimated has been found

System:
    OS: macOS 13.0
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 816.70 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.18.3 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2022.10.31.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.0
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.4 => 0.70.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1、yarn start
2、yarn android

### Snack or a link to a repository

https://github.com/boonook/nativeapp/tree/native7

### Reanimated version

2.12.0

### React Native version

"react-native": "0.70.4",

### Platforms

Android

### Workflow

React Native (without Expo)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 5 API 33

### Acknowledgements

Yes

**Comment by MacDinhThanh** [comment]
AAR for react-native-reanimated has been found
/Users/zimdev/work/ZimMobile/node_modules/react-native-reanimated/android/react-native-reanimated-68-jsc.aar

**Comment by advision-andres** [comment]
The same issue happened to me.

I am updating my project dependencies, moving from React Native `0.66.1` to the last version `0.70.5`.
I also updated `react-native-reanimated` to the last version `2.13.0` and during the `./gradlew clean` I got this error.

I first searched for the bug on Sentry's GitHub (Because the crash mentions Sentry as the problem), but I didn't find a similar case... Then I took a look on this GitHub and the problem I'm having seems to be the same as the headline.

```
> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Users/ahernandez/Desktop/Projects/Apps/oddstrader-app/node_modules/react-native-reanimated/android/react-native-reanimated-70-hermes.aar
The AbstractExecTask.execResult property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the executionResult property instead. See https://docs.gradle.org/7.5.1/dsl/org.gradle.api.tasks.AbstractExecTask.html#org.gradle.api.tasks.AbstractExecTask:execResult for more details.
        at sentry_41g27ey0t1d9wv6ufl2kojqjm$_run_closure1$_closure6.doCall(/Users/ahernandez/Desktop/Projects/Apps/oddstrader-app/node_modules/@sentry/react-native/sentry.gradle:42)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

FAILURE: Build failed with an exception.

* Where:
Script '/Users/ahernandez/Desktop/Projects/Apps/oddstrader-app/node_modules/@sentry/react-native/sentry.gradle' line: 166

* What went wrong:
No signature of method: java.util.ArrayList.containsKey() is applicable for argument types: (String) values: [collectModulesScript]
Possible solutions: contains(java.lang.Object), containsAll(java.util.Collection), contains(java.lang.Object), containsAll([Ljava.lang.Object;)
```

**Comment by serkansentilay** [comment]
I'm getting same error for same 
AAR for react-native-reanimated has been found 
...node_modules\react-native-reanimated\android\react-native-reanimated-70-hermes.aar

**Comment by advision-andres** [comment]
**FIXED**

I don't know why the error occurs when `react-native-reanimated` is being compiled, but the error in my case was caused by `@sentry/react-native` and they fixed it in version `4.10.1`.

**Comment by xiehui999** [comment]
+1

**Comment by veeyka** [comment]
./gradlew clean  just fixed it for me

**Comment by alqamabinsadiq** [comment]
Facing the same problem with my project.

Package.json is attached.
```
{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "android:clean": "cd android && ./gradlew clean && cd .. && react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "link-fonts": "react-native link",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "lint:fix": "eslint './app/**/*.{ts,tsx}' --fix",
    "prettier:fix": "prettier 'app/**/*.{js,jsx,ts,tsx,json,md}' --write",
    "prettier:check": "prettier 'app/**/*.{js,jsx,ts,tsx,json,md}' --check",
    "pods": "cd ios && pod install"
  },
  "dependencies": {
    "@gorhom/portal": "^1.0.12",
    "@notifee/react-native": "5.6.0",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/netinfo": "^8.2.0",
    "@react-native-firebase/analytics": "14.11.1",
    "@react-native-firebase/app": "14.11.1",
    "@react-native-firebase/crashlytics": "14.11.1",
    "@react-native-firebase/messaging": "14.11.1",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.2",
    "@shopify/restyle": "^2.1.0",
    "@stripe/stripe-react-native": "0.19.0",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "axios": "^0.26.0",
    "dayjs": "^1.11.6",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-bootsplash": "^4.1.3",
    "react-native-calendars": "1.1289.0",
    "react-native-date-picker": "^4.2.2",
    "react-native-email-link": "^1.13.1",
    "react-native-fast-image": "^8.6.1",
    "react-native-flash-message": "^0.2.1",
    "react-native-geocoding": "^0.5.0",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-hyperlink": "^0.0.19",
    "react-native-image-crop-picker": "^0.37.3",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-keychain": "^8.1.1",
    "react-native-maps": "^1.3.2",
    "react-native-modal": "^13.0.1",
    "react-native-modalize": "^2.0.13",
    "react-native-password-strength-meter": "^0.0.5",
    "react-native-permissions": "^3.3.1",
    "react-native-pinchable": "^0.2.1",
    "react-native-popover-view": "^5.1.6",
    "react-native-qrcode-svg": "^6.1.2",
    "react-native-reanimated": "^2.13.0",
    "react-native-render-html": "^6.3.4",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-styles-shorthand": "^1.0.0",
    "react-native-svg": "^12.3.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-swiper-flatlist": "^3.0.18",
    "react-native-vector-icons": "^9.1.0",
    "react-native-version-info": "^1.1.1",
    "react-native-webview": "^11.23.1",
    "react-redux": "^8.0.5",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "rn-fetch-blob": "^0.12.0"
  },
  "devDependencies": {
    "@babel/core": "^7.19.6",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.1.0",
    "@reduxjs/toolkit": "^1.8.6",
    "@types/jest": "^29.2.0",
    "@types/react-native": "^0.70.6",
    "@types/react-native-vector-icons": "^6.4.12",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.41.0",
    "@typescript-eslint/parser": "^5.41.0",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^29.2.2",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^8.26.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-import-resolver-typescript": "^3.5.2",
    "eslint-plugin-ft-flow": "^2.0.1",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-module-resolver": "^1.5.0",
    "eslint-plugin-no-secrets": "^0.8.9",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-simple-import-sort": "^8.0.0",
    "husky": "^8.0.1",
    "jest": "^29.2.2",
    "lint-staged": "^13.0.3",
    "metro-react-native-babel-preset": "^0.73.3",
    "prettier": "^2.5.1",
    "react-test-renderer": "18.2.0",
    "typescript": "^4.8.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  },
  "lint-staged": {
    "app/*.{ts,tsx}": [
      "yarn prettier:fix",
      "yarn lint"
    ]
  }
}

```

**Comment by Arif-Malik-N** [comment]
I faced the same error but after reading the whole terminal I found assets duplications in android assets.
I simply remove duplicated assets and rebuild the  error fixed  hope it will help someone

**Comment by tinkumahato17** [comment]
I solved..... 

1. npm uni react-native-reanimated
2. delete animated code part from babel config
3. delete node_modules 
4. npm i
5. npm i react-native-reanimated again library add
6. and again add to babel config animated necessary code part
7. go to the android folder
8. ./gradlew clean
9. then cd ..(back to root folder)
10. npm start

**Comment by Astitva877** [comment]
But when i run ./gradlew clean it gets stuck at 55% and not completing 100%?

**Comment by AlexMSantana** [comment]
Alguem pode me ajudar estou com o mesmo erro.
Porem não conseguir fazer esses passos.

**Comment by AlexMSantana** [comment]
> ./gradlew clean

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-camera
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-device
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-eas-client
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-json-utils
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-manifests
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-notifications
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-splash-screen
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-structured-headers
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-updates
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-updates-interface
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo

Using expo modules
  - expo-application (5.1.1)
  - expo-camera (13.2.1)
  - expo-constants (14.2.1)
  - expo-device (5.2.1)
  - expo-eas-client (0.5.1)
  - expo-file-system (15.2.2)
  - expo-font (11.1.1)
  - expo-json-utils (0.5.1)
  - expo-keep-awake (12.0.1)
  - expo-manifests (0.5.2)
  - expo-modules-core (1.2.6)
  - expo-notifications (0.18.1)
  - expo-splash-screen (0.18.1)
  - expo-structured-headers (3.1.1)
  - expo-updates (0.16.4)

WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/Users/alexsantana/AppsProgramas/Lever/app_lever/node_modules/react-native-reanimated/android/react-native-reanimated-71-jsc.aar

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':expo', ':expo-modules-core'

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 14s
31 actionable tasks: 3 executed, 28 up-to-date

**Comment by AlexMSantana** [comment]
Mesmo assim nao gera

**Comment by piaskowyk** [comment]
Hello everyone! 👋 The message `AAR for react-native-reanimated has been found` doesn't mean an error. It means that reanimated will try to build itself from sources. We can't distribute binaries for all react native versions in Reanimated 2 - the package size would be too large.
Sometimes the cause of this problem can be a cache, so in this case, I recommend you to follow this steps:

> 1. npm uni react-native-reanimated
> 2. delete animated code part from babel config
> 3. delete node_modules
> 4. npm i
> 5. npm i react-native-reanimated again library add
> 6. and again add to babel config animated necessary code part
> 7. go to the android folder
> 8. ./gradlew clean
> 9. then cd ..(back to root folder)
> 10. npm start

**Comment by whyamsx** [comment]
I'm getting the same issue now using `react-native-reanimated@2.17.0` and the steps to clear the cache don't help me

**Comment by piaskowyk** [comment]
@whyamsx Is it possible for you to upgrade Reanimated to version 3?

**Comment by VivekCEpic** [comment]
I'm getting the same issue now using react-native-reanimated@2.17.0 and the steps to clear the cache don't help me

**Comment by sandeepvaid** [comment]
I am getting this following error


> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/sandeep/Documents/sita-app/guide-mb/node_modules/react-native-reanimated/android/react-native-reanimated-71-hermes.aar

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':expo-modules-core:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':expo-modules-core:debugCompileClasspath'.
   > Could not resolve com.facebook.fbjni:fbjni:0.5.1.
     Required by:
         project :expo-modules-core
      > Cannot find a version of 'com.facebook.fbjni:fbjni' that satisfies the version constraints:
           Dependency path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.fbjni:fbjni:0.5.1'
           Constraint path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.fbjni:fbjni:{strictly 0.3.0}' because of the following reason: debugRuntimeClasspath uses version 0.3.0
           Dependency path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.react:react-android:0.71.8' (debugVariantDefaultApiPublication) --> 'com.facebook.fbjni:fbjni:0.3.0'

   > Could not resolve com.facebook.fbjni:fbjni:{strictly 0.3.0}.
     Required by:
         project :expo-modules-core
      > Cannot find a version of 'com.facebook.fbjni:fbjni' that satisfies the version constraints:
           Dependency path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.fbjni:fbjni:0.5.1'
           Constraint path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.fbjni:fbjni:{strictly 0.3.0}' because of the following reason: debugRuntimeClasspath uses version 0.3.0
           Dependency path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.react:react-android:0.71.8' (debugVariantDefaultApiPublication) --> 'com.facebook.fbjni:fbjni:0.3.0'

   > Could not resolve com.facebook.fbjni:fbjni:0.3.0.
     Required by:
         project :expo-modules-core > com.facebook.react:react-android:0.71.8
      > Cannot find a version of 'com.facebook.fbjni:fbjni' that satisfies the version constraints:
           Dependency path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.fbjni:fbjni:0.5.1'
           Constraint path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.fbjni:fbjni:{strictly 0.3.0}' because of the following reason: debugRuntimeClasspath uses version 0.3.0
           Dependency path 'host.exp.exponent:expo-modules-core:1.11.9' --> 'com.facebook.react:react-android:0.71.8' (debugVariantDefaultApiPublication) --> 'com.facebook.fbjni:fbjni:0.3.0'


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
10 actionable tasks: 10 up-to-date
Error: /home/sandeep/Documents/sita-app/guide-mb/android/gradlew exited with non-zero code: 1
Error: /home/sandeep/Documents/sita-app/guide-mb/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/home/sandeep/Documents/sita-app/guide-mb/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at Object.spawnAsync [as default] (/home/sandeep/Documents/sita-app/guide-mb/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/home/sandeep/Documents/sita-app/guide-mb/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/home/sandeep/Documents/sita-app/guide-mb/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/home/sandeep/Documents/sita-app/guide-mb/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:36:24)


**I tried every possible solution listed above but was not able to do that**
