### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.uimanager.UIImplementationProvider" on path: DexPathList

### ISSUE THREAD

**Issue by MinaSamir11** [software-mansion/react-native-reanimated#3792]
### Description

app crash after compiling and load bundles 
giving this error->
```
 Failed to create NativeModule "UIManager"
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/uimanager/UIImplementationProvider;
                                                                                                    	at com.swmansion.reanimated.ReanimatedPackage.createUIManager(ReanimatedPackage.java:73)
                                                                                                    	at com.swmansion.reanimated.ReanimatedPackage.getModule(ReanimatedPackage.java:31)
                                                                                                    	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:161)
                                                                                                    	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:149)
                                                                                                    	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
                                                                                                    	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
                                                                                                    	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:170)
                                                                                                    	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:493)
                                                                                                    	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:469)
                                                                                                    	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:89)
                                                                                                    	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:47)
                                                                                                    	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1241)
                                                                                                    	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1183)
                                                                                                    	at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:135)
                                                                                                    	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1137)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:919)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.uimanager.UIImplementationProvider" on path:

```

### Steps to reproduce

1- setup react-native-jitsti 
2- setup reanimate 2.13.1

### Snack or a link to a repository

null

### Reanimated version

2.13.1

### React Native version

0.67.4

### Platforms

Android

### JavaScript runtime

V8

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

API 10 

### Acknowledgements

Yes

**Comment by aarabmed** [comment]
any update on how to resolve this issue , i got it too  :(

**Comment by aarabmed** [comment]
actually , i have been using jdk 17 and when i updated to jdk 19 and did a rebuild , the error disappeared 🤨

**Comment by TwistedMinda** [comment]
When using `react-native": "0.71.3"`, upgrading to react-native-reanimated v3 fixed this crash for me
