### ISSUE TITLE
App started crashing with java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by KarandikarMihir** [software-mansion/react-native-reanimated#3802]
### Description

Our app started crashing unexpectedly since a few days ago. Note the versions mentioned below. We haven't changed anything since a few years, at least 😄 So I'm bamboozled with the error. Halp!

- `react-native-reanimated` version - `1.13.4`
- `react-native` version - `0.63.4`

<details>
  <summary>Stack Trace</summary>

```
11-23 09:39:54.141 12984 12984 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Found class com.facebook.react.uimanager.events.EventDispatcher, but interface was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/~~ZwNrGB2oFwyVH4qbFfm_bQ==/com.udaan.android.debug-RH-q-8M_1rfGSCiw74UZ1w==/base.apk)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:116)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:95)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.swmansion.reanimated.ReanimatedModule.access$000(ReanimatedModule.java:24)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.swmansion.reanimated.ReanimatedModule$1.execute(ReanimatedModule.java:80)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:571)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1088)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-23 09:39:54.141 12984 12984 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
</details>

### Steps to reproduce

1. Open app
2. See error

### Snack or a link to a repository

No link available

### Reanimated version

1.13.4

### React Native version

0.63.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 5

### Acknowledgements

Yes

**Comment by KarandikarMihir** [comment]
Sorry, I can't create a minimal repro - We're not using the library directly in the app. It's a peer dep for react-navigation. And since it's a closed source project, can't share the repo too.

**Comment by SunshineH2** [comment]
missing same problem!!

**Comment by KarandikarMihir** [comment]
So I did this using [patch-package](https://github.com/ds300/patch-package) and it seems to have fixed it for now. Will post more updates if needed.

`node_modules/react-native-reanimated/android/build.gradle` -

```diff
-    implementation 'com.facebook.react:react-native:+'  // From node_modules
+    implementation 'com.facebook.react:react-native:0.63.4'  // From node_modules
```

**Comment by khanhtn91** [comment]
> So I did this using [patch-package](https://github.com/ds300/patch-package) and it seems to have fixed it for now. Will post more updates if needed.
> 
> `node_modules/react-native-reanimated/android/build.gradle` -
> 
> ```diff
> -    implementation 'com.facebook.react:react-native:+'  // From node_modules
> +    implementation 'com.facebook.react:react-native:0.63.4'  // From node_modules
> ```
> 
> **UPDATE:**
> 
> * This is fixed by react-native team. I removed this patch and just upgraded react-native to `0.63.5`.

Thank @KarandikarMihir , that work for me
