### ISSUE TITLE
Attempt to invoke virtual method 'void com.swmansion.reanimated.NativeProxy.performOperations()' on a null object reference

### ISSUE THREAD

**Issue by BloodyMonkey** [software-mansion/react-native-reanimated#3820]
### Description

I upgraded an app from react native 0.61.5 to 0.70.5. and react-native-reanimated from 1.x to 3.x
I get this crash at launch.
New arch but hermes disabled.

Am i forgetting something ?

```
11-30 10:16:55.817 12247 12537 E ReactNativeJS: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
11-30 10:16:55.817 12247 12537 E ReactNativeJS: 
11-30 10:16:55.817 12247 12537 E ReactNativeJS: Check the render method of `MyApp `.
11-30 10:16:55.817 12247 12537 E ReactNativeJS: 
11-30 10:16:55.817 12247 12537 E ReactNativeJS: This error is located at:
11-30 10:16:55.817 12247 12537 E ReactNativeJS:     in MyApp
11-30 10:16:55.817 12247 12537 E ReactNativeJS:     in RCTView (created by View)
11-30 10:16:55.817 12247 12537 E ReactNativeJS:     in View (created by AppContainer)
11-30 10:16:55.817 12247 12537 E ReactNativeJS:     in RCTView (created by View)
11-30 10:16:55.817 12247 12537 E ReactNativeJS:     in View (created by AppContainer)
11-30 10:16:55.817 12247 12537 E ReactNativeJS:     in AppContainer
11-30 10:16:55.817 12247 12537 E ReactNativeJS:     in MyApp(RootComponent)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: Exception in native call
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.swmansion.reanimated.NativeProxy.performOperations()' on a null object reference
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.swmansion.reanimated.NodesManager.performOperations(NodesManager.java:188)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:249)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.swmansion.reanimated.NodesManager.access$000(NodesManager.java:42)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:142)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.os.Looper.loopOnce(Looper.java:201)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:288)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-30 10:17:03.010 12247 12247 E InputEventReceiver: Exception dispatching input event.
11-30 10:17:03.010 12247 12247 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.swmansion.reanimated.NativeProxy.performOperations()' on a null object reference
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.swmansion.reanimated.NodesManager.performOperations(NodesManager.java:188)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:249)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.swmansion.reanimated.NodesManager.access$000(NodesManager.java:42)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:142)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.os.Looper.loopOnce(Looper.java:201)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:288)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-30 10:16:55.917 12247 12247 E unknown:ReactNative: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Steps to reproduce

1. Upgrade existing project from react native 0.61.5 to 0.70.5
2. Upgrade react-native-reanimated from 1.x to 3.X
3. Build debug on Android

### Reanimated version

3.0.0-rc.7

### React Native version

0.70.5

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel 6 Pro API 31

### Acknowledgements

Yes

**Comment by PreetikaSingh** [comment]
Facing this issue with "react-native-reanimated": "^3.0.2", Any luck anyone

**Comment by maestrolsj** [comment]
I have same issue

**Comment by piaskowyk** [comment]
There is no reproduction so we can't help without this. I highly recommend upgrade of Reanimated to the latest version (3.1.0). If this issue is still a problem and someone provides reproduction I will be happy to reopen this issue 😊

**Comment by douglowder** [comment]
@piaskowyk  @tomekzaw This is 100% reproducible with react-native-reanimated 3.4.2 and react-native 0.72.4.

```sh
git clone https://github.com/douglowder/TVInputDemo -b fabric-test
cd TVInputDemo
yarn
yarn android
```

I was attempting to test react-native-reanimated on Android TV and hit this problem, but the above reproduces it on Android phone with the React Native core release.

**Comment by piaskowyk** [comment]
@douglowder thanks for the report! I have prepared fix for that - https://github.com/software-mansion/react-native-reanimated/pull/5016
