### ISSUE TITLE
[v3] Cannot read property '_toConsumableArray' of undefined

### ISSUE THREAD

**Issue by VoVaVc** [software-mansion/react-native-reanimated#4195]
### Description

I'm getting this error when trying to establish a basic slider with `react-native-reanimated-carousel` in android. It looks like the problem is coming from `react-native-reanimated` package:

```
Exception in native call
com.facebook.jni.CppException: Cannot read property '_toConsumableArray' of undefined
TypeError: Cannot read property '_toConsumableArray' of undefined
    at callGuardDEV (worklet_2791860575378:4:5)
	at com.swmansion.reanimated.Scheduler.triggerUI(Native Method)
	at com.swmansion.reanimated.Scheduler$1.run(Scheduler.java:24)
	at com.swmansion.reanimated.Scheduler$2.runGuarded(Scheduler.java:43)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:30)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Steps to reproduce

run an application from the provided repository

### Snack or a link to a repository

https://github.com/VoVaVc/ReactNativeReanimatedArrayBug

### Reanimated version

3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

Pixel_5_API_33

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
Hey, thanks for the report! I have run your application and everything seems to work. I recommend you following steps:
- clear metro cache: `yarn start --reset-cache`
- uninstall the application from the Android device
- clear android studio cache
- compile and run the application again

https://github.com/software-mansion/react-native-reanimated/assets/36106620/9f7d2126-9d58-4a8f-9c2a-7f88fbbef21f
