### ISSUE TITLE
connectAnimatedNodes crash on Android 12

### ISSUE THREAD

**Issue by mmmoussa** [software-mansion/react-native-reanimated#4242]
### Description

Seeing the following stack trace from a production app:
```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: connectAnimatedNodes: Animated node with tag (child) [1503] does not exist
    at com.facebook.react.animated.NativeAnimatedNodesManager.connectAnimatedNodes(NativeAnimatedNodesManager.java:367)
    at com.facebook.react.animated.NativeAnimatedModule$16.execute(NativeAnimatedModule.java:778)
    at com.facebook.react.animated.NativeAnimatedModule$ConcurrentOperationQueue.executeBatch(NativeAnimatedModule.java:173)
    at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:359)
    at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1036)
    at android.view.Choreographer.doCallbacks(Choreographer.java:846)
    at android.view.Choreographer.doFrame(Choreographer.java:776)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1023)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7996)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

All of the crashes are coming from devices running Android 12 and are brands such as Vivo, Infinix, and Realme. I have not been able to reproduce it myself.

### Steps to reproduce

Not sure how to repro, but seems to be an issue with specific brands (eg. Vivo, Infinix, and Realme) on Android 12. The issue exists on both reanimated 2 and reanimated 3.

### Snack or a link to a repository

N/A (private app and not sure how to repro)

### Reanimated version

2.14.4 and 3.0.2

### React Native version

0.71.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by shubhamguptadream11** [comment]
Hey @mmmoussa. We are also getting crash with same logs. We reduced this by applying in react native library file by disabling useNativeDriver: true to false. We applied patch on `@react-navigation/stack` lib which we are using for navigating between screens. We had also replaces instance of `TouchableOpacity` with `Pressable`. By doing this we are able to reduce its instances by more than 50%

**Comment by NimeshMadhushka** [comment]
> Hey! Your issue comes from [React Native Animated](https://reactnative.dev/docs/animated) (`com.facebook.react.animated`). You can try to avoid this issue by using Reanimated, but that means you need to rewrite your animation from Animated to Reanimated API.

Wow. Nice solution. So need to redo the 5-6 month project work... I am getting the same error. project is old about one year.

**Comment by Saad-Bashar** [comment]
> Hey @mmmoussa. We are also getting crash with same logs. We reduced this by applying patch in react native library file by disabling useNativeDriver: true to false. We applied patch on `@react-navigation/stack` lib which we are using for navigating between screens. We had also replaced instance of `TouchableOpacity` [internally it do useNativeDriver: true] with `Pressable`. By doing this we are able to reduce its instances by more than 50%. Hope this helps🙂 We aren't able to repo this yet.

We are also having kind of the same setup. We are using `@react-navigation/stack` and the version is 5. We have not updated to version 6 yet. Do you think migrating to native-stack instead of stack will solve this?

**Comment by alexTamilouski** [comment]
> > Hey @mmmoussa. We are also getting crash with same logs. We reduced this by applying patch in react native library file by disabling useNativeDriver: true to false. We applied patch on `@react-navigation/stack` lib which we are using for navigating between screens. We had also replaced instance of `TouchableOpacity` [internally it do useNativeDriver: true] with `Pressable`. By doing this we are able to reduce its instances by more than 50%. Hope this helps🙂 We aren't able to repo this yet.
> 
> We are also having kind of the same setup. We are using `@react-navigation/stack` and the version is 5. We have not updated to version 6 yet. Do you think migrating to native-stack instead of stack will solve this?

No, We are using react-navigation v6 and come across the same crash.

**Comment by imamrobani** [comment]
still happen, mostly android 12
why this close, has someone fixed it?

**Comment by androidIsForVivek** [comment]
Please help anybody to fix this issue.

**Comment by piaskowyk** [comment]
This issue comes from react native core not from this library

**Comment by cristiano-linvix** [comment]
> This issue comes from react native core not from this library

Do you know exactly where?

**Comment by raajnadar** [comment]
RN Animated should be deprecated so devs don't use buggy API, RN should add this to their official docs of Animated API
