### ISSUE TITLE
`createAnimatedComponent` does not support stateless functional with Jest testing

### ISSUE THREAD

**Issue by Taimoormk** [software-mansion/react-native-reanimated#426]
I am trying to test a very simple React Native app, its an open source project so the full repo can be found at https://github.com/react-pakistan/react-native-boilerplate/tree/RN01-amend

There are 4 jest cases, all 3 are passing except one which can be found here https://github.com/react-pakistan/react-native-boilerplate/blob/RN01-amend/src/__tests__/MainScreen.test.js

It throws an exception as follows;

```
 FAIL  src/__tests__/MainScreen.test.js
  ● Test suite failed to run

    Invariant Violation: `createAnimatedComponent` does not support stateless functional components; use a
 class component instead.

      at invariant (node_modules/invariant/invariant.js:40:15)
      at invariant (node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:20:3)
      at Object.oldCreate [as createAnimatedComponent] (node_modules/react-native/jest/setup.js:143:23)
      at Object.createAnimatedComponent (node_modules/react-navigation-stack/lib/commonjs/views/BorderlessButton.js:1:1230)
      at Object.require (node_modules/react-navigation-stack/lib/commonjs/views/TouchableItem.js:1:1053)
```

Any help would be much appreciated.

**Comment by hyochan** [comment]
Experiencing same thing!

**Comment by Taimoormk** [comment]
Seems like this issue has been resolved and merged now?

**Comment by jakub-gonet** [comment]
Reanimated doesn't support creating animated functional components, because we rely on `forceUpdate`.

The repo link is broken.
