### ISSUE TITLE
Attempt to invoke virtual method 'void com.swmansion.reanimated.NativeProxy.performOperations()' on a null object reference at com.swmansion.reanimated.NodesManager.performOperations(NodesManager.java:188)

### ISSUE THREAD

**Issue by PreetikaSingh** [software-mansion/react-native-reanimated#4269]
### Description

I shifted to the new architecture for react native and also upgraded "react-native-reanimated": "^3.0.2". The build is successful but the app crashes on launch. Here is the full summary:-
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.swmansion.reanimated.NativeProxy.performOperations()' on a null object reference
at com.swmansion.reanimated.NodesManager.performOperations([NodesManager.java:188](http://nodesmanager.java:188/))
at com.swmansion.reanimated.NodesManager.onAnimationFrame([NodesManager.java:249](http://nodesmanager.java:249/))
at com.swmansion.reanimated.NodesManager.access$000([NodesManager.java:42](http://nodesmanager.java:42/))
at com.swmansion.reanimated.NodesManager$1.doFrameGuarded([NodesManager.java:142](http://nodesmanager.java:142/))
at com.facebook.react.uimanager.GuardedFrameCallback.doFrame([GuardedFrameCallback.java:29](http://guardedframecallback.java:29/))
at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame([ReactChoreographer.java:175](http://reactchoreographer.java:175/))
at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame([ChoreographerCompat.java:85](http://choreographercompat.java:85/))
at android.view.Choreographer$[CallbackRecord.run](http://callbackrecord.run/)([Choreographer.java:1127](http://choreographer.java:1127/))
at android.view.Choreographer.doCallbacks([Choreographer.java:926](http://choreographer.java:926/))
at android.view.Choreographer.doFrame([Choreographer.java:835](http://choreographer.java:835/))
at android.view.Choreographer$[FrameDisplayEventReceiver.run](http://framedisplayeventreceiver.run/)([Choreographer.java:1114](http://choreographer.java:1114/))
at android.os.Handler.handleCallback([Handler.java:938](http://handler.java:938/))
at android.os.Handler.dispatchMessage([Handler.java:99](http://handler.java:99/))
at android.os.Looper.loopOnce([Looper.java:210](http://looper.java:210/))
at android.os.Looper.loop([Looper.java:299](http://looper.java:299/))
at [android.app](http://android.app/).ActivityThread.main([ActivityThread.java:8298](http://activitythread.java:8298/))
at java.lang.reflect.Method.invoke(Native Method)
at [com.android](http://com.android/).internal.os.RuntimeInit$[MethodAndArgsCaller.run](http://methodandargscaller.run/)([RuntimeInit.java:576](http://runtimeinit.java:576/))
at [com.android](http://com.android/).internal.os.ZygoteInit.main([ZygoteInit.java:1073](http://zygoteinit.java:1073/))
has context menu
```

### Steps to reproduce

1. Upgraded "react-native-reanimated": "^3.0.2"
2. Run the build - npx react-native run-android
3. App crashing on launch with the error.

### Snack or a link to a repository

https://stackoverflow.com/questions/75822525/react-native-new-arch-attempt-to-invoke-virtual-method-void-com-swmansion-rean

### Reanimated version

3.0.2

### React Native version

0.71.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo bare workflow

### Architecture

None

### Build type

Release mode

### Device

Real device

### Acknowledgements

Yes

**Comment by abdullahIsa** [comment]
Same here too, updated to the latest build ok but on launching the app shows the error, any fix ?

**Comment by Latropos** [comment]
Duplicate of #3820

**Comment by piaskowyk** [comment]
Because this is duplicate, I will close this issue to keep discussion in the one place.
