### ISSUE TITLE
Web implementation doesn't work in react-native-web 0.19

### ISSUE THREAD

**Issue by janlat** [software-mansion/react-native-reanimated#4335]
### Description

`setNativeProps` method was removed in [react-native-web 0.19](https://github.com/necolas/react-native-web/releases/tag/0.19.0)

Related discussion: https://github.com/software-mansion/react-native-reanimated/discussions/2756

### Steps to reproduce

-

### Snack or a link to a repository

-

### Reanimated version

-

### React Native version

-

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by chrisedington** [comment]
I'm having the same problem. 

RN 0.69.9
RNW 0.19.2

```babel webpack config:```
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['inline-react-svg', '@babel/plugin-proposal-export-namespace-from', 'react-native-reanimated/plugin'],
};
```

```Error Output```
```
AnimatedTransform.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at AnimatedTransform.__attach (AnimatedTransform.js:69:22)
    at AnimatedTransform.__addChild (AnimatedWithChildren.js:41:12)
    at AnimatedStyle.__attach (AnimatedStyle.js:95:15)
    at AnimatedStyle.__addChild (AnimatedWithChildren.js:41:12)
    at AnimatedProps.__attach (AnimatedProps.js:74:15)
    at new AnimatedProps (AnimatedProps.js:40:10)
    at eval (useAnimatedProps.js:39:67)
    at mountMemo (react-dom.development.js:17057:19)
    at Object.useMemo (react-dom.development.js:17517:16)
    at useMemo (react.development.js:1646:21)
__attach @ AnimatedTransform.js:69
__addChild @ AnimatedWithChildren.js:41
__attach @ AnimatedStyle.js:95
__addChild @ AnimatedWithChildren.js:41
__attach @ AnimatedProps.js:74
AnimatedProps @ AnimatedProps.js:40
eval @ useAnimatedProps.js:39
mountMemo @ react-dom.development.js:17057
useMemo @ react-dom.development.js:17517
useMemo @ react.development.js:1646
useAnimatedProps @ useAnimatedProps.js:39
eval @ createAnimatedComponent.js:35
renderWithHooks @ react-dom.development.js:16141
updateForwardRef @ react-dom.development.js:19963
beginWork @ react-dom.development.js:22386
callCallback @ react-dom.development.js:4157
invokeGuardedCallbackDev @ react-dom.development.js:4206
invokeGuardedCallback @ react-dom.development.js:4270
beginWork$1 @ react-dom.development.js:27238
performUnitOfWork @ react-dom.development.js:26387
workLoopSync @ react-dom.development.js:26298
renderRootSync @ react-dom.development.js:26266
performConcurrentWorkOnRoot @ react-dom.development.js:25572
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
module.exports @ _invoke.js:1
queue.<computed> @ _task.js:1
run @ _task.js:1
listener @ _task.js:1
AnimatedTransform.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at AnimatedTransform.__attach (AnimatedTransform.js:69:22)
    at AnimatedTransform.__addChild (AnimatedWithChildren.js:41:12)
    at AnimatedStyle.__attach (AnimatedStyle.js:95:15)
    at AnimatedStyle.__addChild (AnimatedWithChildren.js:41:12)
    at AnimatedProps.__attach (AnimatedProps.js:74:15)
    at new AnimatedProps (AnimatedProps.js:40:10)
    at eval (useAnimatedProps.js:39:67)
    at mountMemo (react-dom.development.js:17057:19)
    at Object.useMemo (react-dom.development.js:17517:16)
    at useMemo (react.development.js:1646:21)react-dom.development.js:18525 
    
The above error occurred in the <ForwardRef> component:

    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
    at Header (webpack://shopstarlive/./node_modules/@react-navigation/stack/node_modules/@react-navigation/elements/lib/module/Header/Header.js?:1:3897)
    at HeaderSegment (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Header/HeaderSegment.js?:1:2986)
    at Header (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Header/Header.js?:1:2718)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
    at HeaderContainer (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Header/HeaderContainer.js?:1:2182)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at CardSheet (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/CardSheet.js?:1:2258)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
    at Dummy (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/GestureHandler.js?:1:1421)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at Card (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/Card.js?:1:6754)
    at CardContainer (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/CardContainer.js?:1:2548)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at NativeScreen (webpack://shopstarlive/./node_modules/react-native-screens/lib/module/index.js?:1:5498)
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
    at MaybeScreen (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Screens.js?:1:2617)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at MaybeScreenContainer (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Screens.js?:1:2281)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at Background (webpack://shopstarlive/./node_modules/@react-navigation/stack/node_modules/@react-navigation/elements/lib/module/Background.js?:1:2169)
    at CardStack (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/CardStack.js?:1:8369)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at SafeAreaProviderCompat (webpack://shopstarlive/./node_modules/@react-navigation/stack/node_modules/@react-navigation/elements/lib/module/SafeAreaProviderCompat.js?:1:2054)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at StackView (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/StackView.js?:1:6191)
    at PreventRemoveProvider (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/PreventRemoveProvider.js?:1:3210)
    at NavigationContent (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/useComponent.js?:1:1284)
    at eval (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/useComponent.js?:1:1538)
    at StackNavigator (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/navigators/createStackNavigator.js?:1:2402)
    at EnsureSingleNavigator (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/EnsureSingleNavigator.js?:1:1755)
    at BaseNavigationContainer (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/BaseNavigationContainer.js?:1:6067)
    at ThemeProvider (webpack://shopstarlive/./node_modules/@react-navigation/native/lib/module/theming/ThemeProvider.js?:1:1585)
    at NavigationContainerInner (webpack://shopstarlive/./node_modules/@react-navigation/native/lib/module/NavigationContainer.js?:1:3516)
    at Routes (webpack://shopstarlive/./src/navigation/Routes.web.js?:1:6575)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at NativeSafeAreaProvider (webpack://shopstarlive/./node_modules/react-native-safe-area-context/lib/module/NativeSafeAreaProvider.web.js?:28:5)
    at SafeAreaProvider (webpack://shopstarlive/./node_modules/react-native-safe-area-context/lib/module/SafeAreaContext.js?:38:5)
    at Provider (webpack://shopstarlive/./node_modules/react-redux/es/components/Provider.js?:19:20)
    at App (webpack://shopstarlive/./App.web.js?:1:4416)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at div
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
    at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/AppRegistry/AppContainer.js?:24:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18525
update.callback @ react-dom.development.js:18553
callCallback @ react-dom.development.js:13092
commitUpdateQueue @ react-dom.development.js:13113
commitLayoutEffectOnFiber @ react-dom.development.js:23199
commitLayoutMountEffects_complete @ react-dom.development.js:24456
commitLayoutEffects_begin @ react-dom.development.js:24442
commitLayoutEffects @ react-dom.development.js:24380
commitRootImpl @ react-dom.development.js:26646
commitRoot @ react-dom.development.js:26512
finishConcurrentRender @ react-dom.development.js:25726
performConcurrentWorkOnRoot @ react-dom.development.js:25643
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
module.exports @ _invoke.js:1
queue.<computed> @ _task.js:1
run @ _task.js:1
listener @ _task.js:1
react-dom.development.js:26735 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at AnimatedTransform.__attach (AnimatedTransform.js:69:22)
    at AnimatedTransform.__addChild (AnimatedWithChildren.js:41:12)
    at AnimatedStyle.__attach (AnimatedStyle.js:95:15)
    at AnimatedStyle.__addChild (AnimatedWithChildren.js:41:12)
    at AnimatedProps.__attach (AnimatedProps.js:74:15)
    at new AnimatedProps (AnimatedProps.js:40:10)
    at eval (useAnimatedProps.js:39:67)
    at mountMemo (react-dom.development.js:17057:19)
    at Object.useMemo (react-dom.development.js:17517:16)
    at useMemo (react.development.js:1646:21)
```

**Comment by agusvazquez** [comment]
same here

```
dex.js:15 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _updatePropsJS (index.js:15:25)
    at UpdateProps.js:29:31
    at Set.forEach (<anonymous>)
    at _f (UpdateProps.js:28:32)
    at _f (useAnimatedStyle.js:170:24)
    at Mapper._f [as mapper] (useAnimatedStyle.js:368:17)
    at Mapper.execute (Mapper.js:19:14)
    at MapperRegistry.execute (MapperRegistry.js:25:24)
    at JSReanimated._onRender (JSReanimated.js:37:30)
_
```

**Comment by pencilcheck** [comment]
This is breaking Moti as well

**Comment by tomekzaw** [comment]
Should be fixed with https://github.com/software-mansion/react-native-reanimated/pull/4352, feedback is welcome!

**Comment by Prithiviraj-Rajkumar** [comment]
> I'm having the same problem.
> 
> RN 0.69.9 RNW 0.19.2
> 
> `babel webpack config:`
> 
> ```
> module.exports = {
>   presets: ['module:metro-react-native-babel-preset'],
>   plugins: ['inline-react-svg', '@babel/plugin-proposal-export-namespace-from', 'react-native-reanimated/plugin'],
> };
> ```
> 
> `Error Output`
> 
> ```
> AnimatedTransform.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
>     at AnimatedTransform.__attach (AnimatedTransform.js:69:22)
>     at AnimatedTransform.__addChild (AnimatedWithChildren.js:41:12)
>     at AnimatedStyle.__attach (AnimatedStyle.js:95:15)
>     at AnimatedStyle.__addChild (AnimatedWithChildren.js:41:12)
>     at AnimatedProps.__attach (AnimatedProps.js:74:15)
>     at new AnimatedProps (AnimatedProps.js:40:10)
>     at eval (useAnimatedProps.js:39:67)
>     at mountMemo (react-dom.development.js:17057:19)
>     at Object.useMemo (react-dom.development.js:17517:16)
>     at useMemo (react.development.js:1646:21)
> __attach @ AnimatedTransform.js:69
> __addChild @ AnimatedWithChildren.js:41
> __attach @ AnimatedStyle.js:95
> __addChild @ AnimatedWithChildren.js:41
> __attach @ AnimatedProps.js:74
> AnimatedProps @ AnimatedProps.js:40
> eval @ useAnimatedProps.js:39
> mountMemo @ react-dom.development.js:17057
> useMemo @ react-dom.development.js:17517
> useMemo @ react.development.js:1646
> useAnimatedProps @ useAnimatedProps.js:39
> eval @ createAnimatedComponent.js:35
> renderWithHooks @ react-dom.development.js:16141
> updateForwardRef @ react-dom.development.js:19963
> beginWork @ react-dom.development.js:22386
> callCallback @ react-dom.development.js:4157
> invokeGuardedCallbackDev @ react-dom.development.js:4206
> invokeGuardedCallback @ react-dom.development.js:4270
> beginWork$1 @ react-dom.development.js:27238
> performUnitOfWork @ react-dom.development.js:26387
> workLoopSync @ react-dom.development.js:26298
> renderRootSync @ react-dom.development.js:26266
> performConcurrentWorkOnRoot @ react-dom.development.js:25572
> workLoop @ scheduler.development.js:266
> flushWork @ scheduler.development.js:239
> performWorkUntilDeadline @ scheduler.development.js:533
> module.exports @ _invoke.js:1
> queue.<computed> @ _task.js:1
> run @ _task.js:1
> listener @ _task.js:1
> AnimatedTransform.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
>     at AnimatedTransform.__attach (AnimatedTransform.js:69:22)
>     at AnimatedTransform.__addChild (AnimatedWithChildren.js:41:12)
>     at AnimatedStyle.__attach (AnimatedStyle.js:95:15)
>     at AnimatedStyle.__addChild (AnimatedWithChildren.js:41:12)
>     at AnimatedProps.__attach (AnimatedProps.js:74:15)
>     at new AnimatedProps (AnimatedProps.js:40:10)
>     at eval (useAnimatedProps.js:39:67)
>     at mountMemo (react-dom.development.js:17057:19)
>     at Object.useMemo (react-dom.development.js:17517:16)
>     at useMemo (react.development.js:1646:21)react-dom.development.js:18525 
>     
> The above error occurred in the <ForwardRef> component:
> 
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
>     at Header (webpack://shopstarlive/./node_modules/@react-navigation/stack/node_modules/@react-navigation/elements/lib/module/Header/Header.js?:1:3897)
>     at HeaderSegment (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Header/HeaderSegment.js?:1:2986)
>     at Header (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Header/Header.js?:1:2718)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
>     at HeaderContainer (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Header/HeaderContainer.js?:1:2182)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at CardSheet (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/CardSheet.js?:1:2258)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
>     at Dummy (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/GestureHandler.js?:1:1421)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at Card (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/Card.js?:1:6754)
>     at CardContainer (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/CardContainer.js?:1:2548)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at NativeScreen (webpack://shopstarlive/./node_modules/react-native-screens/lib/module/index.js?:1:5498)
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js?:35:90)
>     at MaybeScreen (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Screens.js?:1:2617)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at MaybeScreenContainer (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Screens.js?:1:2281)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at Background (webpack://shopstarlive/./node_modules/@react-navigation/stack/node_modules/@react-navigation/elements/lib/module/Background.js?:1:2169)
>     at CardStack (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/CardStack.js?:1:8369)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at SafeAreaProviderCompat (webpack://shopstarlive/./node_modules/@react-navigation/stack/node_modules/@react-navigation/elements/lib/module/SafeAreaProviderCompat.js?:1:2054)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at StackView (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/views/Stack/StackView.js?:1:6191)
>     at PreventRemoveProvider (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/PreventRemoveProvider.js?:1:3210)
>     at NavigationContent (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/useComponent.js?:1:1284)
>     at eval (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/useComponent.js?:1:1538)
>     at StackNavigator (webpack://shopstarlive/./node_modules/@react-navigation/stack/lib/module/navigators/createStackNavigator.js?:1:2402)
>     at EnsureSingleNavigator (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/EnsureSingleNavigator.js?:1:1755)
>     at BaseNavigationContainer (webpack://shopstarlive/./node_modules/@react-navigation/native/node_modules/@react-navigation/core/lib/module/BaseNavigationContainer.js?:1:6067)
>     at ThemeProvider (webpack://shopstarlive/./node_modules/@react-navigation/native/lib/module/theming/ThemeProvider.js?:1:1585)
>     at NavigationContainerInner (webpack://shopstarlive/./node_modules/@react-navigation/native/lib/module/NavigationContainer.js?:1:3516)
>     at Routes (webpack://shopstarlive/./src/navigation/Routes.web.js?:1:6575)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at NativeSafeAreaProvider (webpack://shopstarlive/./node_modules/react-native-safe-area-context/lib/module/NativeSafeAreaProvider.web.js?:28:5)
>     at SafeAreaProvider (webpack://shopstarlive/./node_modules/react-native-safe-area-context/lib/module/SafeAreaContext.js?:38:5)
>     at Provider (webpack://shopstarlive/./node_modules/react-redux/es/components/Provider.js?:19:20)
>     at App (webpack://shopstarlive/./App.web.js?:1:4416)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at div
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/View/index.js?:50:25)
>     at eval (webpack://shopstarlive/./node_modules/react-native-web/dist/exports/AppRegistry/AppContainer.js?:24:24)
> 
> Consider adding an error boundary to your tree to customize error handling behavior.
> Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
> logCapturedError @ react-dom.development.js:18525
> update.callback @ react-dom.development.js:18553
> callCallback @ react-dom.development.js:13092
> commitUpdateQueue @ react-dom.development.js:13113
> commitLayoutEffectOnFiber @ react-dom.development.js:23199
> commitLayoutMountEffects_complete @ react-dom.development.js:24456
> commitLayoutEffects_begin @ react-dom.development.js:24442
> commitLayoutEffects @ react-dom.development.js:24380
> commitRootImpl @ react-dom.development.js:26646
> commitRoot @ react-dom.development.js:26512
> finishConcurrentRender @ react-dom.development.js:25726
> performConcurrentWorkOnRoot @ react-dom.development.js:25643
> workLoop @ scheduler.development.js:266
> flushWork @ scheduler.development.js:239
> performWorkUntilDeadline @ scheduler.development.js:533
> module.exports @ _invoke.js:1
> queue.<computed> @ _task.js:1
> run @ _task.js:1
> listener @ _task.js:1
> react-dom.development.js:26735 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
>     at AnimatedTransform.__attach (AnimatedTransform.js:69:22)
>     at AnimatedTransform.__addChild (AnimatedWithChildren.js:41:12)
>     at AnimatedStyle.__attach (AnimatedStyle.js:95:15)
>     at AnimatedStyle.__addChild (AnimatedWithChildren.js:41:12)
>     at AnimatedProps.__attach (AnimatedProps.js:74:15)
>     at new AnimatedProps (AnimatedProps.js:40:10)
>     at eval (useAnimatedProps.js:39:67)
>     at mountMemo (react-dom.development.js:17057:19)
>     at Object.useMemo (react-dom.development.js:17517:16)
>     at useMemo (react.development.js:1646:21)
> ```

i am also facing the same issue , did you get any fix  for this

**Comment by chrisedington** [comment]
No @Prithiviraj-Rajkumar not yet - please feedback here if you solve it 🙏 I'll do the same

**Comment by juanlarra1** [comment]
> No @Prithiviraj-Rajkumar not yet - please feedback here if you solve it 🙏 I'll do the same

the only thing that worked for me was downgrading react-native-web to 0.18
