### ISSUE TITLE
Execution failed for task react-native-reanimated:generateJsonModelDebug

### ISSUE THREAD

**Issue by Mmec45** [software-mansion/react-native-reanimated#4428]
### Description

An old version of CMake is being used that cannot automatically detect compiler attributes.  Compiler identification is being bypassed.  Some values may be wrong or missing.  Update to CMake 3.19 or newer to use CMake's built-in compiler identification.

### Steps to reproduce

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 4.1.0
Gradle: 6.7

> Configure project :realm

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-pager-view', ':react-native-screens'

> Task :react-native-reanimated:downloadBoost UP-TO-DATE
Download https://github.com/react-native-community/boost-for-react-native/releases/download/v1.63.0-0/boost_1_63_0.tar.gz

> Task :react-native-reanimated:downloadDoubleConversion UP-TO-DATE
Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz

> Task :react-native-reanimated:downloadFolly UP-TO-DATE
Download https://github.com/facebook/folly/archive/v2020.01.13.00.tar.gz

> Task :react-native-reanimated:downloadGlog UP-TO-DATE
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :react-native-reanimated:generateJsonModelDebug
E:\GITHUB\Markpedia_mobile\node_modules\react-native-reanimated\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
  C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:1 (project)

E:\GITHUB\Markpedia_mobile\node_modules\react-native-reanimated\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
  C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:1 (project)

E:\GITHUB\Markpedia_mobile\node_modules\react-native-reanimated\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
  E:/GITHUB/Markpedia_mobile/node_modules/react-native-reanimated/android/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  E:/GITHUB/Markpedia_mobile/node_modules/react-native-reanimated/android/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

E:\GITHUB\Markpedia_mobile\node_modules\react-native-reanimated\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Warning at C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android-legacy.toolchain.cmake:416 (message):
  An old version of CMake is being used that cannot automatically detect
  compiler attributes.  Compiler identification is being bypassed.  Some
  values may be wrong or missing.  Update to CMake 3.19 or newer to use
  CMake's built-in compiler identification.
Call Stack (most recent call first):
  C:/Users/MARKPEDIA/AppData/Local/Android/Sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake:55 (include)
  E:/GITHUB/Markpedia_mobile/node_modules/react-native-reanimated/android/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/3.10.2/CMakeSystem.cmake:6 (include)
  E:/GITHUB/Markpedia_mobile/node_modules/react-native-reanimated/android/.cxx/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

> Task :react-native-reanimated:generateJsonModelDebug FAILED
236 actionable tasks: 8 executed, 228 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:generateJsonModelDebug'.
> E:\GITHUB\Markpedia_mobile\node_modules\react-native-reanimated\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at E:\GITHUB\Markpedia_mobile\node_modules\react-native-reanimated\android\CMakeLists.txt:61 (add_library):
    Syntax error in cmake code when parsing string

      E:\GITHUB\Markpedia_mobile\node_modules\react-native/ReactCommon/jsi/jsi/jsi.cpp

    Invalid character escape '\G'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 39s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:generateJsonModelDebug'.
> E:\GITHUB\Markpedia_mobile\node_modules\react-native-reanimated\android\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at E:\GITHUB\Markpedia_mobile\node_modules\react-native-reanimated\android\CMakeLists.txt:61 (add_library):
    Syntax error in cmake code when parsing string

      E:\GITHUB\Markpedia_mobile\node_modules\react-native/ReactCommon/jsi/jsi/jsi.cpp

    Invalid character escape '\G'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 39s

    at makeError (E:\GITHUB\Markpedia_mobile\node_modules\execa\index.js:174:9)
    at E:\GITHUB\Markpedia_mobile\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (E:\GITHUB\Markpedia_mobile\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (E:\GITHUB\Markpedia_mobile\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! markpedia@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the markpedia@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MARKPEDIA\AppData\Roaming\npm-cache\_logs\2023-05-04T17_06_45_976Z-debug.log

### Snack or a link to a repository

https://snack.expo.io/

### Reanimated version

2.12.0

### React Native version

0.60.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by Mmec45** [comment]
It was necessary to uninstall a third-party dependency in package.json

**Comment by leoderigo** [comment]
@Mmec45 Did you fixed the error? I'm having the same problem with that ndk
