### ISSUE TITLE
app crashed when I use react native reanimated and react-native-gesture-handler

### ISSUE THREAD

**Issue by AzadMohammadi-z** [software-mansion/react-native-reanimated#4598]
### Description

when I install and import react native gesture handler in index.js my app crashed

### Steps to reproduce

  "react-native": "0.70.6",
"react-native-gesture-handler": "^2.9.0",
  "react-native-reanimated": "2.17.0",
       buildToolsVersion = "33.0.1"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

### Snack or a link to a repository

https://github.com/AzadMohammadi-z/optimaPlus

### Reanimated version

2.9.0

### React Native version

0.70.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

None

### Device

Android emulator

### Device model

Anroid 12

### Acknowledgements

Yes

**Comment by AlanWen2016** [comment]
same issue

**Comment by AzadMohammadi-z** [comment]
my logcat

android.content.pm.PackageManager$NameNotFoundException: com.optimaplus
2023-06-21 09:53:15.465  1804-12425 PackageManager          system_server                        D  Uninstall pkg: com.optimaplus u0 flags:4 from u10055/14991 of com.miui.home
2023-06-21 09:53:15.467 14991-15191 Launcher.LauncherUtils  com.miui.home                        D  app(com.optimaplus|UserHandle{0}) isDisable=false, backupProcessingPkg=null
2023-06-21 09:53:15.468 14991-15191 AutoInstallsParser      com.miui.home                        D  isPAIPackageName: com.optimaplus
2023-06-21 09:53:15.472  1804-2188  ActivityManager         system_server                        I  Force stopping com.optimaplus appid=10554 user=0: deletePackageX
2023-06-21 09:53:15.474  1804-2406  AppsFilter              system_server                        I  interaction: PackageSetting{b564db8 com.skill/10443} -> PackageSetting{1870823 com.optimaplus/10554} BLOCKED
2023-06-21 09:53:15.474  1804-2406  AppsFilter              system_server                        I  interaction: PackageSetting{ef43af7 com.fido.asm/10117} -> PackageSetting{1870823 com.optimaplus/10554} BLOCKED
2023-06-21 09:53:15.474  1804-2406  AppsFilter              system_server                        I  interaction: PackageSetting{9fe8d64 com.kanzexapp/10449} -> PackageSetting{1870823 com.optimaplus/10554} BLOCKED
2023-06-21 09:53:15.489 14991-15191 Launcher.Model          com.miui.home                        D  onReceiveBackground, mAllAppsList=add=[], remove=[(0, AppInfo, id=-1, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.optimaplus, className=com.optimaplus.MainActivity, screenId=-1, container=-1, cellX=-1, cellY=-1, spanX=1, spanY=1)], modified=[]
2023-06-21 09:53:15.490 14991-14991 Launcher                com.miui.home                        D  remove icon when bind apps removed:ShortcutInfo, id=430, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.optimaplus, className=com.optimaplus.MainActivity, screenId=1, container=-100, cellX=3, cellY=5, spanX=1, spanY=1
2023-06-21 09:53:15.490 14991-14991 Launcher.CellLayout     com.miui.home                        D  remove icon for ShortcutInfo, id=430, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.optimaplus, className=com.optimaplus.MainActivity, screenId=1, container=-100, cellX=3, cellY=5, spanX=1, spanY=1
2023-06-21 09:53:15.490 14991-14991 Launcher.CellLayout     com.miui.home                        D  updateCellOccupiedMarks, remove, ShortcutInfo, id=430, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.optimaplus, className=com.optimaplus.MainActivity, screenId=1, container=-100, cellX=3, cellY=5, spanX=1, spanY=1
2023-06-21 09:53:15.490 14991-14991 Launcher                com.miui.home                        D  removeShortcutIcon, info=(ShortcutInfo, id=430, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.optimaplus, className=com.optimaplus.MainActivity, screenId=1, container=-100, cellX=3, cellY=5, spanX=1, spanY=1), removeFromDB=true
2023-06-21 09:53:15.490 14991-14991 Launcher.Model          com.miui.home                        D  deleteItemFromDatabase, item=ShortcutInfo, id=430, itemType=0, user=UserHandle{0}, mIconType=0, pkgName=com.optimaplus, className=com.optimaplus.MainActivity, screenId=1, container=-100, cellX=3, cellY=5, spanX=1, spanY=1
2023-06-21 09:53:15.498  1804-2406  PackageManager          system_server                        I  Removing permission com.optimaplus.permission.C2D_MESSAGE that used to be declared by com.optimaplus
2023-06-21 09:53:15.641  1804-2406  PackageFreezer          system_server                        W  Freeze package com.optimaplus about 0.169 seconds for reason: deletePackageX
2023-06-21 09:53:15.685  1804-2406  ActivityManager         system_server                        I  Force stopping com.optimaplus appid=10554 user=0: pkg removed
2023-06-21 09:53:16.059  1804-2623  WifiService             system_server                        W  Couldn't get PackageInfo for package:com.optimaplus
2023-06-21 09:53:16.059  1804-2623  WifiService             system_server                        D  Remove settings for package:com.optimaplus
2023-06-21 09:53:16.059  1804-2623  WifiConfigManager       system_server                        D  Remove all networks for app ApplicationInfo{2061dbf com.optimaplus}
2023-06-21 09:53:16.062  1804-2622  MiuiNetwor...AppBuckets system_server                        D  updateAppPN packageName=com.optimaplus,uid=10554,installed=false
2023-06-21 09:53:16.068  3359-3840  QSTileHost              com.android.systemui                 E  PackageManager Error:com.optimaplus
2023-06-21 09:53:16.068  3359-3666  NotificationProvider    com.android.systemui                 D  call method=clearPkgUsageInfoWhenRemoved extras=Bundle[{packageName=com.optimaplus}]
2023-06-21 09:53:16.071  5270-5270  SLM-SRV-SLAAppLib       com.xiaomi.NetworkBoost              E  initBroadcastReceivercom.optimaplus
2023-06-21 09:53:16.071  5270-5270  SLM-SRV-SLAAppLib       com.xiaomi.NetworkBoost              I  ACTION_PACKAGE_REMOVED uid = 10554com.optimaplus
2023-06-21 09:53:16.072  3333-3333  CarrierSvcBindHelper    com.android.phone                    D  onPackageRemoved: com.optimaplus
2023-06-21 09:53:16.073 14991-15094 InstallApkReceiver      com.miui.home                        E  uninstall:package:com.optimaplus
2023-06-21 09:53:16.074 15363-15363 InstalledAppMonitor     com.miui.securitycenter.remote       I  com.optimaplusonReceive remove pkg=com.optimaplus
2023-06-21 09:53:16.076  1804-2558  RollbackManager         system_server                        I  broadcast=ACTION_PACKAGE_FULLY_REMOVED pkg=com.optimaplus
2023-06-21 09:53:16.082 12531-12531 Finsky                  com.android.vending                  I  [2] vnb.t(8): Package no longer installed: com.optimaplus
2023-06-21 09:53:16.093  1804-1804  GameManagerService      system_server                        I  Disabling downscale for com.optimaplus
2023-06-21 09:53:16.095  1804-2623  PasspointManager        system_server                        I  No app ops listener found for com.optimaplus
2023-06-21 09:53:16.095  1804-2623  WifiService             system_server                        W  Couldn't get PackageInfo for package:com.optimaplus
2023-06-21 09:53:16.095  1804-2623  WifiService             system_server                        D  Remove settings for package:com.optimaplus
2023-06-21 09:53:16.095  1804-2623  WifiConfigManager       system_server                        D  Remove all networks for app ApplicationInfo{2eaf1f0 com.optimaplus}
2023-06-21 09:53:16.114 12531-12531 Finsky                  com.android.vending                  I  [2] vnb.t(8): Package no longer installed: com.optimaplus
2023-06-21 09:53:16.123 12531-9023  Finsky                  com.android.vending                  I  [86470] ax.a(5): Asset module storage cleared for package com.optimaplus.
2023-06-21 09:53:16.132  5230-11161 SQLiteLog               com.qualcomm.qti.workloadclassifier  W  (28) double-quoted string literal: "com.optimaplus"
2023-06-21 09:53:16.134 13152-8868  ProximityAuth           com.google.android.gms.persistent    I  [RecentAppsMediator] Package removed: (user=UserHandle{0}) com.optimaplus
2023-06-21 09:53:16.148 12531-12531 Finsky                  com.android.vending                  I  [2] jix.f(1): AIM: AppInfoCacheUpdater -> invalidating apps: [com.optimaplus]
2023-06-21 09:53:16.152 12531-8747  Finsky                  com.android.vending                  I  [85543] jku.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.optimaplus]
2023-06-21 09:53:16.153  1804-1804  Telecom                 system_server                        I  CarModeTracker: Package com.optimaplus is not tracked.: SSH.oR@2lw
2023-06-21 09:53:16.155  1804-1804  ConditionProviders      system_server                        I  Disallowing condition provider com.optimaplus (userSet: true)
2023-06-21 09:53:16.171 12531-12531 Finsky                  com.android.vending                  W  [2] aadu.b(12): STU: Failed to get storage stats for package 'com.optimaplus' (1601: Error getting stats: android.content.pm.PackageManager.NameNotFoundException)
2023-06-21 09:53:16.261 20432-18717 Icing                   com.google.android.gms               I  doRemovePackageData com.optimaplus
2023-06-21 09:53:16.286  1804-2623  PasspointManager        system_server                        I  No app ops listener found for com.optimaplus
2023-06-21 09:53:16.341 20432-8881  SQLiteLog               com.google.android.gms               W  (28) double-quoted string literal: "com.optimaplus"
2023-06-21 09:53:16.667 14991-14991 Launcher.Model          com.miui.home                        D  LauncherAppsCallback onPackageRemoved|com.optimaplus|UserHandle{0}
2023-06-21 09:53:16.676 14991-15191 AutoInstallsParser      com.miui.home                        D  isPAIPackageName: com.optimaplus
2023-06-21 09:53:16.743 12531-12531 Finsky                  com.android.vending                  I  [2] vnb.t(8): Package no longer installed: com.optimaplus
2023-06-21 09:53:16.827  9059-9147  ResidentChecker         com.miui.cleaner                     I  check: StartScan pkg=com.optimaplus
2023-06-21 09:53:18.701 28463-28463 PersistedS...edReceiver com....android.permissioncontroller  D  Received android.intent.action.PACKAGE_FULLY_REMOVED for com.optimaplus for u0
2023-06-21 09:53:18.718  4933-5837  MediaProvider           com...ndroid.providers.media.module  D  Deleted 0 Android/media items belonging to com.optimaplus on /data/user/0/com.google.android.providers.media.module/databases/external.db
2023-06-21 09:53:18.720  4933-5837  MediaGrants             com...ndroid.providers.media.module  D  Removed 0 media_grants for com.optimaplus. Reason: Package orphaned
2023-06-21 09:57:35.467  1804-5743  ActivityManager         system_server                        W  Invalid packageName: com.optimaplus
2023-06-21 09:57:35.929 10471-10471 studio.deploy           installer                            E  Could not get package user id: run-as: unknown package: com.optimaplus
2023-06-21 09:57:35.938 10471-10471 studio.deploy           installer                            E  Could not find apks for this package: com.optimaplus
2023-06-21 09:57:35.994 10471-10471 studio.deploy           installer                            E  Could not get package user id: run-as: unknown package: com.optimaplus
2023-06-21 09:57:36.003 10471-10471 studio.deploy           installer                            E  Could not find apks for this package: com.optimaplus
2023-06-21 09:57:37.652 12531-12531 Finsky                  com.android.vending                  I  [2] afyz.c(8): VerifyApps: Install-time verification requested for package com.optimaplus, id = 126
2023-06-21 09:57:37.658 12531-10494 Finsky                  com.android.vending                  I  [86516] VerifyAppsInstallTask.agt(5): VerifyApps: Anti-malware verification task started for package=com.optimaplus
2023-06-21 09:57:53.094 12531-12531 Finsky                  com.android.vending                  I  [2] VerifyInstallTask.ags(6): VerifyApps: Verification complete: id=126, package_name=com.optimaplus
2023-06-21 09:57:53.596 10697-10716 IconCustomizer          com.miui.guardprovider               D  Generate customized icon for com.optimaplus.png
2023-06-21 09:57:55.782  1804-2406  PackageFreezer          system_server                        W  Freeze package com.optimaplus about 0.201 seconds for reason: installPackageLI
2023-06-21 09:57:55.782  1804-2406  BackupManagerService    system_server                        I  [UserID:0] restoreAtInstall pkg=com.optimaplus token=75 restoreSet=0
2023-06-21 09:57:55.783  1804-2406  InstallationTiming      system_server                        I  com.optimaplus|null|19728|935|34|0|15454|0
2023-06-21 09:57:55.783  1804-2406  AppsFilter              system_server                        I  interaction: PackageSetting{bfdbfcd com.skill/10443} -> PackageSetting{8179cd8 com.optimaplus/10555} BLOCKED
2023-06-21 09:57:55.783  1804-2406  AppsFilter              system_server                        I  interaction: PackageSetting{1604fd0 com.fido.asm/10117} -> PackageSetting{8179cd8 com.optimaplus/10555} BLOCKED
2023-06-21 09:57:55.783  1804-2406  AppsFilter              system_server                        I  interaction: PackageSetting{9338bc9 com.kanzexapp/10449} -> PackageSetting{8179cd8 com.optimaplus/10555} BLOCKED
2023-06-21 09:57:55.809  1804-2822  SdkSandboxManager       system_server                        I  No SDKs used. Skipping SDK data reconcilation for CallingInfo{mUid=10555, mPackageName='com.optimaplus'}
2023-06-21 09:57:55.809  1804-2184  MiuiCompatModePackages  system_server                        I  package com.optimaplus updated, removing config
2023-06-21 09:57:55.812  1804-2622  MiuiNetwor...AppBuckets system_server                        D  updateAppPN packageName=com.optimaplus,uid=10555,installed=true
2023-06-21 09:57:55.822  3333-3333  CarrierSvcBindHelper    com.android.phone                    D  onPackageAdded: com.optimaplus
2023-06-21 09:57:55.825  5270-5270  SLM-SRV-SLAAppLib       com.xiaomi.NetworkBoost              E  initBroadcastReceivercom.optimaplus
2023-06-21 09:57:55.825  5270-5270  SLM-SRV-SLAAppLib       com.xiaomi.NetworkBoost              I  ACTION_PACKAGE_ADDED uid = 10555com.optimaplus
2023-06-21 09:57:55.825  2859-2859  WakePathManager         com.lbe.security.miui                I  PackageMonitor. onPackageAdded: packageName =com.optimaplus
2023-06-21 09:57:55.829 14991-15094 InstallApkReceiver      com.miui.home                        E  install:package:com.optimaplus
2023-06-21 09:57:55.830  1804-2842  AppScanObserverService  system_server                        E  Try to add a invalid package: com.optimaplus | 10555 | 0
2023-06-21 09:57:55.832 15363-15658 AppInstalledReceiver    com.miui.securitycenter.remote       D  packageName: com.optimaplus
2023-06-21 09:57:55.836 15363-15363 InstalledAppMonitor     com.miui.securitycenter.remote       I  com.optimaplusonReceive add pkg=com.optimaplus
2023-06-21 09:57:55.838 15363-15696 GameBoosterNewApp       com.miui.securitycenter.remote       I  com.optimaplus isGameFromJson false
2023-06-21 09:57:55.839 15363-15696 GameBoosterNewApp       com.miui.securitycenter.remote       I  com.optimaplus isGameFromLocal false
2023-06-21 09:57:55.858  7982-7982  SystemUpda...AppManager com.xiaomi.discover                  I  add package to list: com.optimaplus
2023-06-21 09:57:55.859  3333-3333  ImsResolver             com.android.phone                    D  maybeAddedImsService, packageName: com.optimaplus
2023-06-21 09:57:55.882 12531-10793 Finsky                  com.android.vending                  I  [86522] ax.a(5): Asset module storage cleared for package com.optimaplus.
2023-06-21 09:57:55.894 15363-15363 AppCompatStateReceiver  com.miui.securitycenter.remote       D  AppCompatStateReceiver package_name=com.optimaplus,app_status=0
2023-06-21 09:57:55.935  1804-2395  VerityUtils             system_server                        E  Failed to measure fs-verity, errno 1: /data/app/~~Tl1Es62wBZS0HX9ZXmjCkg==/com.optimaplus-rCSTkaVgAtQNy7iKX56akg==/base.apk
2023-06-21 09:57:55.948 15363-10800 AppCompatStateReceiver  com.miui.securitycenter.remote       D  json params=[{"pkg":"com.optimaplus","ver":"3145729"}]
2023-06-21 09:57:55.950 12531-12531 Finsky                  com.android.vending                  I  [2] jix.f(1): AIM: AppInfoCacheUpdater -> invalidating apps: [com.optimaplus]
2023-06-21 09:57:55.956 12531-8728  Finsky                  com.android.vending                  I  [85532] jku.a(5): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [com.optimaplus]
2023-06-21 09:57:55.982 13152-10819 ProximityAuth           com.google.android.gms.persistent    I  [RecentAppsMediator] Package added: (user=UserHandle{0}) com.optimaplus
2023-06-21 09:57:55.983  5230-11161 SQLiteLog               com.qualcomm.qti.workloadclassifier  W  (28) double-quoted string literal: "com.optimaplus"
2023-06-21 09:57:56.014 20432-10807 IconCustomizer          com.google.android.gms               D  Generate customized icon for com.optimaplus.png
2023-06-21 09:57:56.058  1804-3712  ActivityManager         system_server                        I  Force stopping com.optimaplus appid=10555 user=0: from process:10855
2023-06-21 09:57:56.073  3333-3333  CarrierSvcBindHelper    com.android.phone                    D  onHandleForceStop: [com.optimaplus]
2023-06-21 09:57:56.337  1804-3663  ActivityTaskManager     system_server                        I  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.optimaplus/.MainActivity} from uid 2000 from pid 10921 callingPackage com.android.shell
2023-06-21 09:57:56.346  1804-3663  MiGgameTyp...cationImpl system_server                        D  checkIfGameBeSupported app:com.optimaplus
2023-06-21 09:57:56.346  1804-3663  WindowManager           system_server                        I  When perf version lower than 2.3, MiGTStub result: false, gameType: 1, packageName: com.optimaplus
2023-06-21 09:57:56.382  1804-3965  CoreBackPreview         system_server                        D  Window{315df56 u0 Splash Screen com.optimaplus}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@602ca06, mPriority=0}
2023-06-21 09:57:56.391  1804-2189  Boost                   system_server                        D  hostingType=next-top-activity, hostingName={com.optimaplus/com.optimaplus.MainActivity}, callerPackage=com.android.shell, isSystem=true, isBoostNeeded=false.
2023-06-21 09:57:56.392  1804-2189  ActivityManager         system_server                        I  Start proc 26039:com.optimaplus/u0a555 for next-top-activity {com.optimaplus/com.optimaplus.MainActivity} caller=com.android.shell
2023-06-21 09:57:56.413 26039-26039 com.optimaplus          com.optimaplus                       I  Late-enabling -Xcheck:jni
2023-06-21 09:57:56.426  3359-3588  VRI[optimaplus]         com.android.systemui                 D  vri.reportNextDraw android.view.ViewRootImpl.performTraversals:3779 android.view.ViewRootImpl.doTraversal:2543 android.view.ViewRootImpl$TraversalRunnable.run:9465 android.view.Choreographer$CallbackRecord.run:1451 android.view.Choreographer$CallbackRecord.run:1459 
2023-06-21 09:57:56.426  3359-3588  VRI[optimaplus]         com.android.systemui                 D  vri.Setup new sync id=0 syncSeqId=0
2023-06-21 09:57:56.434  3359-3588  VRI[optimaplus]         com.android.systemui                 D  vri.reportDrawFinished syncSeqId=0 android.view.ViewRootImpl.lambda$createSyncIfNeeded$4$android-view-ViewRootImpl:3847 android.view.ViewRootImpl$$ExternalSyntheticLambda1.run:6 android.os.Handler.handleCallback:942 android.os.Handler.dispatchMessage:99 android.os.Looper.loopOnce:211 
2023-06-21 09:57:56.439  5230-11161 SQLiteLog               com.qualcomm.qti.workloadclassifier  W  (28) double-quoted string literal: "com.optimaplus"
2023-06-21 09:57:56.472  1804-2160  SmartPower...s/10555(0) system_server                        I  background->visible(93ms) R(become visible) adj=-10000.
2023-06-21 09:57:56.477  1804-2790  SmartPower              system_server                        I  com.optimaplus/10555 state=background adj=0 proc size=1 move to foreground become visible
2023-06-21 09:57:56.480 26039-26039 com.optimaplus          com.optimaplus                       I  Using CollectorTypeCC GC.
2023-06-21 09:57:56.488  1804-2160  WindowManager           system_server                        I  wms.showSurfaceRobustly mWin:Window{315df56 u0 Splash Screen com.optimaplus}
2023-06-21 09:57:56.501 14991-20896 ActivityManagerWrapper  com.miui.home                        E  getRecentTasks: mainTaskId=2295   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=268435456 cmp=ComponentInfo{com.optimaplus/com.optimaplus.MainActivity} }
2023-06-21 09:57:56.503 14991-20896 ziparchive              com.miui.home                        W  Unable to open '/data/app/~~lIUMqYLd3L43lYAA8qgh-A==/com.optimaplus-MvzIfX0zP98SIVvq2dnqkg==/base.apk': No such file or directory
2023-06-21 09:57:56.503 14991-20896 com.miui.home           com.miui.home                        E  Failed to open APK '/data/app/~~lIUMqYLd3L43lYAA8qgh-A==/com.optimaplus-MvzIfX0zP98SIVvq2dnqkg==/base.apk': I/O error
2023-06-21 09:57:56.504 14991-20896 ResourcesManager        com.miui.home                        W  failed to preload asset path '/data/app/~~lIUMqYLd3L43lYAA8qgh-A==/com.optimaplus-MvzIfX0zP98SIVvq2dnqkg==/base.apk'
                                                                                                    java.io.IOException: Failed to load asset path /data/app/~~lIUMqYLd3L43lYAA8qgh-A==/com.optimaplus-MvzIfX0zP98SIVvq2dnqkg==/base.apk
                                                                                                    	at android.content.res.ApkAssets.nativeLoad(Native Method)
                                                                                                    	at android.content.res.ApkAssets.<init>(ApkAssets.java:296)
                                                                                                    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:145)
                                                                                                    	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:482)
                                                                                                    	at android.app.ResourcesManager.-$$Nest$mloadApkAssets(Unknown Source:0)
                                                                                                    	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:177)
                                                                                                    	at android.app.ResourcesManager.createApkAssetsSupplierNotLocked(ResourcesManager.java:1027)
                                                                                                    	at android.app.ResourcesManager.getResources(ResourcesManager.java:1148)
                                                                                                    	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2557)
                                                                                                    	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:2075)
                                                                                                    	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:2061)
                                                                                                    	at android.app.ApplicationPackageManager.getText(ApplicationPackageManager.java:2382)
                                                                                                    	at android.content.pm.ComponentInfo.loadUnsafeLabel(ComponentInfo.java:130)
                                                                                                    	at android.content.pm.PackageItemInfo.loadLabel(PackageItemInfo.java:212)
                                                                                                    	at com.android.systemui.shared.recents.system.ActivityManagerWrapper.getBadgedActivityLabel(ActivityManagerWrapper.java:492)
                                                                                                    	at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityTitle(RecentsTaskLoader.java:664)
                                                                                                    	at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.preloadPlan(RecentsTaskLoadPlan.java:265)
                                                                                                    	at com.android.systemui.shared.recents.model.RecentsTaskLoader.preloadTasks(RecentsTaskLoader.java:462)
                                                                                                    	at com.miui.home.recents.RecentsModel.preloadRecents(RecentsModel.java:145)
                                                                                                    	at com.miui.home.recents.RecentsModel$HandlerCallbacks.handleMessage(RecentsModel.java:244)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Latropos** [comment]
Hi! Provided link doesn't work (it's probably outdated). Also we are sorry to inform that we have limited our support for Reanimated2 since our release of Reanimated 3.
