### ISSUE TITLE
Error when trying to use reanimated v2 in web

### ISSUE THREAD

**Issue by Christofon** [software-mansion/react-native-reanimated#5028]
### Description

I am trying to downgrade my reanimated version from v3 to v2 because `react-native-dragable-flatlist` seems to have issues with v3. The installation instructions where followed closely and are as described in the docs.

Unfortunately on the web I get the following error:

```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _updatePropsJS (http://localhost:8080/main.bundle.js:12093:1171)
    at http://localhost:8080/main.bundle.js:11658:1349
    at Set.forEach (<anonymous>)
    at _f (http://localhost:8080/main.bundle.js:11658:1292)
    at _f (http://localhost:8080/main.bundle.js:11948:9206)
    at Mapper._f [as mapper] (http://localhost:8080/main.bundle.js:11948:22143)
    at Mapper.execute (http://localhost:8080/main.bundle.js:12053:1436)
    at MapperRegistry.execute (http://localhost:8080/main.bundle.js:12063:1691)
    at JSReanimated._onRender (http://localhost:8080/main.bundle.js:12043:4283)
```

### Versions
```
"react-native-web": "0.19.6",
"react-native-reanimated": "^2.17.0",
"react-native": "0.72.3",
```

### Steps to reproduce

Install mentioned versions, the error should appear immediately on app start

### Snack or a link to a repository

none

### Reanimated version

2.17.0

### React Native version

0.72.3

### Platforms

Android, iOS, Web

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by m-bert** [comment]
Hi @Christofon! Unfortunately we are not planning to release new patches for Reanimated v2. That's why I highly recommend to stick to v3. 

What seems to be the problem with `react-native-dragable-flatlist`? @piaskowyk opened [this PR](https://github.com/computerjazz/react-native-draggable-flatlist/pull/462) in their repo, maybe it will fix your issue?
