### ISSUE TITLE
TypeError: Object is not a function, js engine: hermes; FATAL EXCEPTION: mqt_native_modules

### ISSUE THREAD

**Issue by Nehal-Zeller** [software-mansion/react-native-reanimated#5104]
### Description

App works fine in debug mode but crashes in release mode. Happens on both android and iOS. 
Error log:

```
JSI rethrowing JS exception: Object is not a function
TypeError: Object is not a function
 at anonymous (address at index.android.bundle:1:4711688)
 TypeError: Object is not a function, js engine: hermes
E  FATAL EXCEPTION: mqt_native_modules
 mdi.sdk.cv0: TypeError: Object is not a function, js engine: hermes, stack:anonymous@1:4711688
at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:75)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147)
at com.facebook.jni.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
at java.lang.Thread.run(Thread.java:1012)
```

### Steps to reproduce

Yet to figure out what is causing the crash but it started only after react-native-reanimated update

### Snack or a link to a repository

no link

### Reanimated version

3.5.2

### React Native version

0.71.13

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Pixel 6 (API 34)

### Acknowledgements

Yes

**Comment by tjzel** [comment]
Hi @Nehal-Zeller. Make sure you reset your bundler's cache after updating, eg. `yarn start --reset-cache` or `npm start -- --reset-cache`.

**Comment by Nehal-Zeller** [comment]
@tjzel  Thanks!
But the release build is crashing produced by CI and that CI agent has no stored caches.

**Comment by tjzel** [comment]
Oh yes, you are right. Could you check the behavior on `react-native` 0.72.3? Also, from which Reanimated version did you upgrade?

**Comment by Nehal-Zeller** [comment]
@tjzel  I'll try the upgrade real quick
Also,  previous  reanimated version was 3.4.2

**Comment by hirwaaldo1** [comment]
```js 
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// Ensure CSS files are handled properly
config.resolver.assetExts.push('css');

module.exports = config;

```
