### ISSUE TITLE
Attempted to extract from a HostObject that wasn't converted to a Shareable

### ISSUE THREAD

**Issue by enchorb** [software-mansion/react-native-reanimated#5322]
### Description

A lot of our users are getting the error below, only on Android 

```
Fatal Exception: com.facebook.jni.CppException: Exception in HostFunction: [Reanimated] Attempted to extract from a HostObject that wasn't converted to a Shareable.

Error: Exception in HostFunction: [Reanimated] Attempted to extract from a HostObject that wasn't converted to a Shareable.
    at _scheduleOnJS (native)
    at anonymous (JavaScript:1:438)
    at anonymous (JavaScript:1:212)
    at anonymous (JavaScript:1:629)
    at handleAndFlushAnimationFrame (JavaScript:1:148)
       at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(SourceFile)
       at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(:6)
       at com.swmansion.gesturehandler.react.RNGestureHandlerStateChangeEvent.dispatch(RNGestureHandlerStateChangeEvent.java:13)
       at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:2)
       at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:11)
       at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:27)
       at com.swmansion.gesturehandler.ReactContextExtensionsKt.dispatchEvent(ReactContextExtensions.kt:25)
       at com.swmansion.gesturehandler.react.RNGestureHandlerModule.sendEventForDirectEvent(:9)
       at com.swmansion.gesturehandler.react.RNGestureHandlerModule.sendEventForReanimated()
       at com.swmansion.gesturehandler.react.RNGestureHandlerModule.onStateChange(:24)
       at com.swmansion.gesturehandler.react.RNGestureHandlerModule.access$onStateChange()
       at com.swmansion.gesturehandler.react.RNGestureHandlerModule$eventListener$1.onStateChange(RNGestureHandlerModule.java:7)
       at com.swmansion.gesturehandler.core.GestureHandler.dispatchStateChange(GestureHandler.java:8)
       at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onHandlerStateChange(GestureHandlerOrchestrator.java:93)
       at com.swmansion.gesturehandler.core.GestureHandler.moveToState(GestureHandler.java:45)
       at com.swmansion.gesturehandler.core.GestureHandler.cancel(GestureHandler.java:14)
       at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.cancelAll(GestureHandlerOrchestrator.java:47)
       at com.swmansion.gesturehandler.core.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.java:24)
       at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.java:13)
       at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.java:14)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3091)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4299)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:2)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
       at android.view.View.dispatchPointerEvent(View.java:15309)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9286)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9420)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
       at android.view.Choreographer.doCallbacks(Choreographer.java:899)
       at android.view.Choreographer.doFrame(Choreographer.java:824)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7918)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Steps to reproduce

-

### Snack or a link to a repository

-

### Reanimated version

3.5.4

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Real device

### Device model

Various Android Devices, A lot On Pixel 7

### Acknowledgements

Yes

**Comment by tjzel** [comment]
@tomekzaw Is this fixed by #5264?

**Comment by tomekzaw** [comment]
@tjzel Not sure, the error in #5264 was `[Reanimated] Provided value is already an instance of ShareableJSRef.` but here it's `[Reanimated] Attempted to extract from a HostObject that wasn't converted to a Shareable.`.

**Comment by tjzel** [comment]
@enchorb Could you provide a snippet with a reproduction or at least a hint on how to reproduce it?

**Comment by Jiyeopkim** [comment]
It's the same problem.... help!

**Comment by JDBoots** [comment]
We're experiencing the same issue, but also on iOS.

`reanimated version 3.5.4`

**Comment by tomekzaw** [comment]
@JDBoots Thanks for your comment, thanks to your description I was able to reproduce this error.

**Comment by tomekzaw** [comment]
Closing this issue in favor of #5442 which has a minimal reproducible example. Thanks again @JDBoots for providing necessary information.

**Comment by ismaelsousa** [comment]
You are right @JDBoots, when you try to run a function created in a worklet context on `runOnJS` this error appears.

Check my case here: https://github.com/software-mansion/react-native-reanimated/issues/5442#issuecomment-1995391981
