### ISSUE TITLE
Unactionable errors are difficult to debug

### ISSUE THREAD

**Issue by gaearon** [software-mansion/react-native-reanimated#5367]
### Description

I'm trying to work around https://github.com/software-mansion/react-native-reanimated/issues/5364 by moving all my `useAnimatedScrollHandler` calls to the leaf components. This not a very easy process, and unfortunately it's complicated by this error providing no actionable information:

<img width="564" alt="Screenshot 2023-11-10 at 17 18 49" src="https://github.com/software-mansion/react-native-reanimated/assets/810438/7e146646-68d9-4dc4-9f34-9454181df0fd">

I don't know *where* that call (out of a dozen possible call sites) might be.

Any extra information, if possible, would be very useful in this output.

### Steps to reproduce

See above

### Snack or a link to a repository

N/A

### Reanimated version

3.4.3

### React Native version

0.72.5

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by gaearon** [comment]
In the terminal, I'm seeing this:

```
Error: ENOENT: no such file or directory, open '/Users/dan/p/social-app/worklet_13358486790341'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (/Users/dan/p/social-app/node_modules/metro/src/Server.js:879:18)
    at Server._symbolicate (/Users/dan/p/social-app/node_modules/metro/src/Server.js:962:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (/Users/dan/p/social-app/node_modules/metro/src/Server.js:418:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/dan/p/social-app/worklet_13358486790341'
}
Error: ENOENT: no such file or directory, open '/Users/dan/p/social-app/worklet_13358486790341'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getCodeFrame (/Users/dan/p/social-app/node_modules/metro/src/Server.js:879:18)
    at Server._symbolicate (/Users/dan/p/social-app/node_modules/metro/src/Server.js:962:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server._processRequest (/Users/dan/p/social-app/node_modules/metro/src/Server.js:418:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/dan/p/social-app/worklet_13358486790341'
}

```

I don't know if it means that I'm _actually_ calling worklets from a bad place, or if the build process just failed.

**Comment by Latropos** [comment]
Hi @gaearon,
These particular errors are already updated in the newest reanimated, now we provide a link to our documentation with more precise explanations.
<img src="https://github.com/software-mansion/react-native-reanimated/assets/56199675/4aa59233-b896-4635-a662-2647b0eb2d45" widht="300"/>

**Comment by gaearon** [comment]
Ahh nice, so it points to the source now? Then we can close.
