### ISSUE TITLE
Android: Application Not Responding Crash

### ISSUE THREAD

**Issue by gtokman** [software-mansion/react-native-reanimated#5438]
### Description

We are seeing crash logs for the following error on Android: Application Not Responding.

```
com.datadog.android.rum.internal.anr.ANRException: Application Not Responding
com.datadog.android.rum.internal.anr.ANRException
	at com.swmansion.reanimated.nativeProxy.AnimationFrameCallback.onAnimationFrame(Native Method)
	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:271)
	at com.swmansion.reanimated.NodesManager.-$$Nest$monAnimationFrame(Unknown Source:0)
	at com.swmansion.reanimated.NodesManager$2.doFrameGuarded(NodesManager.java:156)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	```

### Steps to reproduce

We haven't been able to definitively reproduce the error since local app execution didn't produce the same outcome. This error was identified through our crash analytics tool.

### Snack or a link to a repository

n/a

### Reanimated version

3.6.0

### React Native version

0.72.7

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by cakasuma** [comment]
happens to us as well
