### ISSUE TITLE
Requiring unknown module "undefined" ( isNativeModule Function )

### ISSUE THREAD

**Issue by SaatwikRishi** [software-mansion/react-native-reanimated#5490]
### Description

I recently updated my react native version from 0.68.5 to 0.72.7 and updated react-navigation drawer to 6.6.6, now whenever i am trying to open the drawer, the animation is  very sluggish and taking a lot of time to complete with a lot of lag also i am getting this error 
![image](https://github.com/software-mansion/react-native-reanimated/assets/38259107/e8e1384c-e2bf-4a1f-b985-dda3f24382f0)

I found a temporary fix by replacing 
import { PropsAllowlists } from '../../propsAllowlists';
to 
import * as List  from '../../propsAllowlists';

and changing the function 
from
function isNativeProp(propName: string): boolean {
  return !!PropsAllowlists.NATIVE_THREAD_PROPS_WHITELIST[propName];
}

to 

function isNativeProp(propName: string): boolean {
  return !!List.PropsAllowlists.NATIVE_THREAD_PROPS_WHITELIST[propName];
}

but is there any other way to fix this?

RN Info:
```
System:
  OS: macOS 14.1.2
  CPU: (8) arm64 Apple M1
  Memory: 99.77 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: /opt/homebrew/opt/node@18/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: /opt/homebrew/opt/node@18/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /Users/bahubully/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

```

### Steps to reproduce

1. Open drawer 
2. And issue is there

### Snack or a link to a repository

N/A

### Reanimated version

3.6.1

### React Native version

0.72.7

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

Samsung Galaxy S22+ (Physical Device ), Pixel 6A (Emulator )

### Acknowledgements

Yes

**Comment by Latropos** [comment]
Hi! Please reset cache each time you start metro `yarn start --reset-cache` and tell us **what version of react-navigation drawer you was previously used**.

**Comment by Latropos** [comment]
@SaatwikRishi

**Comment by SaatwikRishi** [comment]
@Latropos, tried that already,
previously i was on v6.4.1

**Comment by evilchis94** [comment]
Had the exactly the same issue, had to downgrade to react-native-reanimated 2.17.0 but now I face this problem: https://github.com/software-mansion/react-native-reanimated/issues/4408

React Native v0.72.7
React Native Reanimated v2.17.0

`com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8facebook5react19ReadableNativeArrayC1EN5folly7dynamicE" referenced by "/data/app/~~CjNIRn1YSNehUt2byya3Bg==/com.acsyt.rooma-T2nkcLDEt9wF0K0No3dLNg==/base.apk!/lib/arm64-v8a/libreanimated.so"..., js engine: hermes, stack:
callNativeSyncHook@1:106247
nonPromiseMethodWrapper@1:103288
NativeReanimated@1:708369
anonymous@1:701637
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:746320
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:710167
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:696855
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:695448
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:1867255
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:1866097
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:1865089
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:996223
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:986422
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:966518
loadModuleImplementation@1:73625
guardedLoadModule@1:73180
metroRequire@1:72808
anonymous@1:80017
loadModuleImplementation@1:73625
guardedLoadModule@1:73137
metroRequire@1:72808
global@1:72364 at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:1012)`

Please, help
Thanks!

**Comment by SaatwikRishi** [comment]
> Had the exactly the same issue, had to downgrade to react-native-reanimated 2.17.0 but now I face this problem: #4408
> 
> React Native v0.72.7 React Native Reanimated v2.17.0
> 
> `com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8facebook5react19ReadableNativeArrayC1EN5folly7dynamicE" referenced by "/data/app/~~CjNIRn1YSNehUt2byya3Bg==/com.acsyt.rooma-T2nkcLDEt9wF0K0No3dLNg==/base.apk!/lib/arm64-v8a/libreanimated.so"..., js engine: hermes, stack: callNativeSyncHook@1:106247 nonPromiseMethodWrapper@1:103288 NativeReanimated@1:708369 anonymous@1:701637 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:746320 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:710167 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:696855 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:695448 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:1867255 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:1866097 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:1865089 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:996223 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:986422 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:966518 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:80017 loadModuleImplementation@1:73625 guardedLoadModule@1:73137 metroRequire@1:72808 global@1:72364 at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) at com.facebook.jni.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) at android.os.Looper.loopOnce(Looper.java:210) at android.os.Looper.loop(Looper.java:299) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) at java.lang.Thread.run(Thread.java:1012)`
> 
> Please, help Thanks!

0.72 is not compatible with 2.xx, try using my temp fix which I have mentioned above

**Comment by evilchis94** [comment]
> > Had the exactly the same issue, had to downgrade to react-native-reanimated 2.17.0 but now I face this problem: #4408
> > React Native v0.72.7 React Native Reanimated v2.17.0
> > `com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8facebook5react19ReadableNativeArrayC1EN5folly7dynamicE" referenced by "/data/app/~~CjNIRn1YSNehUt2byya3Bg==/com.acsyt.rooma-T2nkcLDEt9wF0K0No3dLNg==/base.apk!/lib/arm64-v8a/libreanimated.so"..., js engine: hermes, stack: callNativeSyncHook@1:106247 nonPromiseMethodWrapper@1:103288 NativeReanimated@1:708369 anonymous@1:701637 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:746320 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:710167 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:696855 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:695448 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:1867255 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:1866097 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:1865089 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:996223 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:986422 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:966518 loadModuleImplementation@1:73625 guardedLoadModule@1:73180 metroRequire@1:72808 anonymous@1:80017 loadModuleImplementation@1:73625 guardedLoadModule@1:73137 metroRequire@1:72808 global@1:72364 at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) at com.facebook.jni.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) at android.os.Looper.loopOnce(Looper.java:210) at android.os.Looper.loop(Looper.java:299) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) at java.lang.Thread.run(Thread.java:1012)`
> > Please, help Thanks!
> 
> 0.72 is not compatible with 2.xx, try using the temp fix I have mentioned above

It worked for debug mode, but not for release. I'm getting the same undefined is not a function, js engine: hermes

**Comment by Ryabchikus** [comment]
Same here with error in reanimated v3.6.1 and RN 0.72.7
I can fork the repository and fix it for my project, but it doesn't look good

**Comment by lluis-sancho** [comment]
Same with 0.71.6 and reanimated 3.6.1

**Comment by marcofuentes05** [comment]
Same here, trying to update RN 0.71.2 -> 0.73.2 using reanimated 3.6.1

**Comment by Stewart-Needham** [comment]
Just working through an upgrade and encountered this issue. luketgriffith's workaround overcame the issue.
RN 0.73.2
react-native-reanimated 3.6.1
@react-navigation/drawer 6.6.6

**Comment by MaryKilduff68** [comment]
Our project is also seeing this issue, [SaatwikRishi](https://github.com/SaatwikRishi) temporary fix worked for us, but would be keen to see if this issue could be resolved

**Comment by eidan66** [comment]
> i have this error as well - even though the PropsAllowlist seems to be clearly defined, it would crash every time. I ended up moving the contents of that file (propsAllowLists.ts) directly into the index.ts file, and that worked for some reason. Created a patch to work around it for now

Can you share the patch file, please?

**Comment by Srh07** [comment]
I'm facing the same issue after upgrading. 
The fix of [SaatwikRishi](https://github.com/SaatwikRishi) seems to work. (importing propsAllowlists differently)

Hoping for a permanent fix soon. 

versions:
"react-native": "0.72.11",
"@react-navigation/drawer": "^6.6.11",
"react-native-reanimated": "^3.7.2",

**Comment by rohinipf** [comment]
We just upgraded to the following versions and are experiencing the exact same issue. Will we be seeing a permanent fix soon as this issue has been ongoing for a while now?

"react-native": "0.73.5",
 "@react-navigation/drawer": "^6.6.11",
 "react-native-reanimated": "^3.7.2",

**Comment by anhquan291** [comment]
Also facing the same issue with the latest versions!

**Comment by BloodyMonkey** [comment]
Same problem with 3.10.1, patch seems to fix it

**Comment by JeeshaVwebiots** [comment]
i want to this error in React native 0.75.3

**Comment by cuongnguyeneh** [comment]
For me, it looks like React native debugger causes this issue, it also crash app when I try to upgrade reanimated to 3.15.5 . ref https://github.com/jhen0409/react-native-debugger/issues/811

**Comment by patrycjakalinska** [comment]
hi @SaatwikRishi, could you please bump your Reanimated to `3.19.0` or to `4.0.0` (as it has minor changes to propsAllowlist) and RN to `0.80` and tell me if it fixed your problem? If no, please let me know if the issue exists on latest clean RN Reanimated app with RN Naviagtion?

If you could also provide me with a code snippet that will reproduce the issue, as it looks fine on my side.
