### ISSUE TITLE
useAnimatedKeyboard does not work for Android when the focused TextInput is inside a Modal

### ISSUE THREAD

**Issue by Braden1996** [software-mansion/react-native-reanimated#5754]
### Description

`useAnimatedKeyboard` generally works well, but unfortunately doesn't update on Android when the focused `TextInput` is inside a `Modal`. This issue has been around for quite a few major releases and I can confirm it is also present in the latest release.

Interesting, this issue is also present in `react-native-keyboard-controller` despite them using a different approach to calculating keyboard height (see https://github.com/kirillzyusko/react-native-keyboard-controller/issues/369). 

Here is a video demonstrating the working behaviour on iOS, followed by the broken behaviour on Android:
https://github.com/software-mansion/react-native-reanimated/assets/5165963/ed37fc4d-7bc3-453c-8d32-5de5847bebee

### Steps to reproduce

Put a `TextInput` inside a `Modal` component. Notice that any uses of `useAnimatedKeyboard` (both inside the `Modal` and outside) do not update to reflect the visible keyboard height.

### Snack or a link to a repository

https://snack.expo.dev/@braden1996/reanimated-useanimatedkeyboard-modal-bug

### Reanimated version

3.6.1

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Thanks @Braden1996 for reporting this issue! Recently we've merged several improvements directly related to `useAnimatedKeyboard` and this sounds like a reasonable thing to fix as well. I hope @piaskowyk will have some time to investigate this issue.

**Comment by maciekstosio** [comment]
I prepared PR (#5916) that allows to keep track keyboard height on modals too. Please, let me know if that helps.

**Comment by kirillzyusko** [comment]
Hey @maciekstosio 

Have you tested Fabric architecture? I've applied your patch and it crashes app immediately when modal appears with:

```bash
FATAL EXCEPTION: main

com.facebook.react.uimanager.IllegalViewOperationException: Trying to resolve view with tag 480 which doesn't exist

FATAL EXCEPTION: main
Process: com.keyboardcontrollerfabricexample, PID: 3726
com.facebook.react.uimanager.IllegalViewOperationException: Trying to resolve view with tag 480 which doesn't exist
	at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveView(NativeViewHierarchyManager.java:102)
	at com.facebook.react.uimanager.UIManagerModule.resolveView(UIManagerModule.java:870)
	at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:337)
	at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:320)
	at com.facebook.react.uimanager.events.FabricEventDispatcher.dispatchEvent(FabricEventDispatcher.java:43)
```

**Comment by 256hz** [comment]
Hi @maciekstosio I made a patch from your PR and it worked like a charm for me, thank you very much!  We're on Expo 49.

**Comment by deva-Irfan** [comment]
I am facing the same issue, it works nicely on ios, on android `keyboard.height.value` returns 0
```tsx
import React from "react";
import { Modal, Pressable } from "react-native";
import Animated, { useAnimatedKeyboard, useAnimatedStyle, withSpring } from "react-native-reanimated";

interface ModalViewProps {
  visible: boolean;
  children: React.ReactNode;
  onClose?: () => void;
}

export default function ModalView({ children, visible, onClose = () => undefined }: ModalViewProps) {
  const keyboard = useAnimatedKeyboard();

  const keyboardAwareStyle = useAnimatedStyle(() => {
    const keyBoardHeight = keyboard.height.value;
    return {
      marginBottom: withSpring(keyBoardHeight * 0.9),
    };
  });
  console.log({ kheight: keyboard.height.value });

  return (
    <Modal transparent animationType="none" visible={visible} statusBarTranslucent>
      <Pressable
        style={{ position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(0, 0, 0, 0.5)" }}
        onPress={onClose}
      />
      <Animated.View style={[{ flex: 1, justifyContent: "center", alignItems: "center" }, keyboardAwareStyle]}>
        {children}
      </Animated.View>
    </Modal>
  );
}
```

**Comment by kirillzyusko** [comment]
@deva-Irfan the `useAnimatedKeyboard` hook is [deprecated](https://docs.swmansion.com/react-native-reanimated/docs/device/useAnimatedKeyboard#migration-guide) now. You can use `react-native-keyboard-controller` lib (this bug shouldn't be reproducible using this lib, but if you encounter any issues you can submit them in `react-native-keyboard-controller` repo)
