### ISSUE TITLE
ReferenceError: _updateDataSynchronously is not defined

### ISSUE THREAD

**Issue by jordmccord** [software-mansion/react-native-reanimated#6019]
### Description

Since upgrading to Expo SDK 51 and Reanimated 3.10.1 I'm getting this error when rendering my app in for the web:
```
ReferenceError: _updateDataSynchronously is not defined
    at mutables.ts:1:1
    at ../../packages/native-ui/node_modules/react-native-reanimated/lib/module/reanimated2/mutables.js (mutables.ts:1:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at ../../packages/native-ui/node_modules/react-native-reanimated/lib/module/reanimated2/Sensor.js (Sensor.ts:1:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at ../../packages/native-ui/node_modules/react-native-reanimated/lib/module/reanimated2/SensorContainer.js (SensorContainer.ts:1:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    ```

![Screenshot 2024-05-15 at 11 26 10](https://github.com/software-mansion/react-native-reanimated/assets/7591840/ee2e43bf-f7bd-44b1-8c42-a651ce058b66)

    

### Steps to reproduce

1. Update to Expo SDK 51
2. Build app in storybook for web

### Snack or a link to a repository

N/A

### Reanimated version

3.10.1

### React Native version

0.74.1

### Platforms

Web

### JavaScript runtime

None

### Workflow

Expo Go

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by jordmccord** [comment]
This was caused due to a dev dependency of a monorepo being an older version of reanimated
