### ISSUE TITLE
[3.13.0] IllegalArgumentException - Expected receiver of type com.swmansion.rnscreens.ScreenFragment

### ISSUE THREAD

**Issue by huextrat** [software-mansion/react-native-reanimated#6210]
### Description

From `v3.13.0` we are seeing issue on Android. We are reproducing it using Stripe SDK and launching Google Pay sheet, but according to the stack trace this might occur on other native fragment.

I can reproduce it on debug and release on my app.

`Expected receiver of type com.swmansion.rnscreens.ScreenFragment, but got com.reactnativestripesdk.GooglePayPaymentMethodLauncherFragment`

We never saw this crash before the update, and it seems related to RN Screens also, but we are on `v3.32.0` for two weeks, and it was working well with previous reanimated version.

Here is the complete raw stack trace: 

```
java.lang.IllegalArgumentException: Expected receiver of type com.swmansion.rnscreens.ScreenFragment, but got com.reactnativestripesdk.GooglePayPaymentMethodLauncherFragment
    at java.lang.reflect.Method.invoke(Method.java)
    at com.swmansion.reanimated.layoutReanimation.TabNavigatorObserver$FragmentLifecycleCallbacks.onFragmentUpdate(SourceFile:6)
    at com.swmansion.reanimated.layoutReanimation.TabNavigatorObserver$FragmentLifecycleCallbacks.onFragmentAttached(SourceFile:2)
    at androidx.fragment.app.FragmentLifecycleCallbacksDispatcher.dispatchOnFragmentAttached(SourceFile:59)
    at androidx.fragment.app.FragmentStateManager.attach(SourceFile:194)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:138)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:348)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:82)
    at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:22)
    at androidx.fragment.app.FragmentManager$5.run(SourceFile:4)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loopOnce(Looper.java:232)
    at android.os.Looper.loop(Looper.java:317)
    at android.app.ActivityThread.main(ActivityThread.java:8699)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

### Steps to reproduce

1. Opening Google Pay with Stripe SDK

### Snack or a link to a repository

WIP

### Reanimated version

3.13.0

### React Native version

0.74.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Acknowledgements

Yes

**Comment by piaskowyk** [comment]
@huextrat thank for the report! I prepared PR with fix, could you check if it works for you?

**Comment by huextrat** [comment]
@piaskowyk I've just tried it with a patch, and the fix works well 👌 Thank you for your responsiveness
