### ISSUE TITLE
IllegalViewOperationException associated with ReanimatedUIManage on production crashlytics

### ISSUE THREAD

**Issue by Mahmoudn1** [software-mansion/react-native-reanimated#6435]
### Description

we are facing this error in production in Crashlytics that we can not reproduce

       Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException: Trying to update non-existent view with tag 39
       at com.facebook.react.uimanager.UIImplementation.updateView(UIImplementation.java:272)
       at com.facebook.react.uimanager.UIManagerModule.updateView(UIManagerModule.java:430)
       at com.facebook.react.uimanager.ReanimatedUIManager.updateView(ReanimatedUIManager.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)
        

### Steps to reproduce

We can not reproduce it

### Snack or a link to a repository

not available

### Reanimated version

3.5.1

### React Native version

0.72.11

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by alihamza1729** [comment]
Hi i am getting same issue have you found any solution?

"react-native-reanimated": "^3.15.5",
  "react-native": "^0.72.7",
