### ISSUE TITLE
no version-specific reanimated AAR for react-native version 72 found.

### ISSUE THREAD

**Issue by Akilramki** [software-mansion/react-native-reanimated#6616]
### Description

WARNING reanimated - no version-specific reanimated AAR for react-native version 72 found.
Falling back to AAR for react-native version 71.
The react-native JSI interface is not ABI-safe yet, this may result in crashes.
Please post a pull request to implement support for react-native version 72 to the reanimated repo.
Thanks!

logs:
 E  FATAL EXCEPTION: main Process: com.test, PID: 8131
 java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
	at com.facebook.react.defaults.DefaultReactNativeHost.<init>(Unknown Source:2)
	at com.test.MainApplication$1.<init>(MainApplication.java:60)
	at com.test.MainApplication.<init>(MainApplication.java:59)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1177)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6686)
	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/~~9WxCk3XrE7SQPl1SGfcVBw==/com.test-bI6GMu7mX7VADCnd_HBxrg==/base.apk"],nativeLibraryDirectories=[/data/app/~~9WxCk3XrE7SQPl1SGfcVBw==/com.test-bI6GMu7mX7VADCnd_HBxrg==/lib/arm64, /data/app/~~9WxCk3XrE7SQPl1SGfcVBw==/com.test-bI6GMu7mX7VADCnd_HBxrg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.facebook.react.defaults.DefaultReactNativeHost.<init>(Unknown Source:2) 
	at com.test.MainApplication$1.<init>(MainApplication.java:60) 
	at com.test.MainApplication.<init>(MainApplication.java:59) 
	at java.lang.Class.newInstance(Native Method) 
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) 
	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51) 
	at android.app.Instrumentation.newApplication(Instrumentation.java:1177) 
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356) 
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6686) 
	at android.app.ActivityThread.access$1500(ActivityThread.java:247) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7839) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 

### Steps to reproduce

1. App installed and Crashed

### Snack or a link to a repository

nil

### Reanimated version

3.15.5

### React Native version

0.72.17

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & production bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by tomekzaw** [comment]
Hi @Akilramki, this is simply not possible – we don't have "reanimated - no version-specific reanimated AAR" warning since long time ago.

Are you sure you're using Reanimted 3.15.5?

**Comment by Akilramki** [comment]
@tomekzaw yes

**Comment by tomekzaw** [comment]
@Akilramki Please share full build logs so we can help you.
