### ISSUE TITLE
Snapshots excessively large or failing with `Invalid string length`

### ISSUE THREAD

**Issue by BrianValente** [software-mansion/react-native-reanimated#6645]
### Description

Since Reanimated v3.16.0, snapshots using `@testing-library/react-native` have been breaking. In some cases, the snapshot size has increased drastically, going from less than 1 KB to over 250 MB. In other cases, snapshots fail to generate, throwing an `Invalid string length` error. 

### v3.15.5
```
 PASS  ./ComponentTwo.test.tsx
 › 1 snapshot written.
 PASS  ./ComponentOne.test.tsx
 › 1 snapshot written.

Snapshot Summary
 › 2 snapshots written from 2 test suites.

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   2 written, 2 total
Time:        1.938 s, estimated 22 s
```
```
➜ ls -lh
total 16
-rw-r--r--@ 1 brianvalente  staff   586B Oct 28 16:22 ComponentOne.test.tsx.snap
-rw-r--r--@ 1 brianvalente  staff   925B Oct 28 16:22 ComponentTwo.test.tsx.snap
```

### v3.16.1

```
 PASS  ./ComponentOne.test.tsx (6.267 s)
 › 1 snapshot written.
 FAIL  ./ComponentTwo.test.tsx (9.18 s)
  ● ComponentTwo › should pass

    RangeError: Invalid string length

       6 |     it("should pass", () => {
       7 |         const rendered = render(<ComponentTwo />).toJSON();
    >  8 |         expect(rendered).toMatchSnapshot();
         |                          ^
       9 |     });
      10 | })
      11 |

      at printElement (node_modules/jest-snapshot/node_modules/pretty-format/build/plugins/lib/markup.js:105:36)
      at Object.toMatchSnapshot (ComponentTwo.test.tsx:8:26)

Snapshot Summary
 › 1 snapshot written from 1 test suite.

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   1 written, 1 total
Time:        9.404 s
```

```
➜ ls -lh
total 537280
-rw-r--r--@ 1 brianvalente  staff   262M Oct 28 16:23 ComponentOne.test.tsx.snap
```

### Steps to reproduce

1. Clone [demo repo](https://github.com/BrianValente/reanimated-jest-snapshot-issue-demo)
2. Install dependencies
3. Run `npm run test`

### Snack or a link to a repository

https://github.com/BrianValente/reanimated-jest-snapshot-issue-demo

### Reanimated version

3.6.1

### React Native version

0.74.5

### Platforms

Android, iOS, macOS, Web

### JavaScript runtime

Hermes

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Other (please specify)

### Device

None

### Acknowledgements

Yes

**Comment by arelstone** [comment]
I am facing the same issue

**Comment by nicolas-meilan** [comment]
I have the same issue

**Comment by arelstone** [comment]
My issue were caused by a regular useRef on an Animated.Scrollview. When it was changed to an useAnimatedRef the size went back to normal

**Comment by MBauhoffer** [comment]
Same here :(

**Comment by mostfinance-ca** [comment]
I am facing the same issue. I am running RN 0.76.1 and RNR 3.16.1

**Comment by wkoutre** [comment]
Also blocked by this

**Comment by ally-bryand** [comment]
I'm having the same issues with RN 0.76 and RNR 3.16.2

**Comment by rotoxl** [comment]
+1, also blocked here

**Comment by ilteoood** [comment]
Here is happening with reanimated version 3.16.x, while on 3.15.x is not happening

**Comment by Pcpkomputer** [comment]
+1

**Comment by rotoxl** [comment]
Hey @ilteoood,

Same here. 
This unblocks me, and now I will be able to upgrade to newest `expo-sdk52`

Thanks!

**Comment by MarkKD** [comment]
+ 1 I've encountered this issue on both 3.15.x and 3.16.x

**Comment by Pcpkomputer** [comment]
+1

**Comment by Grohden** [comment]
Really annoying to debug, but it seems that `jestInlineStyle` is the culprit here

Here's a patch that probably will work for people:
```
diff --git a/build/plugins/lib/markup.js b/build/plugins/lib/markup.js
index dae3bc4ada911297e1d0f1ad2e8ea7083a81a649..4aacf5e914574ae5a5385e01bb7e1892701f5765 100644
--- a/build/plugins/lib/markup.js
+++ b/build/plugins/lib/markup.js
@@ -26,6 +26,10 @@ const printProps = (keys, props, config, indentation, depth, refs, printer) => {
   const indentationNext = indentation + config.indent;
   const colors = config.colors;
   return keys
+    .filter(key => {
+      // https://github.com/software-mansion/react-native-reanimated/issues/6645
+      return !["jestInlineStyle"].includes(key);
+    })
     .map(key => {
       const value = props[key];
       let printed = printer(value, config, indentationNext, depth, refs);
```

If there's anything related to that property is this PR https://github.com/software-mansion/react-native-reanimated/pull/6400

Might be worth to investigate it

**Comment by Grohden** [comment]
An alternative patch that worked here: 
```diff
diff --git a/lib/module/createAnimatedComponent/createAnimatedComponent.js b/lib/module/createAnimatedComponent/createAnimatedComponent.js
index a6cb68f926a1c0501631ffa988e19290cc4e3994..f04ed3a273dbd03e9f1da4538ef6c12a01a04ed4 100644
--- a/lib/module/createAnimatedComponent/createAnimatedComponent.js
+++ b/lib/module/createAnimatedComponent/createAnimatedComponent.js
@@ -387,8 +387,9 @@ export function createAnimatedComponent(Component, options) {
       const skipEntering = this.context?.current;
       const nativeID = skipEntering || !isFabric() ? undefined : `${this.reanimatedID}`;
       const jestProps = IS_JEST ? {
-        jestInlineStyle: this.props.style,
-        jestAnimatedStyle: this.jestAnimatedStyle
+        // https://github.com/software-mansion/react-native-reanimated/issues/6645
+        // jestInlineStyle: this.props.style,
+        // jestAnimatedStyle: this.jestAnimatedStyle
       } : {};
       return /*#__PURE__*/React.createElement(Component, _extends({
         nativeID: nativeID
```

**Comment by BrianValente** [comment]
@Grohden It worked, thank you! Now I can upgrade to the latest version while waiting for the fix to be implemented.

**Comment by cam-shaw** [comment]
@Grohden I tested adding `toJSON` in the tests added by that PR #6400 and I saw the same error.
Might try dig into this tomorrow to see if I can resolve anything.

I did work out that if you don't provide an inline animated style (e.g. from useAnimatedStyle) to your component, it will work fine and your tests will pass. No solutions there yet just a discovery.

If you update your patch to result in the following code, it will filter out any animated styles and continue to apply normal styles. Excuse anything _poor_ about the code as it's just a quick hack in my debugging.
```javascript
 const isAnimatedStyle = (style) => {
        return "jestAnimatedStyle" in style;
      };
      const jestProps = IS_JEST
        ? {
            jestInlineStyle: Array.isArray(this.props.style)
              ? this.props.style.filter((style) => !isAnimatedStyle(style))
              : isAnimatedStyle(this.props.style)
              ? {}
              : this.props.style,
            jestAnimatedStyle: this.jestAnimatedStyle,
          }
        : {};
```

**Comment by cam-shaw** [comment]
@Grohden I tested adding `toJSON` in the tests added by that PR #6400 and I saw the same error.
Might try dig into this tomorrow to see if I can resolve anything.

I did work out that if you don't provide an inline animated style (e.g. from useAnimatedStyle) to your component, it will work fine and your tests will pass. No solutions there yet just a discovery.

If you update your patch to result in the following code, it will filter out any animated styles and continue to apply normal styles. Excuse anything _poor_ about the code as it's just a quick hack in my debugging.
```javascript
const isAnimatedStyle = (style) => {
  return "jestAnimatedStyle" in style;
};
const jestProps = IS_JEST
  ? {
      jestInlineStyle: Array.isArray(this.props.style)
        ? this.props.style.filter((style) => !isAnimatedStyle(style))
        : isAnimatedStyle(this.props.style)
        ? {}
        : this.props.style,
      jestAnimatedStyle: this.jestAnimatedStyle,
    }
  : {};
```

**Comment by wkoutre** [comment]
Applying @Grohden 's patch works! However, I found that tests that use `expect(component).toHaveAnimatedStyle(...)` would fail. Here's an updated patch that fixes this

```diff
diff --git a/lib/module/createAnimatedComponent/createAnimatedComponent.js b/lib/module/createAnimatedComponent/createAnimatedComponent.js
index 69682cb3b85d04d83ae29dc8d07e16204e62b29c..62fe52439729a7280c1fc5d33addc53fd367a5ca 100644
--- a/lib/module/createAnimatedComponent/createAnimatedComponent.js
+++ b/lib/module/createAnimatedComponent/createAnimatedComponent.js
@@ -172,9 +172,9 @@ export function createAnimatedComponent(Component, options) {
       } else {
         const hostInstance = findHostInstance(this);
         if (!hostInstance) {
-          /* 
-            findHostInstance can return null for a component that doesn't render anything 
-            (render function returns null). Example: 
+          /*
+            findHostInstance can return null for a component that doesn't render anything
+            (render function returns null). Example:
             svg Stop: https://github.com/react-native-svg/react-native-svg/blob/develop/src/elements/Stop.tsx
           */
           throw new ReanimatedError('Cannot find host instance for this component. Maybe it renders nothing?');
@@ -392,8 +392,10 @@ export function createAnimatedComponent(Component, options) {
       const skipEntering = this.context?.current;
       const nativeID = skipEntering || !isFabric() ? undefined : `${this.reanimatedID}`;
       const jestProps = IS_JEST ? {
-        jestInlineStyle: this.props.style,
-        jestAnimatedStyle: this.jestAnimatedStyle
+        // In react-native-reanimated 3.16.0>, there's a bug that generates components infinitely, because of the circular reference in jestAnimatedStyle.
+        // To fix this, let's temporarily not pass the jestAnimatedStyle to the component.
+        // jestInlineStyle: this.props.style,
+        // jestAnimatedStyle: this.jestAnimatedStyle
       } : {};
       return /*#__PURE__*/React.createElement(Component, _extends({
         nativeID: nativeID
diff --git a/lib/module/jestUtils.js b/lib/module/jestUtils.js
index 09310c12af916c38bb51f6297a08fc880c1ede67..d41a4a07978ea9ce18d88a5bcad9dd8b03d65b22 100644
--- a/lib/module/jestUtils.js
+++ b/lib/module/jestUtils.js
@@ -6,7 +6,7 @@ import { ReanimatedError } from "./errors.js";
 const defaultFramerateConfig = {
   fps: 60
 };
-const isEmpty = obj => Object.keys(obj).length === 0;
+const isEmpty = (obj = {}) => Object.keys(obj).length === 0;
 const getStylesFromObject = obj => {
   return obj === undefined ? {} : Object.fromEntries(Object.entries(obj).map(([property, value]) => [property, value._isReanimatedSharedValue ? value.value : value]));
 };

```

**Comment by rkaartikeyan** [comment]
> Hey [@ilteoood](https://github.com/ilteoood),
> 
> Same here. This unblocks me, and now I will be able to upgrade to newest `expo-sdk52`
> 
> Thanks!
> 
> > Here is happening with reanimated version 3.16.x, while on 3.15.x is not happening
> 
> Update: unfortunately I have Android build errors on version 3.15, so stuck again :(
> 
> ```
> > Task :react-native-reanimated:compileDebugJavaWithJavac FAILED
> /Users/rotoxl/dev/beone-mobile/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:456: warning: [removal] ReactViewBackgroundDrawable in com.facebook.react.views.view has been deprecated and marked for removal
>         if (!(background instanceof ReactViewBackgroundDrawable)) {
>                                     ^
> /Users/rotoxl/dev/beone-mobile/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java:459: warning: [removal] ReactViewBackgroundDrawable in com.facebook.react.views.view has been deprecated and marked for removal
>         int actualColor = ((ReactViewBackgroundDrawable) background).getColor();
>                             ^
> /Users/rotoxl/dev/beone-mobile/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java:285: error: no suitable method found for updateLayout(int,int,int,int,int,int)
>     super.updateLayout(parentTag, tag, x, y, width, height);
>          ^
>     method NativeViewHierarchyManager.updateLayout(int,int,int,int,int) is not applicable
>       (actual and formal argument lists differ in length)
>     method NativeViewHierarchyManager.updateLayout(int,int,int,int,int,int,YogaDirection) is not applicable
>       (actual and formal argument lists differ in length)
>     method NativeViewHierarchyManager.updateLayout(View,int,int,int,int) is not applicable
>       (actual and formal argument lists differ in length)
> /Users/rotoxl/dev/beone-mobile/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/BorderRadiiDrawableUtils/latest/com/swmansion/reanimated/BorderRadiiDrawableUtils.java:15: error: incompatible types: bad type in conditional expression
>       float full = uniform != null ? uniform.resolve(view.getWidth(), view.getHeight()) : Float.NaN;
>                                                     ^
>     CornerRadii cannot be converted to float
> /Users/rotoxl/dev/beone-mobile/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/BorderRadiiDrawableUtils/latest/com/swmansion/reanimated/BorderRadiiDrawableUtils.java:16: warning: [removal] getComputedBorderRadius() in CSSBackgroundDrawable has been deprecated and marked for removal
>       ComputedBorderRadius computedBorderRadius = drawable.getComputedBorderRadius();
>                                                           ^
> /Users/rotoxl/dev/beone-mobile/node_modules/react-native-reanimated/android/src/reactNativeVersionPatch/BorderRadiiDrawableUtils/latest/com/swmansion/reanimated/BorderRadiiDrawableUtils.java:19: error: incompatible types: CornerRadii cannot be converted to float
>           computedBorderRadius.getTopLeft(),
>                                          ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
> 3 errors
> 3 warnings
> ```

Hi @rotoxl I am also facing same issue with RNRA 3.15.0 and RN 0.76.0, did you found any solution?

**Comment by rotoxl** [comment]
Hey @rkaartikeyan, 
sorry I dont have in my memory what was the key, it was 6 months ago, but we had to mock reanimated, so I would suggest you start with `require('react-native-reanimated').setUpTests();` and you try to narrow down the problem.

I wish I remembered more info 🤷‍♂️
