### ISSUE TITLE
 Error: Exception in HostObject::get for prop 'ReanimatedModule': java.lang.RuntimeException: [Reanimated] Failed to obtain instance of FabricUIManager.

### ISSUE THREAD

**Issue by tdinckaya** [software-mansion/react-native-reanimated#6660]
### Description

I’m trying to upgrade to React Native version 0.76.1. However, I encountered the following error on the Android side.

Metro Bundle:
 Error: Exception in HostObject::get for prop 'ReanimatedModule': java.lang.RuntimeException: [Reanimated] Failed to obtain instance of FabricUIManager.

Logcat:
FATAL EXCEPTION: main
                                                                                                    Process: com.myapp, PID: 3096
                                                                                                    java.lang.AssertionError
                                                                                                    	at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:160)
                                                                                                    	at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:128)
                                                                                                    	at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.maybeInit(ReaLayoutAnimator.java:36)
                                                                                                    	at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.isLayoutAnimationEnabled(ReaLayoutAnimator.java:191)
                                                                                                    	at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.isLayoutAnimationDisabled(ReanimatedNativeHierarchyManager.java:92)
                                                                                                    	at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.manageChildren(ReanimatedNativeHierarchyManager.java:148)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:194)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:879)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:992)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue.-$$Nest$mflushPendingBatches(Unknown Source:0)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:948)
                                                                                                    	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### Steps to reproduce

1. react-native run-android

### Snack or a link to a repository

tdinckaya

### Reanimated version

3.16.1

### React Native version

0.76.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

Real device

### Device model

Samsung Galaxy A50

### Acknowledgements

Yes

**Comment by tdinckaya** [comment]
I was performing a React Native upgrade, and my issue was resolved when I converted my Java files in the Android directory to Kotlin.

**Comment by instesti** [comment]
Were you able to get this sorted @BalogunofAfrica ?

**Comment by vivek-sharma-sws** [comment]
@tdinckaya Could you please share the Kotlin file, if possible? I'm facing the same issue while upgrading React Native from version 0.63.0 to 0.78.1.

**Comment by LuanNguyen-HnL** [comment]
I faced this issue on RN 0.80 and react-native-reanimated@4.1.0 on Android. I'm using Java files, but what's problem with Java files? Any one else have the resolution for this? I'm upgrading RN to RN 0.80 from 0.70

**Comment by pemeraldy** [comment]
I am facing the same issue. Is there a solution yet?

**Comment by greeenboi** [comment]
I found a fix that worked for me, just update react native reanimated

```console
react-native-reanimated@3.17.5 - expected version: ~4.1.1
```
