### ISSUE TITLE
App cash with `java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference`

### ISSUE THREAD

**Issue by bglgwyng** [software-mansion/react-native-reanimated#6674]
### Description

My app keeps crashing and failing to launch.

Here's the stack trace from Sentry.
```
java.lang.IllegalStateException: com.facebook.jni.CppException: Exception in HostFunction: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference

Error: Exception in HostFunction: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.HashMap.containsKey(java.lang.Object)' on a null object reference
    at _notifyAboutProgress (native)
    at anonymous (JavaScript:1:325)
    at anonymous (JavaScript:1:396)
    at forEach (native)
    at set _value (JavaScript:1:368)
    at step (JavaScript:1:1058)
    at anonymous (JavaScript:1:407)
    at forEach (native)
    at anonymous (JavaScript:1:386)
    at anonymous (JavaScript:1:704)
    at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:496)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
    at com.facebook.react.modules.core.ReactChoreographer$1.doFrame(ReactChoreographer.java:89)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1688)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1154)
    at android.view.Choreographer.doFrame(Choreographer.java:1070)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:9063)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Steps to reproduce

> This error has only been found in my production app. I'm trying to figure out how to reproduce it, but I have very little clue now. Please let me know if someone sees hints in the stack trace.

### Snack or a link to a repository

not yet

### Reanimated version

3.6.1

### React Native version

0.74.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

Expo Go

### Architecture

Paper (Old Architecture)

### Build type

Release app & production bundle

### Device

Real device

### Device model

Samsung Galaxy,  SM-F731N

### Acknowledgements

Yes

**Comment by johnnywang** [comment]
I'm also encountering this issue, but have not been able to reproduce it at all. Sentry is reporting that it only happens in Android. I'm using the following:

```
    "react-native-reanimated": "3.16.1",
    "react-native": "0.75.4",
```

**Comment by bglgwyng** [comment]
@johnnywang I haven't figured out it yet. However,  I suspect this error comes from another native crash. In my code, a code triggered a native crash in some conditions. And I removed it and this error was gone.

I mean, this error message has some problems and I think it needs to be fixed to be more friendly. However, it might be possible for you to fix your problem by removing other parts of your code.

**Comment by anthowm** [comment]
The original issue is not resolved the exception is coming from NodesManager I just put a try catch block to avoid crashes in prod but dunno from where is coming the exception because I'm not confident with the core code. 

`com.swmansion.reanimated.nativeProxy.AnimationFrameCallback.onAnimationFrame (AnimationFrameCallback.java)
com.swmansion.reanimated.NodesManager.onAnimationFrame (NodesManager.java:294)
com.swmansion.reanimated.NodesManager.-$$Nest$monAnimationFrame
com.swmansion.reanimated.NodesManager$2.doFrameGuarded (NodesManager.java:173)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.kt:22)
com.facebook.react.modules.core.ReactChoreographer.frameCallback$lambda$1 (ReactChoreographer.kt:60)
com.facebook.react.modules.core.ReactChoreographer.$r8$lambda$nSkFhrr5T7rop_XKwzlLov4NLLw
com.facebook.react.modules.core.ReactChoreographer$$ExternalSyntheticLambda0.doFrame (D8$$SyntheticClass)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1470)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:1480)
android.view.Choreographer.doCallbacks (Choreographer.java:1103)
android.view.Choreographer.doFrame (Choreographer.java:1000)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1455)
android.os.Handler.handleCallback (Handler.java:942)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loopOnce (Looper.java:223)
android.os.Looper.loop (Looper.java:324)
android.app.ActivityThread.main (ActivityThread.java:8486)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:582)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1061)`

**Comment by andrejpavlovic** [comment]
If I recall correctly, applying a patch based on https://github.com/software-mansion/react-native-reanimated/pull/6902 fixed it for me.

**Comment by anthowm** [comment]
@andrejpavlovic in my case I still got the crashes in prod with that patch, that patch fix this exception https://github.com/software-mansion/react-native-reanimated/issues/6724#issuecomment-2491467241
