### ISSUE TITLE
[3.16.2] sv.addListener is not a function (it is Object), js engine: reanimated

### ISSUE THREAD

**Issue by mgcrea** [software-mansion/react-native-reanimated#6741]
### Description

I'm encountering issues on basic drag&drop code that used to work well in previous versions of the library, with a js crash when calling `setCount` in the following snippet:

```ts
  const onDragEnd = () => {
    setCount(count => count + 1);
  };

  const handleDragEnd: DndProviderProps['onDragEnd'] = ({active, over}) => {
    'worklet';
    if (over) {
      console.log(`Current count is ${count}`);
      runOnJS(onDragEnd)();
    }
  };
```

That throws the following error:

```txt
console.js:589 ReanimatedError: sv.addListener is not a function (it is Object), js engine: reanimated
anonymous @ console.js:589
reactConsoleErrorHandler @ ExceptionsManager.js:168
anonymous @ setUpDeveloperTools.js:67
registerError @ LogBox.js:198
anonymous @ LogBox.js:68
overrideMethod @ backend.js:14284
reportException @ ExceptionsManager.js:110
handleException @ ExceptionsManager.js:158
handleError @ setUpErrorHandling.js:24
reportFatalError @ error-guard.js:49
reportFatalErrorOnJS @ errors.ts:93
````

Last version where it was tested to work was `3.5.4` but haven't been able to test it as it's no longer building with the latest RN release. Haven't had the time to bisect the exact regression version either, crashes on `3.6.1` and `3.6.2` 
 

 

### Steps to reproduce

1. clone https://github.com/mgcrea/react-native-dnd-expo-example
2. npm run dev
3. drag the "drag" box on the "drop" box
4. crash

When using expo the crash is native while it is properly caught JS-side when using a local native app.

### Snack or a link to a repository

https://github.com/mgcrea/react-native-dnd-expo-example

### Reanimated version

3.16.2

### React Native version

0.76.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

None

### Build type

None

### Device

iOS simulator

### Device model

iPhone 16

### Acknowledgements

Yes

**Comment by LunatiqueCoder** [comment]
@mgcrea Did you find any solution to this? I'm having the same issue trying to update `react-native-drax` library. (Drag n drop library)

**Comment by donpj** [comment]
I'm having the same issue on @mgcrea/react-native-dnd @mgcrea

**Comment by Hau-Hau** [comment]
Same issue.

```
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact: ReactHost{30}.handleHostException(message = "sv.removeListener is not a function (it is Object)
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact:
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact: TypeError: sv.removeListener is not a function (it is Object)
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact:     at stop (:1:2145)
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact:     at mappersTs3 (:1:167)
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact:     at apply (native)
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact:     at anonymous (:1:113)
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact:     at forEach (native)
08-27 13:12:03.732 21710 21710 W unknown:BridgelessReact:     at threadsTs5 (:1:80)")
08-27 13:12:03.733 21710 21710 E unknown:ReactNative: Exception in native call
08-27 13:12:03.733 21710 21710 E unknown:ReactNative: com.facebook.jni.CppException: sv.removeListener is not a function (it is Object)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:
08-27 13:12:03.733 21710 21710 E unknown:ReactNative: TypeError: sv.removeListener is not a function (it is Object)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:     at stop (:1:2145)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:     at mappersTs3 (:1:167)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:     at apply (native)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:     at anonymous (:1:113)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:     at forEach (native)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:     at threadsTs5 (:1:80)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at com.swmansion.worklets.AndroidUIScheduler.triggerUI(Native Method)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at com.swmansion.worklets.AndroidUIScheduler.d(SourceFile:12)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at com.swmansion.worklets.AndroidUIScheduler.a(SourceFile:1)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at com.swmansion.worklets.a.run(SourceFile:1)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at com.swmansion.worklets.AndroidUIScheduler$a.runGuarded(SourceFile:7)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at com.facebook.react.bridge.GuardedRunnable.run(SourceFile:1)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:958)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at android.os.Looper.loopOnce(Looper.java:205)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:294)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at android.app.ActivityThread.main(ActivityThread.java:8223)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at java.lang.reflect.Method.invoke(Native Method)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
08-27 13:12:03.733 21710 21710 E unknown:ReactNative:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact: ReactHost{30}.getOrCreateDestroyTask()
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact: ReactHost{30}.raiseSoftException(getOrCreateDestroyTask()): handleHostException(message = "sv.removeListener is not a function (it is Object)
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact:
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact: TypeError: sv.removeListener is not a function (it is Object)
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact:     at stop (:1:2145)
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact:     at mappersTs3 (:1:167)
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact:     at apply (native)
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact:     at anonymous (:1:113)
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact:     at forEach (native)
08-27 13:12:03.733 21710 29290 W unknown:BridgelessReact:     at threadsTs5 (:1:80)")
08-27 13:12:03.733 21710 29290 E unknown:ReactHost: Unhandled SoftException
08-27 13:12:03.733 21710 29290 E unknown:ReactHost: com.facebook.react.bridge.ReactNoCrashSoftException: raiseSoftException(getOrCreateDestroyTask()): handleHostException(message = "sv.removeListener is not a function (it is Object)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:
08-27 13:12:03.733 21710 29290 E unknown:ReactHost: TypeError: sv.removeListener is not a function (it is Object)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at stop (:1:2145)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at mappersTs3 (:1:167)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at apply (native)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at anonymous (:1:113)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at forEach (native)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at threadsTs5 (:1:80)")
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.facebook.react.runtime.ReactHostImpl.raiseSoftException(SourceFile:4)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.facebook.react.runtime.ReactHostImpl.getOrCreateDestroyTask(SourceFile:6)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.facebook.react.runtime.ReactHostImpl.lambda$destroy$7(SourceFile:26)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.facebook.react.runtime.ReactHostImpl.N(SourceFile:1)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.facebook.react.runtime.K.call(SourceFile:1)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.facebook.react.runtime.internal.bolts.Task$2.run(SourceFile:5)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at java.lang.Thread.run(Thread.java:1012)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost: Caused by: com.facebook.jni.CppException: sv.removeListener is not a function (it is Object)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:
08-27 13:12:03.733 21710 29290 E unknown:ReactHost: TypeError: sv.removeListener is not a function (it is Object)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at stop (:1:2145)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at mappersTs3 (:1:167)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at apply (native)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at anonymous (:1:113)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at forEach (native)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at threadsTs5 (:1:80)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.swmansion.worklets.AndroidUIScheduler.triggerUI(Native Method)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.swmansion.worklets.AndroidUIScheduler.d(SourceFile:12)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.swmansion.worklets.AndroidUIScheduler.a(SourceFile:1)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.swmansion.worklets.a.run(SourceFile:1)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.swmansion.worklets.AndroidUIScheduler$a.runGuarded(SourceFile:7)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.facebook.react.bridge.GuardedRunnable.run(SourceFile:1)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at android.os.Handler.handleCallback(Handler.java:958)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at android.os.Handler.dispatchMessage(Handler.java:99)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at android.os.Looper.loopOnce(Looper.java:205)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at android.os.Looper.loop(Looper.java:294)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at android.app.ActivityThread.main(ActivityThread.java:8223)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at java.lang.reflect.Method.invoke(Native Method)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
08-27 13:12:03.733 21710 29290 E unknown:ReactHost:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
```

**Comment by tomekzaw** [comment]
@Hau-Hau Do you use `Object.assign` to assign a new value to a shared value?

**Comment by Hau-Hau** [comment]
@tomekzaw 
No, I don't use `Object.assign`. In my code any update is performed by spread operator.

In my case structure looks like `SharedValue<{ [key: string]: SharedValue<Foo> }>`. From what I've observed error is triggered when I'm trying to access nested SharedValue.

**Comment by tomekzaw** [comment]
@Hau-Hau 

> spread operator

Spread operator transpiles into `Object.assign`.

> From what I've observed error is triggered when I'm trying to access nested SharedValue.

There's no such thing as "nested shared value", you cannot nest those.

**Comment by Hau-Hau** [comment]
What do you mean by that I cannot nest them?

Below code seems working.
```
const foo = useSharedValue("something");
const state = useSharedValue({
  foo
});
```

**Comment by tomekzaw** [comment]
@Hau-Hau You're not supposed to place a shared value inside another shared value. The inner "shared value" will lose its responsiveness. Even if it seems to be working, it's not. Please don't do that. It's not an officially supported feature and it can stop working anytime without prior notice. Instead, keep the object in a single shared value and use `useDerivedValue` hook if you want to create a "view" shared value of a single prop.
