### ISSUE TITLE
Building a for web with vite causes an error when doing a production build

### ISSUE THREAD

**Issue by dannyhw** [software-mansion/react-native-reanimated#6775]
### Description

When running in dev with vite everything works fine, when I run the build for production for example with `npm run build && npm run preview` in the repro then I get this error

Initially I ran into this error when working on a new vite framework for storybook but I found the same error present in a users example on the discussions here where it works on dev but fails when serving the static files.

```
index-DvzMhtGV.js:53 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at dl (index-DvzMhtGV.js:53:6327)
    at index-DvzMhtGV.js:53:48672
    at Array.forEach (<anonymous>)
    at Dc (index-DvzMhtGV.js:53:48646)
    at Object.a [as worklet] (index-DvzMhtGV.js:53:50781)
    at o (index-DvzMhtGV.js:53:13912)
```

![image](https://github.com/user-attachments/assets/88867119-b9ab-47f9-8516-09d9498fab0f)

### Steps to reproduce

in the repro:
1. click the terminal
2. ctrl + c to end the dev server
3. use the command `npm run build && npm run preview` to run a preview of the prod build
4. note the animation fails and open the browser console to see the error

in general: 
1. setup react native web with vite
2. add reanimated and add the babel plugin to the react plugin's babel config
3. add an animated component and attempt to animate it
3. build for prod

### Snack or a link to a repository

https://stackblitz.com/edit/vitejs-vite-wcfpnl?file=package.json

same repo from the stack blitz: 
https://github.com/dannyhw/vite-reanimated-web-prod-repro

to run here just do
`npm install`
`npm run build && npm run preview`

The example code is actually mostly taken from here: https://github.com/software-mansion/react-native-reanimated/discussions/5814

In which disabling strict mode fixes one problem but then in the build theres this new error

### Reanimated version

~3.16.3

### React Native version

^0.76.3

### Platforms

Web

### JavaScript runtime

V8

### Workflow

None

### Architecture

None

### Build type

Release app & production bundle

### Device

None

### Acknowledgements

Yes

**Comment by dannyhw** [comment]
I recognise that the setup is a bit strange but vite is now a more common target with the 'one' framework and also with storybook working really well with vite we want to support a way to preview react native web components with a vite setup, so far the main blocker is getting reanimated support done since most other packages we've been able to get working.

It's quite possible that we're just missing some global variable or some configuration but I'm really having a hard time figuring it out. Any help would be greatly appreciated.

**Comment by dannyhw** [comment]
I find my own solution eventually after digging through expo's babel preset

```
plugins: [
  [
    // this is a fix for reanimated not working in production
    '@babel/plugin-transform-modules-commonjs',
    {
      strict: false,
      strictMode: false, // prevent "use strict" injections
      allowTopLevelThis: true, // dont rewrite global `this` -> `undefined`
    },
  ],
  ...otherplugins
],
          ```

**Comment by jordmccord** [comment]
I've got the same issue using Storybook with vite, that plugin causes further issues with my setup. https://github.com/jordmccord/test-unistyles/blob/main/packages/test-ui/vite.config.ts

**Comment by jordmccord** [comment]
I managed to get everything working with the following `vite.config.ts`:
```js
import react from '@vitejs/plugin-react';
import babel from 'vite-plugin-babel';
import { defineConfig } from 'vite';

const extensions = [
  '.web.tsx',
  '.tsx',
  '.web.ts',
  '.ts',
  '.web.jsx',
  '.jsx',
  '.web.js',
  '.js',
  '.css',
  '.json',
  '.mjs',
];

const development = process.env.NODE_ENV === 'development';

export default defineConfig({
  clearScreen: true,
  plugins: [
    react({
      babel: {
        plugins: [
          '@babel/plugin-proposal-export-namespace-from',
          'react-native-reanimated/plugin',
        ],
      },
    }),
    ...(development
      ? []
      : [
          babel({
            include: [/node_modules\/(react-native|@react-native)/],
            babelConfig: {
              plugins: [
                [
                  // this is a fix for reanimated not working in production
                  '@babel/plugin-transform-modules-commonjs',
                  {
                    strict: false,
                    strictMode: false, // prevent "use strict" injections
                    allowTopLevelThis: true, // dont rewrite global `this` -> `undefined`
                  },
                ],
              ],
            },
          }),
        ]),
  ],
  define: {
    __DEV__: JSON.stringify(development),
    DEV: JSON.stringify(development),
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
    'global.__x': {},
    _frameTimestamp: undefined,
    _WORKLET: false,
  },
  resolve: {
    extensions,
    alias: {
      'react-native': 'react-native-web',
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      resolveExtensions: extensions,
      jsx: 'automatic',
      loader: { '.js': 'jsx' },
    },
  },
});
```
Took me a minute to piece everything together but now it's working in dev and when built in prod. Thanks @dannyhw for the suggestions.

**Comment by thanksyouall** [comment]
Thanks a lot! You saved my day. I've fixed expo libs.

```
include: [/node_modules\/(react-native|@react-native|expo-linear-gradient|expo-av)/],
```

**Comment by matthieugicquel** [comment]
After looking into it, the "root error" happening in vite production builds is something along the lines of `require is not defined` here:

https://github.com/software-mansion/react-native-reanimated/blob/1cc26a42c7ad64aab4f6aace25b65315319e186f/packages/react-native-reanimated/src/ReanimatedModule/js-reanimated/webUtils.web.ts#L10-L14

The error gets caught and not logged, some things are broken, and later it causes the "Object.keys" error we see in the console.

@dannyhw Seeing the config changes you did, maybe you had found out about that, but I don't see it mentioned so I'm adding the info here :)


Modifying this file to use `import`/`export` seems to be an ok fix:

- it works in vite dev and prod (tested through a storbyook with a custom config)
- it works with webpack (tested through nextjs)
- it's a coherent way forward: we should move away from using `require` in ES modules, more and more tools won't be ok with that

One piece is missing: why was this using dynamic requires in the first place? Maybe @tomekzaw you know something about that (found you in the git blame)? I wouldn't want to make a PR that just breaks some other scenario.

**Comment by tomekzaw** [comment]
> Modifying this file to use `import`/`export` seems to be an ok fix:

@matthieugicquel This won't work because in RN apps there's no `react-native-web` installed, so bundling will fail. That's the exact reason why there's a dynamic import.

**Comment by matthieugicquel** [comment]
> > Modifying this file to use `import`/`export` seems to be an ok fix:
> 
> @matthieugicquel This won't work because in RN apps there's no `react-native-web` installed, so bundling will fail. That's the exact reason why there's a dynamic import.

But now it's in a .web file so the file won't be looked at by metro at all when bundling for native, no?

**Comment by tomekzaw** [comment]
> But now it's in a .web file so the file won't be looked at by metro at all when bundling for native, no?

Oh, I haven't noticed that it's in a separate file now. In that case this might work properly. Feel free to submit a PR then.

**Comment by dannyhw** [comment]
@matthieugicquel nice job finding that, I can confirm that if I just work around these requires I'm able to get things working. Now I've got a pretty ugly workaround in my vite plugin for this but would be cool to be able to remove that.
