### ISSUE TITLE
Cannot build Android under expo SDK 37 

### ISSUE THREAD

**Issue by jcohenho** [software-mansion/react-native-reanimated#702]
After upgrading to expo SDK 37, I can no longer build for android. I'm using RN 0.61: 

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/projects/testapp/node_modules/react-native-reanimated/android/build.gradle' line: 89

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/user/projects/testapp/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/projects/testapp/node_modules/react-native-reanimated/android/build.gradle' line: 89

* What went wrong:
A problem occurred configuring project ':react-native-reanimated'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/user/projects/testapp/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at checkExecSyncError (child_process.js:603:11)
    at execFileSync (child_process.js:621:15)
    at runOnAllDevices (/Users/user/projects/testapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/user/projects/testapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at /Users/user/projects/testapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/user/projects/testapp/node_modules/@react-native-community/cli/build/index.js:182:9)
```

I tried adding the local.properties file along with the `sdk.dir` path but that did not work either. Any help would be much appreciated.

**Comment by jakub-gonet** [comment]
Hi, did you doublechecked you set env variables for android studio?
Namely:
```
ANDROID_HOME
ANDROID_SDK_ROOT ANDROID_AVD_HOME
```

**Comment by jcohenho** [comment]
I do not have these set, they are required? What values should I provide for them?

**Comment by jakub-gonet** [comment]
They may be required for gradle to work

Checkout some answers from this SO question
https://stackoverflow.com/questions/29391511/where-is-android-sdk-root-and-how-do-i-set-it/53138471

If you're using Linux / Mac set them in .bashrc / .zshrc / .profile to path where you have your sdk installed

Please report back if this helped resolving your issue

**Comment by jcohenho** [comment]
My environment variable config for ANDROID_SDK_ROOT and other variables somehow got corrupted when installing an unrelated app. Fixed the env vars and now the Android build works. Thanks so much!

**Comment by zhangpeng-lab** [comment]
?????

**Comment by Looskie** [comment]
?????
