### ISSUE TITLE
 Animated events must have event data

### ISSUE THREAD

**Issue by musicode** [software-mansion/react-native-reanimated#704]
```
java.lang.IllegalArgumentException: Animated events must have event data.
	at com.swmansion.reanimated.nodes.EventNode.receiveEvent(Unknown Source:50)
	at com.swmansion.gesturehandler.react.i.a(Unknown Source:8)
	at com.swmansion.reanimated.b.b(Unknown Source:47)
	at com.swmansion.reanimated.b.a(Unknown Source:25)
	at com.swmansion.reanimated.b.a(Unknown Source:0)
	at com.swmansion.reanimated.b$a.b(Unknown Source:2)
	at com.facebook.react.uimanager.e.a(Unknown Source:0)
	at com.facebook.react.modules.core.g$d.a(Unknown Source:46)
	at com.facebook.react.modules.core.a$a$a.doFrame(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
	at android.view.Choreographer.doFrame(Choreographer.java:772)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8169)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by jakub-gonet** [comment]
Hi @musicode,
thanks for reporting!

Can you provide a minimal working example on [snack](https://snack.expo.io/) that triggers this exception and provide versions of React, React Native, React Native Gesture Handler and React Native Reanimated?

**Comment by musicode** [comment]
I dont't know how to reproduce this issue, because this error stack is reported by a bug analysis system.

**Comment by jakub-gonet** [comment]
All right, could you provide then packages versions? It was happening before or after upgrade to certain version of gesture handler / reanimated?

**Comment by musicode** [comment]
```
    "react": "16.11.0",
    "react-native": "0.62.1",
    "react-native-device-info": "^5.5.3",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-permissions": "^2.0.10",
    "react-native-reanimated": "^1.7.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-simple-store": "^2.0.2",
    "react-native-swiper": "1.6.0-rc.3",
    "react-native-tab-view": "^2.13.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^4.4.5",
    "react-native-webview": "^9.0.1",
    "react-navigation": "4.3.3",
    "react-navigation-stack": "^2.3.7",
    "react-navigation-tabs": "^2.8.7",
```

I upgrade react-native to 0.62 last week.

**Comment by jakub-gonet** [comment]
It's probably related to [this](https://github.com/react-native-community/react-native-tab-view/issues/976) issue

**Comment by chgsilva** [comment]
same issue here, any solutions?

**Comment by jakub-gonet** [comment]
@chgsilva,
being honest I was unable to reproduce call stack - I get tab view expo example crashing, but couldn't get much more than that, maybe it's related to being in a release mode. Without inspecting what payload from RNGH causes event data to be null we're basically out of luck fixing this because I was only able to reproduce it in a release app.

If you have reproducible code that causes the crash and can be debugged it'd be really appreciated.

**Comment by drb1** [comment]
same issue in release mode, is there any solution

**Comment by mym0404** [comment]
same in Android

![image](https://user-images.githubusercontent.com/33388801/87433866-c7b6f500-c624-11ea-9b0b-034b5886a78d.png)

**Comment by aliceathens** [comment]
+1 same issues for our app in production:
`"@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/masked-view": "^0.1.9",
    "@react-native-community/netinfo": "^5.7.0",
    "@react-native-firebase/analytics": "7.1.2",
    "@react-native-firebase/app": "7.1.4",
    "@react-native-firebase/crashlytics": "7.1.3",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/drawer": "^5.4.0",
    "@react-navigation/material-top-tabs": "^5.2.12",
    "@react-navigation/native": "^5.1.4",
    "@react-navigation/stack": "^5.2.9",
    "base-64": "^0.1.0",
    "color": "^3.1.2",
    "compare-versions": "^3.6.0",
    "d3-shape": "^1.3.7",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.28",
    "prop-types": "^15.7.2",
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-bcrypt": "^2.4.0",
    "react-native-code-push": "^6.2.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "1.4.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-snap-carousel": "^3.9.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.0.3",
    "react-native-tab-view": "^2.14.4",
    "react-native-touch-id": "^4.4.1",
    "react-native-ux-cam": "^5.1.15",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^9.2.1",
    "react-redux": "5.1.0",
    "redux": "^3.7.2",
    "redux-form": "^7.0.3",
    "redux-saga": "0.16.0",
    "reselect": "^4.0.0"`

`Fatal Exception: java.lang.IllegalArgumentException: Animated events must have event data.
       at com.swmansion.reanimated.nodes.EventNode.receiveEvent(EventNode.java:63)
       at com.swmansion.gesturehandler.react.RNGestureHandlerStateChangeEvent.dispatch(RNGestureHandlerStateChangeEvent.java:80)
       at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:402)
       at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:148)
       at com.swmansion.reanimated.NodesManager.access$000(NodesManager.java:55)
       at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:108)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
       at android.view.Choreographer.doCallbacks(Choreographer.java:796)
       at android.view.Choreographer.doFrame(Choreographer.java:727)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by kangfenmao** [comment]
```
java.lang.IllegalArgumentException: Animated events must have event data.
	at com.swmansion.reanimated.nodes.EventNode.receiveEvent(EventNode.java:63)
	at com.swmansion.gesturehandler.react.RNGestureHandlerStateChangeEvent.dispatch(RNGestureHandlerStateChangeEvent.java:80)
	at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:394)
	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:148)
	at com.swmansion.reanimated.NodesManager.access$000(NodesManager.java:55)
	at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:108)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1055)
	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
	at android.view.Choreographer.doFrame(Choreographer.java:772)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by jakub-gonet** [comment]
I'm keeping eye on this issue, but any reproduction example would be very helpful.

**Comment by kangfenmao** [comment]
```java
@Override
  public void receiveEvent(int targetTag, String eventName, @Nullable WritableMap event) {
    if (event == null) {
      // throw new IllegalArgumentException("Animated events must have event data.");
      return;
    }

    for (int i = 0; i < mMapping.size(); i++) {
      EventMap eventMap = mMapping.get(i);
      Double value = eventMap.lookupValue(event);
      if (value != null) {
        mNodesManager.findNodeById(eventMap.nodeID, ValueNode.class).setValue(value);
      }
    }
  }
```

Don't throw an exception here. This caused a large number of android applications crash 😂

**Comment by jakub-gonet** [comment]
@kangfenmao, as I said [here](https://github.com/software-mansion/react-native-gesture-handler/pull/1089#issuecomment-663975545) I'd want to fix the root of the problem instead of ignoring malformed events.

**Comment by jakub-gonet** [comment]
Hi guys, could you check if https://github.com/software-mansion/react-native-gesture-handler/pull/1171 fixes those crashes for you?

**Comment by danigm87** [comment]
> Hi guys, could you check if [software-mansion/react-native-gesture-handler#1171](https://github.com/software-mansion/react-native-gesture-handler/pull/1171) fixes those crashes for you?

Will a release be created with this fix?

**Comment by zmnv** [comment]
@jakub-gonet hello! is it fixed for now moment? 

some of our users with Android has:
```
java.lang.IllegalArgumentException: Animated events must have event data.
    at com.swmansion.reanimated.nodes.EventNode.receiveEvent(EventNode.java:63)
```

**Comment by jakub-gonet** [comment]
Fix for that crash was included in the 1.8.1 release of the gesture handler.

**Comment by girish54321** [comment]
Hi @jakub-gonet there no version `1.8.1` can you tell me which one to install to fix this bug.

**Comment by jakub-gonet** [comment]
You can install any version from 1.8.0 upwards.

**Comment by girish54321** [comment]
Thanks, @jakub-gonet
