### ISSUE TITLE
Error building the example

### ISSUE THREAD

**Issue by raffaeler** [software-mansion/react-native-reanimated#710]
I just followed the steps at https://github.com/software-mansion/react-native-reanimated/tree/master/Example

Nothing more, nothing less.

This is the outcome:
```
yarn run v1.22.4
$ react-native start
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (H:\Samples\react-native-reanimated\Example\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:69:59)
    at getDefaultConfig (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:85:20)
    at load (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:121:25)
    at Object.runServer [as func] (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (H:\Samples\react-native-reanimated\Example\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:311:20)
    at Command.parseArgs (H:\Samples\react-native-reanimated\Example\node_modules\commander\index.js:654:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

HTH

**Comment by jakub-gonet** [comment]
Hi @raffaeler,
could you provide Reanimated version? Or you just ran it from master branch?

**Comment by raffaeler** [comment]
I started from the master branch: clone, yarn, etc. as written in the doc page.
I would expect the master is always  unbroken as I see/work in other repos.
Thanks

**Comment by jakub-gonet** [comment]
That's strange.

I just cloned the repo, run `cd react-native-reanimated && yarn && cd Example && yarn && yarn start` from directory and it worked flawlessly.

Do you have metro bundler installed globally by any chance?

You're using windows, right?

**Comment by raffaeler** [comment]
No, I didn't install anything global.
On other projects I am using npx and run the react native cli with that.
Yes, I'm on Windows

Is there a log I can post here?

**Comment by jakub-gonet** [comment]
I think this issue is related to windows path convention (Unix uses `/`, windows uses `\` which you have to double escape). I'll take a look at it, but unfortunately, I don't have windows machine handy to test it

**Comment by jakub-gonet** [comment]
@raffaeler, can you add line with:
```js
console.log(nodeModuleDirs);
```

in `Example/metro.config.js` right before `return blacklist(nodeModuleDirs);`, run `yarn start` and post the output of it?

**Comment by raffaeler** [comment]
apparently it doesn't hit the `getBlacklist()` function at all

**Comment by jakub-gonet** [comment]
Are you sure? I analyzed stacktrace and it's crashing on `Example/node_modules/metro-config/src/defaults/blacklist.js#34`, probably because `additionalBlacklist` is corrupted in some way. So `getBlacklist()` should be surely called.

It should look like that:
```js
function getBlacklist() {
  const nodeModuleDirs = [
    glob(`${path.resolve(__dirname, '..')}/node_modules/*`),
    glob(`${path.resolve(__dirname, '..')}/docs/*`),
    glob(`${path.resolve(__dirname, '..')}/e2e/*`),
    glob(`${path.resolve(__dirname)}/node_modules/*/node_modules/fbjs/*`),
    glob(
      `${path.resolve(
        __dirname
      )}/node_modules/*/node_modules/hoist-non-react-statics/*`
    ),
    glob(
      `${path.resolve(
        __dirname
      )}/node_modules/react-native/node_modules/@babel/*`
    ),
  ];
 
  console.log(nodeModuleDirs);

  return blacklist(nodeModuleDirs);
}
```

**Comment by raffaeler** [comment]
Here it is:
```
function getBlacklist() {
  console.log("****************************",  __dirname);
  const nodeModuleDirs = [
    glob(`${path.resolve(__dirname, '..')}/node_modules/*`),
    glob(`${path.resolve(__dirname, '..')}/docs/*`),
    glob(`${path.resolve(__dirname, '..')}/e2e/*`),
    glob(`${path.resolve(__dirname)}/node_modules/*/node_modules/fbjs/*`),
    glob(
      `${path.resolve(
        __dirname
      )}/node_modules/*/node_modules/hoist-non-react-statics/*`
    ),
    glob(
      `${path.resolve(
        __dirname
      )}/node_modules/react-native/node_modules/@babel/*`
    ),
  ];

  console.log("****************************",  nodeModuleDirs);
  return blacklist(nodeModuleDirs);
}
```

Output:
```
H:\Samples\react-native-reanimated\Example>yarn start
yarn run v1.22.4
$ react-native start
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (H:\Samples\react-native-reanimated\Example\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:69:59)
    at getDefaultConfig (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:85:20)
    at load (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:121:25)
    at Object.runServer [as func] (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (H:\Samples\react-native-reanimated\Example\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (H:\Samples\react-native-reanimated\Example\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:311:20)
    at Command.parseArgs (H:\Samples\react-native-reanimated\Example\node_modules\commander\index.js:654:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jakub-gonet** [comment]
That's interesting, I wonder why this is happening then.

Could you try adding some console.logs in `Example/node_modules/metro-config/src/defaults/blacklist.js`? It's crashing on c-tor of RegExp, so maybe logging content of additionalBlacklist, sharedBlacklist and escapeRegExp will give some insight about the crash.

**Comment by raffaeler** [comment]
The fault is in `escapeRegExp`. I added a log of `console.log` and printed out the parameters from the relevant branch `if (Object.prototype.toString.call(pattern) === "[object RegExp]")`

The line `*** escapeRegExp2 *** /.*\/__tests__\/.*/ .*\/__tests__\/.* \`  before the exception prints:

<div>
- pattern: /.*\/__tests__\/.*/
</div>
<div>
- pattern.source: .*\/__tests__\/.*
</div>
<div>
- path.sep: \
</div>


```

$ react-native start
*** blacklist ***
*** escapeRegExp1 ***
*** escapeRegExp2 *** /.*\/__fixtures__\/.*/ .*\/__fixtures__\/.* \
*** escapeRegExp1 ***
*** escapeRegExp2 *** /node_modules[/\\]react[/\\]dist[/\\].*/ node_modules[/\\]react[/\\]dist[/\\].* \
*** escapeRegExp1 ***
*** escapeRegExp2 *** /website\/node_modules\/.*/ website\/node_modules\/.* \
*** escapeRegExp1 ***
*** escapeRegExp2 *** /heapCapture\/bundle\.js/ heapCapture\/bundle\.js \
*** escapeRegExp1 ***
*** escapeRegExp2 *** /.*\/__tests__\/.*/ .*\/__tests__\/.* \
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.

[... cut ...]
```

**Comment by jakub-gonet** [comment]
Taking into consideration that blacklist doesn't even call a function defined in Reanimated config and likely unescaped slashes in `node_modules[\\\]react[\\\]dist[\\\]` are causing this issue I can't help you much with it. Try making an issue in the metro bundler repo.

**Comment by raffaeler** [comment]
Done, thank you anyway
